import { groupHoldings, visibleHoldings, pricedHoldingsSummary, portfolioTotal, coinMetadata, compactQuantity, priceUsd, displayDecimal, aud, valuationContext, displayValuation, valuationMoney, fxReferenceDate } from './model.mjs?v=20261006.known1';
const eye='<button class="icon-button privacy-toggle" data-privacy-toggle aria-label="Hide coins and values" aria-pressed="false" title="Hide coins and values"><svg viewBox="0 0 24 24" width="23" height="23" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/><path class="eye-slash" d="m3 3 18 18"/></svg></button>';
export function createDetails({getModel,getCurrency=()=>displayValuation(getModel()).currency,renderHoldings,setPrivacyHidden,isPrivacyHidden,esc,when}){
 const $=id=>document.getElementById(id);let sequence=0,portfolioReturn='#portfolio',coinReturn='#holdings',portfolioTrigger=null,coinTrigger=null,coinTriggerKey=null;
 const coinRoutes=new Map();let renderedModel=null,renderedCoinKey=null;
 const link=document.createElement('link');link.rel='stylesheet';link.href='portfolio/details.css?v=20261002.details1';document.head.append(link);
 function windowHTML(id,title,contents){return `<div class="dialog-heading"><h2 id="${id}Title">${title}</h2><div class="staking-window-actions">${eye}<button class="button" data-detail-close="${id}" aria-label="Close ${title.toLowerCase()}">Close</button></div></div><div class="privacy-placeholder privacy-coins" data-privacy-placeholder hidden><p class="privacy-dots" aria-hidden="true">••••••</p><p>Details hidden</p><span>Tap the eye to show them again</span></div><div data-private>${contents}</div>`;}
 const overview=document.createElement('dialog');overview.id='portfolioDialog';overview.className='staking-window portfolio-window';overview.setAttribute('aria-labelledby','portfolioDialogTitle');overview.innerHTML=windowHTML('portfolioDialog','Portfolio',`<div id="portfolioDetailEmpty" class="empty-detail"><p>Sign in to view your private portfolio.</p><button class="button" data-connection>Connection details</button></div><div id="portfolioDetailData" hidden><div class="detail-summary"><p id="detailAccountScope" class="eyebrow"></p><h3 id="detailValueLabel">Priced exposure</h3><p class="detail-value" id="detailValue">—</p><p id="detailCoverage"></p><p class="fine-print">Held liquid coins + staked principal, counted once. Unminted estimates are excluded.</p></div><section class="all-holdings"><div class="panel-heading"><h3>Combined holdings</h3><span class="small-badge">READ-ONLY</span></div><p class="fine-print">Coins combined across the selected wallets. Holdings worth $5 or less in the selected currency are hidden; totals still include them. Select a coin for details.</p><div class="holdings-scroll"><table class="holdings-table"><caption class="sr-only">Combined held quantities and indicative values, including separate staking positions once.</caption><thead><tr><th>Asset</th><th>Combined balance</th><th>Indicative AUD</th></tr></thead><tbody id="allHoldingsBody"></tbody></table></div><p class="fine-print">Unpriced holdings are hidden. Asset coverage may be incomplete.</p></section></div>`);
 const coin=document.createElement('dialog');coin.id='coinDialog';coin.className='staking-window coin-window';coin.setAttribute('aria-labelledby','coinDialogTitle');coin.innerHTML=windowHTML('coinDialog','Coin details',`<div id="coinDetailEmpty" class="empty-detail"><p>Select a recorded coin from Holdings after sign-in.</p><button class="button" data-connection>Connection details</button></div><div id="coinDetailData" hidden><div id="coinPosition"></div><section><h3>Wallet breakdown</h3><div id="coinWallets"></div></section><section><h3>Token &amp; sources</h3><div id="coinSources"></div></section><section class="activity-empty"><h3>Activity</h3><p>Wallet activity history is not connected.</p><p class="fine-print">Deposits, transfers, buys, sells and fees are not available here. A balance snapshot is not a transaction record.</p></section></div>`);
 document.body.append(overview,coin);setPrivacyHidden(isPrivacyHidden());
 function currentCoin(){const key=coinRoutes.get(location.hash);return key?visibleHoldings(groupHoldings(getModel()),getCurrency()).find(h=>h.key===key)||null:null;}
 function render(){
  const current=getModel(),ready=!!current?.snapshot,modelChanged=current!==renderedModel; $('portfolioDetailEmpty').hidden=ready;$('portfolioDetailData').hidden=!ready;
  if(ready){if(modelChanged){const all=groupHoldings(current),display=displayValuation(current,getCurrency());$('detailAccountScope').textContent=(current.account.kind==='smsf'?'Super':'Personal')+' · watched wallets';$('detailValueLabel').textContent=display.label;$('detailValue').textContent=valuationMoney(display.value,display.currency);$('detailCoverage').textContent=`${current.wallets.length} watched wallets · ${display.pricedAssets} priced held assets${display.unpricedAssets?' · '+display.unpricedAssets+' excluded or unpriced':''}${display.pendingWallets?' · '+display.pendingNetworks.join(', ')+' balance unknown':''}. ${display.incomplete?'Incomplete valuation. ':''}${display.fxUnavailable?'AUD conversion unavailable. Select USD or use Refresh balances on Home.':''}`;renderHoldings('allHoldingsBody',all);}}
  else{$('detailValue').textContent='—';$('allHoldingsBody').replaceChildren();}
  const holding=ready?currentCoin():null;$('coinDetailEmpty').hidden=!!holding;$('coinDetailData').hidden=!holding;
  if(holding)renderCoin(current,holding,modelChanged||holding.key!==renderedCoinKey);else for(const id of ['coinPosition','coinWallets','coinSources'])$(id).replaceChildren();
  renderedModel=current;renderedCoinKey=holding?.key||null;setPrivacyHidden(isPrivacyHidden());
 }
 function renderCoin(current,h,refreshFacts){
  const currency=getCurrency(),key=currency==='USD'?'usd':'aud';
  const meta=coinMetadata(h),name=meta?.name||h.symbol||'Token',timing=valuationContext(current.snapshot);
  if(refreshFacts){$('coinPosition').innerHTML=`<div class="coin-detail-heading">${meta?`<img src="assets/coins/${meta.icon}" width="56" height="56" alt="">`:''}<div><h3>${esc(name)}</h3><p>${esc(h.symbol)} · ${h.chainId===1?'Ethereum':'Chain '+esc(h.chainId)}</p></div></div><p class="detail-value">${esc(valuationMoney(h[key],currency))}</p><p class="coin-quantity">${esc(compactQuantity(h.quantity))} ${esc(h.symbol)}</p><details class="exact-quantity"><summary>Exact quantity</summary><p class="wallet-address">${esc(displayDecimal(h.quantity,255))} ${esc(h.symbol)}</p></details><p class="fine-print">${esc(compactQuantity(h.liquid))} liquid · ${esc(compactQuantity(h.staked))} staked principal</p><p class="fine-print">${h[key]==null?currency+' value unavailable. ':''}${h.unreliable?'Price unreliable; excluded from priced exposure. ':''}${h.quote?.low_liquidity?'Low liquidity. ':h.quote?.confidence==='low'?'Low confidence. ':''}Indicative, before fees and slippage. Unminted rewards are excluded.</p><p class="fine-print">Balances observed ${esc(when(timing.balanceStart))}${timing.carried?' · Carried forward, not refreshed':''}</p>`;
  $('coinWallets').innerHTML=current.wallets.map(w=>{const part=groupHoldings({...current,balances:current.balances.filter(b=>b.wallet_id===w.id),stakes:current.stakes.filter(s=>s.wallet_id===w.id)}).find(p=>p.key===h.key);if(!part)return '';const address=String(w.address||''),short=address.length>15?address.slice(0,8)+'…'+address.slice(-6):address;return `<div class="wallet-breakdown"><div><p class="wallet-address">${esc(short||'Watched wallet')}</p><details><summary>Full address</summary><p class="wallet-address">${esc(address)}</p></details></div><div><strong>${esc(compactQuantity(part.quantity))} ${esc(h.symbol)}</strong><p>${esc(valuationMoney(part[key],currency))}</p><p class="fine-print">${esc(compactQuantity(part.liquid))} liquid · ${esc(compactQuantity(part.staked))} staked</p></div></div>`;}).join('')||'<p>No verified wallet breakdown is available.</p>';
  $('coinSources').innerHTML=`<dl class="token-facts"><dt>Network</dt><dd>${h.chainId===1?'Ethereum':'Chain '+esc(h.chainId)}</dd><dt>Contract</dt><dd class="wallet-address">${esc(h.assetId==='native'?'Native network asset':h.assetId)}</dd><dt>Decimals</dt><dd>${esc(h.decimals)}</dd><dt>Token price · USD</dt><dd>${esc(priceUsd(h.unitPriceUsd))}</dd><dt>Position value · USD</dt><dd>${esc(h.usd==null?'Unavailable':aud(h.usd).replace('A$','US$'))}</dd><dt>Quote source</dt><dd>${esc(h.priceSource||'Unavailable')}</dd><dt>Quote observed</dt><dd>${esc(when(h.priceAt))}</dd><dt>Quote retrieved</dt><dd>${esc(when(h.quote?.retrieved_at))}</dd><dt>AUD conversion</dt><dd>${esc(timing.fxSource||'Unavailable')} · ${esc(fxReferenceDate(current.snapshot)?'Reference date '+fxReferenceDate(current.snapshot)+' · Daily rate':when(timing.fxAt))}</dd></dl>`;
  }
 }
 function close(which){const fromCoin=which==='coinDialog',target=fromCoin?coinReturn:portfolioReturn;history.replaceState(null,'',target);window.dispatchEvent(new window.Event('hashchange'));const context=['#overview','#holdings'].includes(target)?overview:['#staking','#ladder','#rewards'].includes(target)?$('stakingDialog'):$('portfolioView');const trigger=fromCoin?[...context.querySelectorAll('[data-coin-key]')].find(row=>row.dataset.coinKey===coinTriggerKey)||coinTrigger:portfolioTrigger;const ownerDialog=trigger?.closest('dialog');if(trigger?.isConnected&&!trigger.closest('[hidden]')&&(!ownerDialog||ownerDialog.open))trigger.focus();else (document.querySelector('dialog[open] [data-privacy-toggle]')||document.querySelector('.topbar [data-privacy-toggle]'))?.focus();}
 function route(){const hash=location.hash,isCoin=coinRoutes.has(hash),isOverview=['#overview','#holdings'].includes(hash);if(!isCoin&&coin.open)coin.close();if(!isOverview&&overview.open)overview.close();if(isCoin){if(!coin.open)coin.showModal();document.title='Sea Chef Labs · Coin details';}else if(isOverview){if(!overview.open)overview.showModal();$('portfolioDialogTitle').textContent=hash==='#holdings'?'Holdings':'Portfolio';document.querySelectorAll('[data-detail-route]').forEach(a=>a.setAttribute('aria-current',a.getAttribute('href')===hash?'page':'false'));document.title='Sea Chef Labs · '+(hash==='#holdings'?'Holdings':'Portfolio details');}if(isCoin||isOverview)render();}
 document.addEventListener('click',event=>{const row=event.target.closest('[data-coin-key]');if(row){event.preventDefault();coinTrigger=row;coinTriggerKey=row.dataset.coinKey;coinReturn=['#overview','#holdings','#staking','#ladder','#rewards'].includes(location.hash)?location.hash:'#portfolio';const hash='#coin-'+(++sequence);coinRoutes.set(hash,row.dataset.coinKey);location.hash=hash;route();return;}const closer=event.target.closest('[data-detail-close]');if(closer){close(closer.dataset.detailClose);return;}});
 for(const d of [overview,coin])d.addEventListener('cancel',e=>{e.preventDefault();close(d.id);});window.addEventListener('hashchange',route);
 return {route,openCoin(key,trigger){coinTrigger=trigger;coinTriggerKey=key;coinReturn=['#overview','#holdings','#staking','#ladder','#rewards'].includes(location.hash)?location.hash:'#portfolio';const hash='#coin-'+(++sequence);coinRoutes.set(hash,key);location.hash=hash;route();},openPortfolio(trigger,target='#overview'){if(!overview.contains(trigger))portfolioTrigger=trigger;portfolioReturn=location.hash==='#tools'?'#tools':'#portfolio';location.hash=target;route();},update({force=false}={}){if(force)renderedModel=null;render();},clear(){renderedModel=null;renderedCoinKey=null;render();}};
}
