import { groupHoldings, pricedHoldingsSummary, portfolioTotal, coinMetadata, compactQuantity, priceUsd, displayDecimal, aud, valuationContext } from './model.mjs?v=20261003.personal1';
import {renderRecordedChart,bindRecordedChart} from './visuals.mjs?v=20261003.personal1';
import { recordedHistorySummary } from './history.mjs?v=20261002.details1';
const ranges=[['1H','1H'],['1D','1D'],['1W','1W'],['1M','1M'],['1Y','1Y'],['MAX','MAX']];
const durations={'1H':3600000,'1D':86400000,'1W':7*86400000,'1M':30*86400000,'1Y':365*86400000};
const eye='<button class="icon-button privacy-toggle" data-privacy-toggle aria-label="Hide coins and values" aria-pressed="false" title="Hide coins and values"><svg viewBox="0 0 24 24" width="23" height="23" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/><path class="eye-slash" d="m3 3 18 18"/></svg></button>';
export function createDetails({getModel,readHistoryModels,renderHoldings,setPrivacyHidden,isPrivacyHidden,onAccessDenied,onHeadlineChange,esc,when}){
 const $=id=>document.getElementById(id);let selectedRange='1D',coinRange='1D',coinMetric='price',sequence=0,request=0,historyBusy=false,historyError=false,pendingHeadline=false,portfolioReturn='#portfolio',coinReturn='#holdings',portfolioTrigger=null,coinTrigger=null,coinTriggerKey=null;
 const coinRoutes=new Map(),savedModels=new Map();let loadedAccount=null,renderedModel=null,renderedCoinKey=null;
 const link=document.createElement('link');link.rel='stylesheet';link.href='portfolio/details.css?v=20261002.details1';document.head.append(link);
 function windowHTML(id,title,contents){return `<div class="dialog-heading"><h2 id="${id}Title">${title}</h2><div class="staking-window-actions">${eye}<button class="button" data-detail-close="${id}" aria-label="Close ${title.toLowerCase()}">Close</button></div></div><div class="privacy-placeholder privacy-coins" data-privacy-placeholder hidden><p class="privacy-dots" aria-hidden="true">••••••</p><p>Details hidden</p><span>Tap the eye to show them again</span></div><div data-private>${contents}</div>`;}
 const overview=document.createElement('dialog');overview.id='portfolioDialog';overview.className='staking-window portfolio-window';overview.setAttribute('aria-labelledby','portfolioDialogTitle');overview.innerHTML=windowHTML('portfolioDialog','Portfolio',`<div id="portfolioDetailEmpty" class="empty-detail"><p>Sign in to view your private portfolio.</p><button class="button" data-connection>Connection details</button></div><div id="portfolioDetailData" hidden><div class="detail-summary"><p id="detailAccountScope" class="eyebrow"></p><h3 id="detailValueLabel">Priced exposure</h3><p class="detail-value" id="detailValue">—</p><p id="detailCoverage"></p><p class="fine-print">Held liquid coins + staked principal, counted once. Unminted estimates are excluded.</p></div><div class="detail-tabs"><a href="#overview" data-detail-route="overview">Overview</a><a href="#holdings" data-detail-route="holdings">Holdings</a></div><section id="portfolioDetailHistory"><h3>Priced holdings value</h3><p class="fine-print">Recorded AUD value. Changes include holdings and market prices; deposits and withdrawals are not separated. This is not investment profit.</p><div class="periods detail-periods" role="group" aria-label="Portfolio history range">${rangeButtons('portfolio')}</div><div id="portfolioHistoryOutput"></div></section><section class="all-holdings"><div class="panel-heading"><h3>Combined holdings</h3><span class="small-badge">READ-ONLY</span></div><p class="fine-print">All recorded coins in this account, combined across its watched wallets. Select a coin for details.</p><div class="holdings-scroll"><table class="holdings-table"><caption class="sr-only">Combined held quantities and indicative values, including separate staking positions once.</caption><thead><tr><th>Asset</th><th>Combined balance</th><th>Indicative AUD</th></tr></thead><tbody id="allHoldingsBody"></tbody></table></div><p class="fine-print">A complete list of recorded assets, not proof that every asset on every network has been discovered.</p></section></div>`);
 const coin=document.createElement('dialog');coin.id='coinDialog';coin.className='staking-window coin-window';coin.setAttribute('aria-labelledby','coinDialogTitle');coin.innerHTML=windowHTML('coinDialog','Coin details',`<div id="coinDetailEmpty" class="empty-detail"><p>Select a recorded coin from Holdings after sign-in.</p><button class="button" data-connection>Connection details</button></div><div id="coinDetailData" hidden><div id="coinPosition"></div><section class="coin-history"><div class="detail-tabs" role="group" aria-label="Coin history measure"><button data-coin-metric="price" aria-pressed="true">Price history · USD</button><button data-coin-metric="value" aria-pressed="false">Position value · AUD</button></div><p class="fine-print" id="coinHistoryExplanation"></p><div class="periods detail-periods" role="group" aria-label="Coin history range">${rangeButtons('coin')}</div><div id="coinHistoryOutput"></div></section><section><h3>Wallet breakdown</h3><div id="coinWallets"></div></section><section><h3>Token &amp; sources</h3><div id="coinSources"></div></section><section class="activity-empty"><h3>Activity</h3><p>Wallet activity history is not connected.</p><p class="fine-print">Deposits, transfers, buys, sells and fees are not available here. A balance snapshot is not a transaction record.</p></section></div>`);
 document.body.append(overview,coin);setPrivacyHidden(isPrivacyHidden());
 function rangeButtons(scope){return ranges.map(([key,label])=>`<button data-detail-range="${key}" data-range-scope="${scope}" aria-pressed="${key==='1D'}">${label}</button>`).join('');}
 function currentCoin(){const key=coinRoutes.get(location.hash);return key?groupHoldings(getModel()).find(h=>h.key===key)||null:null;}
 function renderChart(id,summary){
  summary={...summary,change:summary.change?.value??summary.change};const target=$(id);target.innerHTML=renderRecordedChart(summary,{loading:historyBusy,error:historyError});bindRecordedChart(target,summary);
 }
 function selectedModels(range){const current=getModel();if(!current)return [];const cutoff=range==='MAX'?-Infinity:Date.now()-durations[range];return (current.history||[]).filter(s=>{const at=Date.parse(valuationContext(s).balanceStart);return !Number.isFinite(at)||at>=cutoff;}).map(snapshot=>snapshot.id===current.snapshot?.id?current:savedModels.get(snapshot.id)||{account:current.account,wallets:current.wallets,snapshot,balances:[],stakes:[],rewardEstimates:[]});}
 function summaryFor(range,coinKey=null,metric='value'){const result=recordedHistorySummary({models:selectedModels(range),currentModel:getModel(),rangeKey:range,coinKey,metric,historyLimited:(getModel()?.history?.length||0)>=730});return {...result,metric,change:{available:result.changeAvailable,value:result.change,formatted:result.changeFormatted,baselineAt:result.baselineAt,endpointAt:result.endpointAt}};}
 function historySummary(range=selectedRange){return summaryFor(range);}
 function render(){
  const current=getModel(),ready=!!current?.snapshot,modelChanged=current!==renderedModel; $('portfolioDetailEmpty').hidden=ready;$('portfolioDetailData').hidden=!ready;
  if(ready){if(modelChanged){const all=groupHoldings(current),priced=pricedHoldingsSummary(all),total=portfolioTotal(current);$('detailAccountScope').textContent=(current.account.kind==='smsf'?'Super':'Personal')+' · watched wallets';$('detailValueLabel').textContent=total==null?'Priced exposure':'Total recorded exposure';$('detailValue').textContent=aud(total??priced.value);$('detailCoverage').textContent=`${current.wallets.length} watched wallets · ${priced.pricedAssets} priced held assets${priced.unpricedAssets?' · '+priced.unpricedAssets+' excluded or unpriced':''}. ${total==null?'Incomplete valuation.':''}`;renderHoldings('allHoldingsBody',all);}renderChart('portfolioHistoryOutput',historySummary());onHeadlineChange(historySummary('1D'));}
  else{$('detailValue').textContent='—';$('allHoldingsBody').replaceChildren();$('portfolioHistoryOutput').replaceChildren();}
  const holding=ready?currentCoin():null;$('coinDetailEmpty').hidden=!!holding;$('coinDetailData').hidden=!holding;
  if(holding)renderCoin(current,holding,modelChanged||holding.key!==renderedCoinKey);else for(const id of ['coinPosition','coinWallets','coinSources','coinHistoryOutput'])$(id).replaceChildren();
  for(const b of document.querySelectorAll('[data-detail-range]'))b.setAttribute('aria-pressed',String(b.dataset.detailRange===(b.dataset.rangeScope==='coin'?coinRange:selectedRange)));
  for(const b of document.querySelectorAll('[data-coin-metric]'))b.setAttribute('aria-pressed',String(b.dataset.coinMetric===coinMetric));
  renderedModel=current;renderedCoinKey=holding?.key||null;setPrivacyHidden(isPrivacyHidden());
 }
 function renderCoin(current,h,refreshFacts){
  const meta=coinMetadata(h),name=meta?.name||h.symbol||'Token',timing=valuationContext(current.snapshot);
  if(refreshFacts){$('coinPosition').innerHTML=`<div class="coin-detail-heading">${meta?`<img src="assets/coins/${meta.icon}" width="56" height="56" alt="">`:''}<div><h3>${esc(name)}</h3><p>${esc(h.symbol)} · ${h.chainId===1?'Ethereum':'Chain '+esc(h.chainId)}</p></div></div><p class="detail-value">${esc(aud(h.aud))}</p><p class="coin-quantity">${esc(compactQuantity(h.quantity))} ${esc(h.symbol)}</p><details class="exact-quantity"><summary>Exact quantity</summary><p class="wallet-address">${esc(displayDecimal(h.quantity,255))} ${esc(h.symbol)}</p></details><p class="fine-print">${esc(compactQuantity(h.liquid))} liquid · ${esc(compactQuantity(h.staked))} staked principal</p><p class="fine-print">${h.aud==null?'AUD value unavailable. ':''}${h.unreliable?'Price unreliable; excluded from priced exposure. ':''}${h.quote?.low_liquidity?'Low liquidity. ':h.quote?.confidence==='low'?'Low confidence. ':''}Indicative, before fees and slippage. Unminted rewards are excluded.</p><p class="fine-print">Balances observed ${esc(when(timing.balanceStart))}${timing.carried?' · Carried forward, not refreshed':''}</p>`;
  $('coinWallets').innerHTML=current.wallets.map(w=>{const part=groupHoldings({...current,balances:current.balances.filter(b=>b.wallet_id===w.id),stakes:current.stakes.filter(s=>s.wallet_id===w.id)}).find(p=>p.key===h.key);if(!part)return '';const address=String(w.address||''),short=address.length>15?address.slice(0,8)+'…'+address.slice(-6):address;return `<div class="wallet-breakdown"><div><p class="wallet-address">${esc(short||'Watched wallet')}</p><details><summary>Full address</summary><p class="wallet-address">${esc(address)}</p></details></div><div><strong>${esc(compactQuantity(part.quantity))} ${esc(h.symbol)}</strong><p>${esc(aud(part.aud))}</p><p class="fine-print">${esc(compactQuantity(part.liquid))} liquid · ${esc(compactQuantity(part.staked))} staked</p></div></div>`;}).join('')||'<p>No verified wallet breakdown is available.</p>';
  $('coinSources').innerHTML=`<dl class="token-facts"><dt>Network</dt><dd>${h.chainId===1?'Ethereum':'Chain '+esc(h.chainId)}</dd><dt>Contract</dt><dd class="wallet-address">${esc(h.assetId==='native'?'Native network asset':h.assetId)}</dd><dt>Decimals</dt><dd>${esc(h.decimals)}</dd><dt>Token price · USD</dt><dd>${esc(priceUsd(h.unitPriceUsd))}</dd><dt>Position value · USD</dt><dd>${esc(h.usd==null?'Unavailable':aud(h.usd).replace('A$','US$'))}</dd><dt>Quote source</dt><dd>${esc(h.priceSource||'Unavailable')}</dd><dt>Quote observed</dt><dd>${esc(when(h.priceAt))}</dd><dt>Quote retrieved</dt><dd>${esc(when(h.quote?.retrieved_at))}</dd><dt>AUD conversion</dt><dd>${esc(timing.fxSource||'Unavailable')} · ${esc(when(timing.fxAt))}</dd></dl>`;
  }$('coinHistoryExplanation').textContent=coinMetric==='price'?'Recorded USD token prices from saved wallet observations. Points use balance observation dates; quote times appear in the exact table. This is not a continuous market candle feed.':'Recorded AUD value of your liquid tokens and staked principal. Holdings changes and market prices both affect this value; this is not P&L.';
  const summary=summaryFor(coinRange,h.key,coinMetric);renderChart('coinHistoryOutput',summary,coinMetric==='price');
 }
 async function ensureHistory({headline=false}={}){
  if(headline)pendingHeadline=true;const current=getModel();if(!current?.snapshot||historyBusy)return;
  const range=coin.open?coinRange:overview.open?selectedRange:'1D',cutoff=Math.min(range==='MAX'?-Infinity:Date.now()-durations[range],pendingHeadline?Date.now()-durations['1D']:Infinity);pendingHeadline=false;
  const wanted=(current.history||[]).filter(s=>Date.parse(s.observed_at)>=cutoff&&s.provenance?.valuation?.basis==='fresh_pinned_balances'&&s.provenance?.valuation?.balances_refreshed===true&&!savedModels.has(s.id)&&s.id!==current.snapshot.id);
  if(!wanted.length){render();return;}
  const id=++request;historyBusy=true;historyError=false;render();
  try{const result=await readHistoryModels({...current,history:wanted});if(id!==request||getModel()!==current)return;if(result.status==='signed-out'){onAccessDenied();return;}if(result.status!=='ready'){historyError=true;return;}for(const m of result.models)savedModels.set(m.snapshot.id,m);}
  catch{if(id===request)historyError=true;}
  finally{if(id===request){historyBusy=false;render();const nowRange=coin.open?coinRange:overview.open?selectedRange:'1D';if(!historyError&&(nowRange!==range||pendingHeadline))void ensureHistory();}}
 }
 function close(which){const fromCoin=which==='coinDialog',target=fromCoin?coinReturn:portfolioReturn;history.replaceState(null,'',target);window.dispatchEvent(new window.Event('hashchange'));const context=['#overview','#holdings'].includes(target)?overview:['#staking','#ladder','#rewards'].includes(target)?$('stakingDialog'):$('portfolioView');const trigger=fromCoin?[...context.querySelectorAll('[data-coin-key]')].find(row=>row.dataset.coinKey===coinTriggerKey)||coinTrigger:portfolioTrigger;const ownerDialog=trigger?.closest('dialog');if(trigger?.isConnected&&!trigger.closest('[hidden]')&&(!ownerDialog||ownerDialog.open))trigger.focus();else (document.querySelector('dialog[open] [data-privacy-toggle]')||document.querySelector('.topbar [data-privacy-toggle]'))?.focus();}
 function route(){const hash=location.hash,isCoin=coinRoutes.has(hash),isOverview=['#overview','#holdings'].includes(hash);if(!isCoin&&coin.open)coin.close();if(!isOverview&&overview.open)overview.close();if(isCoin){if(!coin.open)coin.showModal();document.title='Sea Chef Labs · Coin details';}else if(isOverview){if(!overview.open)overview.showModal();$('portfolioDetailHistory').hidden=hash==='#holdings';$('portfolioDialogTitle').textContent=hash==='#holdings'?'Holdings':'Portfolio';document.querySelectorAll('[data-detail-route]').forEach(a=>a.setAttribute('aria-current',a.getAttribute('href')===hash?'page':'false'));document.title='Sea Chef Labs · '+(hash==='#holdings'?'Holdings':'Portfolio details');}if(isCoin||isOverview){render();void ensureHistory();}}
 document.addEventListener('click',event=>{const row=event.target.closest('[data-coin-key]');if(row){event.preventDefault();coinTrigger=row;coinTriggerKey=row.dataset.coinKey;coinReturn=['#overview','#holdings','#staking','#ladder','#rewards'].includes(location.hash)?location.hash:'#portfolio';const hash='#coin-'+(++sequence);coinRoutes.set(hash,row.dataset.coinKey);location.hash=hash;route();return;}const closer=event.target.closest('[data-detail-close]');if(closer){close(closer.dataset.detailClose);return;}const period=event.target.closest('[data-detail-range]');if(period){if(period.dataset.rangeScope==='coin')coinRange=period.dataset.detailRange;else selectedRange=period.dataset.detailRange;render();void ensureHistory();return;}const metric=event.target.closest('[data-coin-metric]');if(metric){coinMetric=metric.dataset.coinMetric;render();void ensureHistory();}});
 for(const d of [overview,coin])d.addEventListener('cancel',e=>{e.preventDefault();close(d.id);});window.addEventListener('hashchange',route);
 return {route,openCoin(key,trigger){coinTrigger=trigger;coinTriggerKey=key;coinReturn=['#overview','#holdings','#staking','#ladder','#rewards'].includes(location.hash)?location.hash:'#portfolio';const hash='#coin-'+(++sequence);coinRoutes.set(hash,key);location.hash=hash;route();},openPortfolio(trigger,target='#overview'){if(!overview.contains(trigger))portfolioTrigger=trigger;portfolioReturn=['#research','#tools'].includes(location.hash)?location.hash:'#portfolio';location.hash=target;route();},update(){const current=getModel();if(loadedAccount!==current?.account?.id){++request;historyBusy=false;historyError=false;pendingHeadline=false;savedModels.clear();loadedAccount=current?.account?.id||null;}render();if(overview.open||coin.open)void ensureHistory();},clear(){++request;historyBusy=false;historyError=false;pendingHeadline=false;savedModels.clear();render();},loadHeadline(){void ensureHistory({headline:true});}};
}
