import {calculateTradePlan,formatDraftTicket} from './trade-plan.mjs?v=20261003.desk1';
import {readMarketReference,MARKET_DOCUMENTATION} from './market-reference.mjs?v=20261003.charts1';
import {createMarketChart} from './market-chart.mjs?v=20261003.charts1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>v!==''&&v!=null&&Number.isFinite(Number(v))?Number(v):null;
const fmt=v=>v==null?'—':new Intl.NumberFormat('en-AU',{maximumSignificantDigits:9}).format(v);
const stamp=v=>new Date(v).toLocaleString('en-AU',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'});
const coinOptions=[['BTC','Bitcoin'],['ETH','Ethereum'],['SOL','Solana'],['XRP','XRP'],['HBAR','Hedera'],['PEPE','Pepe'],['DOGE','Dogecoin'],['LINK','Chainlink'],['SUI','Sui']];
const fields=['baseAsset','quoteCurrency','budget','entry','stop','target','entryFeePercent','exitFeePercent','slippagePercent','riskBudget','trailingActivation','trailingCallbackPercent'];
const levels=[{field:'entry',label:'Buy limit',color:'#92dacf'},{field:'stop',label:'Stop trigger',color:'#ffa4aa'},{field:'target',label:'Take profit',color:'#c5b5ff'},{field:'trailingActivation',label:'Trail activation',color:'#e9c283'}];
export function createTradePlanner({container,onRender=()=>{},fetchMarket=readMarketReference,chartFactory=createMarketChart}={}){
 let market=null,loading=false,marketMessage='',controller=null,request=0,ticketOpen=false,interval='4h',chartView=null,chartStatus='empty';
 const input=(name,label,help='',extra='')=>`<label class="tp-field"><span>${label}</span><input name="${name}" inputmode="decimal" autocomplete="off" type="text" placeholder="Enter amount" ${extra}>${help?`<small>${help}</small>`:''}</label>`;
 container.innerHTML=`<div class="tp-toolbar"><label class="tp-field"><span>Coin</span><select name="baseAsset"><option value="">Choose a coin</option>${coinOptions.map(([symbol,name])=>`<option value="${symbol}">${name} · ${symbol}</option>`).join('')}<option value="CUSTOM">Other coin</option></select></label><label class="tp-field" data-custom hidden><span>Coin ticker</span><input name="customAsset" maxlength="15" autocomplete="off" placeholder="e.g. ticker"></label><label class="tp-field"><span>Price currency</span><select name="quoteCurrency">${['USDT','USD','USDC','AUD'].map(c=>`<option value="${c}">${c}</option>`).join('')}</select></label><button class="button" type="button" data-load-market>Refresh chart</button></div>
 <p class="tp-toolbar-note">Public prices only. Selecting a coin loads a public market snapshot. USDT/USDC references use Binance; other quotes support daily OKX references when available. USD, USDT, USDC and AUD are different currencies; no FX conversion is applied.</p>
 <div class="tp-layout"><div class="glass tp-chart-panel"><div class="tp-chart-heading"><div><p class="eyebrow">YOUR PLAN, IN CONTEXT</p><h2 data-pair>Choose a coin</h2><p data-reference>4H candles · snapshot, not streaming</p></div><span class="small-badge">PROPOSED LEVELS</span></div><div class="tp-chart-tools"><div class="tp-intervals" role="group" aria-label="Candle timeframe"><button type="button" data-interval="1h" aria-pressed="false">1H</button><button type="button" data-interval="4h" aria-pressed="true">4H</button><button type="button" data-interval="1d" aria-pressed="false">1D</button></div><button class="tp-chart-control" type="button" data-reset-chart>Reset view</button></div><p class="tp-market-message" data-market-message role="status"></p><p class="tp-readout" data-chart-readout aria-live="off">Hover or touch a candle to inspect its prices and volume</p><div class="tp-chart-stage"><div class="tp-chart" data-chart></div><p class="tp-chart-fallback" data-chart-fallback>Choose a coin to load real candles</p></div><label class="tp-edit-mode"><span>Chart mode</span><select data-edit-level aria-label="Chart interaction mode"><option value="">Explore · pan and zoom</option><option value="entry">Edit draft buy limit</option><option value="stop">Edit draft stop trigger</option><option value="target">Edit draft take profit</option><option value="trailingActivation">Edit draft trail activation</option></select></label><div class="tp-level-key"><span class="tp-entry">— Buy limit</span><span class="tp-stop">— Stop trigger</span><span class="tp-target" data-exit-key>— Take profit</span></div><p class="fine-print">Choose an edit mode to drag one draft level. Otherwise pan, pinch or scroll to explore. Numeric price inputs always remain available. Keyboard in edit mode: ↑ or ↓. These are draft levels, never active orders.</p><p class="chart-attribution"><a href="https://www.tradingview.com/" target="_blank" rel="noopener noreferrer">TradingView Lightweight Charts™</a> · Copyright (с) 2025 TradingView, Inc.</p><div class="tp-checkpoint"><strong>Built for an evening decision</strong><p>After 6 pm: review the price date, your spend and your exits. Breakfast or lunch: check actual orders in OKX if needed.</p></div><details class="tp-market-details"><summary>Market source &amp; dates</summary><div data-market-details>No market data loaded. The chart will not invent past prices.</div><a data-market-documentation href="${MARKET_DOCUMENTATION}" target="_blank" rel="noopener noreferrer">Public market documentation</a></details><details class="tp-candle-data"><summary>Recent candle values</summary><div class="tp-data-table" data-candle-table>No candle data loaded</div></details></div>
 <form class="glass tp-form" novalidate><div class="tp-form-heading"><h2>Build the draft</h2><span class="tp-spot">SPOT BUY</span></div><div class="tp-currency-note" data-currency-note>Amounts in USDT</div><div class="tp-fields">${input('budget','Buy amount','Includes the entry-fee assumption')}${input('entry','Limit-entry price','Maximum planned buy price per coin')}${input('stop','Stop-loss trigger','Below entry; execution may be worse')}${input('target','Take-profit price','Above entry; scenario only')}</div><fieldset class="tp-exit-choice"><legend>Exit plan</legend><label><input type="radio" name="exitMode" value="fixed" checked> Fixed take profit</label><label><input type="radio" name="exitMode" value="trailing"> Trail after a run</label></fieldset><div class="tp-fields" data-trailing hidden>${input('trailingActivation','Trail activation price','At or above entry')}${input('trailingCallbackPercent','Trailing distance · %','Below the best price after activation')}</div><p class="tp-exit-note" data-exit-note>Fixed target for the full planned quantity. Confirm available paired stop/target order types in OKX.</p><details class="tp-costs" open><summary>Costs &amp; risk assumptions</summary><p>No exchange fee rate is assumed. Enter your actual fee tier or a deliberate estimate, including zero if that is your assumption.</p><div class="tp-fields">${input('entryFeePercent','Entry fee · %')}${input('exitFeePercent','Exit fee · %')}${input('slippagePercent','Exit slippage · %','Assumed adverse price movement')}${input('riskBudget','Loss budget · optional','A warning threshold, not protection')}</div></details><div data-validation class="tp-validation" role="status"></div><div class="tp-metrics" data-metrics></div><button type="button" class="button primary tp-review" data-review disabled>Review draft ticket</button><p class="tp-execution-warning">A stop can slip or fail to fill. Loss can exceed this estimate. Fees, lot size and supported exits must be checked in OKX.</p></form></div>
 <section class="glass tp-ticket" data-ticket hidden aria-labelledby="tradeTicketTitle"><div class="panel-heading"><div><p class="eyebrow">MANUAL REVIEW</p><h2 id="tradeTicketTitle">Draft ticket</h2></div><button class="button" type="button" data-close-ticket>Close</button></div><p>Nothing has been sent. Review and enter the order yourself in OKX. Only the exchange can confirm an order or exit is active.</p><textarea readonly data-ticket-text aria-label="Draft spot trade ticket"></textarea><div class="tp-ticket-actions"><a class="button" href="https://www.okx.com/" target="_blank" rel="noopener noreferrer">Open OKX ↗</a><button type="button" class="button" data-select-ticket>Select ticket text</button></div><p class="fine-print">This draft is held in this page only. It clears on sign-out, account reload or page exit.</p></section>`;
 const q=s=>container.querySelector(s),field=name=>q(`[name="${name}"]`);
 function read(){const value=Object.fromEntries(fields.map(name=>[name,field(name).value.trim()]));if(value.baseAsset==='CUSTOM')value.baseAsset=field('customAsset').value.trim().toUpperCase();const trailing=q('[name="exitMode"][value="trailing"]').checked;if(trailing)value.target='';else{value.trailingActivation='';value.trailingCallbackPercent='';}return value;}
 function pairChanged(){chartView?.clear();q('[data-edit-level]').value='';++request;controller?.abort();loading=false;market=null;marketMessage='';for(const name of ['entry','stop','target','budget','riskBudget','trailingActivation'])field(name).value='';q('[data-custom]').hidden=field('baseAsset').value!=='CUSTOM';ticketOpen=false;q('[data-ticket]').hidden=true;q('[data-ticket-text]').value='';update();}
 function inspectCandle(candle){q('[data-chart-readout]').textContent=candle?`${stamp(candle.time)} · O ${fmt(candle.open)} · H ${fmt(candle.high)} · L ${fmt(candle.low)} · C ${fmt(candle.close)} · Volume ${fmt(candle.volume)} ${read().baseAsset}${candle.isForming?' · Forming candle':''}`:'Hover or touch a candle to inspect its prices and volume';}
 function chart(input){
  const active=levels.filter(l=>number(input[l.field])>0).map(l=>({...l,value:number(input[l.field])}));
  chartView?.setLevels(active);
  const mode=q('[data-edit-level]');for(const option of mode.querySelectorAll('option'))if(option.value)option.disabled=!active.some(l=>l.field===option.value)||!market;
  if(mode.value&&!active.some(l=>l.field===mode.value)){mode.value='';chartView?.setEditField(null);}
  const fallback=q('[data-chart-fallback]');fallback.hidden=chartStatus==='ready';fallback.textContent=chartStatus==='loading'?'Preparing interactive chart…':market?'The interactive chart could not load. Market data and numeric draft controls remain available below.':loading?'Loading real candles…':'Choose a coin to load real candles. No market history is invented.';
 }
 function update(){
  if(market)market.stale=Date.now()-market.retrievedAt>15*60000||Date.now()-market.latest.closeAt>2*(market.candleDurationMs||86400000);
  const input=read(),result=calculateTradePlan(input),trailing=q('[name="exitMode"][value="trailing"]').checked,currency=input.quoteCurrency;
  field('target').closest('label').hidden=trailing;q('[data-trailing]').hidden=!trailing;q('[data-exit-key]').textContent=trailing?'— Trail activation':'— Take profit';q('[data-exit-key]').className=trailing?'tp-trail':'tp-target';
  q('[data-exit-note]').textContent=trailing?'Trailing is an alternative to a fixed target for the full planned quantity. It is not an extra full-size exit. Confirm how it interacts with your stop in OKX.':'Fixed target for the full planned quantity. Confirm available paired stop/target order types in OKX.';
  q('[data-pair]').textContent=input.baseAsset?input.baseAsset+' / '+currency:'Choose a coin';q('[data-currency-note]').textContent='Spend, prices and loss budget in '+currency+' · no FX conversion';
  q('[data-load-market]').disabled=loading||!input.baseAsset;q('[data-load-market]').textContent=loading?'Loading candles…':'Refresh chart';q('[data-market-message]').textContent=marketMessage;
  q('[data-reference]').textContent=market?`${market.venue||'Public reference'} · ${interval.toUpperCase()} · Latest bar close ${fmt(market.latest.close)} ${currency}${market.latest.isForming?' · Forming candle':' · Completed candle'}${market.stale?' · Stale reference':''}`:`${interval.toUpperCase()} candles · snapshot, not streaming`;
  q('[data-market-details]').textContent=market?`${market.venue||'Public reference'} · ${market.pair}. ${market.candles.length} ${interval.toUpperCase()} UTC candles. Retrieved ${stamp(market.retrievedAt)}. ${market.latest.isForming?'The final candle is still forming. ':''}Chart time axis is UTC. Missing bars are not filled. Snapshot only; refresh before deciding. This is not a live executable quote. ${market.venue==='Binance'?'Binance is a separate venue; OKX prices and fills can differ.':''}`:'No market data loaded. The chart will not invent past prices.';
  q('[data-candle-table]').innerHTML=market?`<table><caption>${esc(market.pair)} · ${interval.toUpperCase()} · ${esc(market.venue)} · latest 12 candles</caption><thead><tr><th>Bar opens</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume (${esc(input.baseAsset)})</th><th>Status</th></tr></thead><tbody>${market.candles.slice(-12).map(c=>`<tr><td>${esc(stamp(c.time))}</td>${[c.open,c.high,c.low,c.close,c.volume].map(v=>`<td>${esc(fmt(v))}</td>`).join('')}<td>${c.isForming?'Forming':'Completed'}</td></tr>`).join('')}</tbody></table>`:'No candle data loaded';
  q('[data-market-documentation]').href=market?.documentation||MARKET_DOCUMENTATION;
  q('[data-market-documentation]').textContent=(market?.venue||'OKX')+' public market documentation';
  const extraErrors=[];if(trailing&&(!input.trailingActivation||!input.trailingCallbackPercent))extraErrors.push('Enter both trailing activation and distance.');if(!trailing&&!input.target)extraErrors.push('Enter a take-profit price for the fixed-target draft.');
  const complete=result.valid&&!extraErrors.length;
  const names={baseAsset:'Coin',budget:'Buy amount',entry:'Entry price',stop:'Stop loss',target:'Take profit',entryFeePercent:'Entry fee',exitFeePercent:'Exit fee',slippagePercent:'Slippage',riskBudget:'Loss budget',trailingActivation:'Trail activation',trailingCallbackPercent:'Trailing distance'};
  const errors=Array.isArray(result.errors)?result.errors:Object.entries(result.errors||{}).map(([key,message])=>(names[key]||key)+': '+message);
  q('[data-validation]').innerHTML=complete?`<strong>${result.plan.riskExceeded?'Review your loss budget':'Draft ready for your review'}</strong><p>${result.plan.riskExceeded?'The estimated stop scenario exceeds your loss budget.':'Check the chart, assumptions and exchange order rules before using it.'}</p>`:`<strong>Draft incomplete</strong><p>${esc([...errors,...extraErrors].slice(0,3).join(' '))}</p>`;
  for(const name of fields){const error=!Array.isArray(result.errors)&&result.errors?.[name];if(error)field(name).setAttribute('aria-invalid','true');else field(name).removeAttribute('aria-invalid');}
  const p=result.plan,metric=(label,value,kind='')=>`<div class="${kind}"><span>${label}</span><strong>${value}</strong></div>`;
  q('[data-metrics]').innerHTML=p?metric('Planned quantity',esc(fmt(p.quantity))+' '+esc(input.baseAsset))+metric('Stop scenario · estimated loss',esc(fmt(p.stopLoss))+' '+currency,'tp-loss')+metric('Entry fee / stop-exit fee',esc(fmt(p.entryFee))+' / '+esc(fmt(p.stopExitFee))+' '+currency)+metric(trailing?'Trail starts below activation':'Target scenario · net gain',trailing?esc(fmt(p.trailingInitialTrigger))+' '+currency:p.targetGain==null?'—':esc(fmt(p.targetGain))+' '+currency,'tp-gain')+metric('Stop distance',esc(fmt(p.stopDistancePercent))+'%')+metric('Net reward / estimated risk',p.rewardRisk==null?'—':esc(fmt(p.rewardRisk))+'×'):metric('Stop scenario · estimated loss','—','tp-loss')+metric('Target scenario · net gain','—','tp-gain');
  q('[data-review]').disabled=!complete;
  chart(input);
  if(ticketOpen){if(!complete){ticketOpen=false;q('[data-ticket]').hidden=true;q('[data-ticket-text]').value='';}else writeTicket(input,result);}
  onRender();return {input,result,complete};
 }
 function writeTicket(input,result){q('[data-ticket-text]').value=formatDraftTicket(input,result)+'\n\nExit mode: '+(q('[name="exitMode"][value="trailing"]').checked?'Trailing alternative for the full planned quantity, no fixed target. Confirm interaction with the protective stop in OKX.':'Fixed target for the full planned quantity. Confirm supported paired stop/target order types in OKX.')+'\nMarket reference: '+(market?(market.venue||'Public reference')+' '+market.pair+' '+interval.toUpperCase()+' bar close '+fmt(market.latest.close)+(market.latest.isForming?' (forming candle)':' (completed candle)')+'; bar opens '+stamp(market.latest.time)+'; retrieved '+stamp(market.retrievedAt)+(market.stale?' · STALE, recheck in OKX':''):'Not loaded. Recheck the current exchange quote before placing any order.')+'\nNo FX conversion. Market-reference venue may differ from OKX; verify the current OKX quote. This draft is not an active order.';}
 async function loadMarket(){if(loading)return;q('[data-edit-level]').value='';chartView?.setEditField(null);const input=read(),id=++request;controller?.abort();controller=new AbortController();const activeController=controller,timeout=setTimeout(()=>activeController.abort(),12000);loading=true;marketMessage='Reading public candles and volume. No portfolio or draft amounts are sent.';update();try{const loaded=await fetchMarket({baseAsset:input.baseAsset,quoteCurrency:input.quoteCurrency,interval,limit:300,includeForming:true,signal:controller.signal});if(id!==request)return;market=loaded;chartView?.setMarket(market);marketMessage=market.stale?'Prices loaded, but this reference is stale. Check current prices in OKX before deciding.':`${market.venue||'Public reference'} candles loaded. ${market.venue==='Binance'?'This is a reference from a separate venue, not an OKX execution quote. ':''}Your proposed levels are unchanged.`;}catch{if(id!==request)return;marketMessage=(['USD','AUD'].includes(input.quoteCurrency)&&interval!=='1d'?'Choose 1D to try this quote currency. ':'')+'Public prices are unavailable for this pair here. You can still sketch levels; check the market in OKX. No price history has been invented.';}finally{clearTimeout(timeout);if(id===request){loading=false;update();}}}
 container.addEventListener('submit',event=>event.preventDefault());
 container.addEventListener('input',event=>{if(event.target.name==='customAsset'){pairChanged();return;}if(event.target.matches('input'))update();});
 container.addEventListener('change',event=>{if(['baseAsset','quoteCurrency'].includes(event.target.name)){pairChanged();if(read().baseAsset&&field('baseAsset').value!=='CUSTOM')void loadMarket();}else if(event.target.matches('[data-edit-level]')){chartView?.setEditField(event.target.value);}else if(event.target.name==='customAsset'){if(read().baseAsset)void loadMarket();}else{if(event.target.name==='exitMode'){q('[data-edit-level]').value='';chartView?.setEditField(null);}update();}});
 container.addEventListener('click',event=>{const timeframe=event.target.closest('[data-interval]');if(timeframe&&timeframe.dataset.interval!==interval){interval=timeframe.dataset.interval;++request;controller?.abort();loading=false;market=null;marketMessage='';chartView?.clear();q('[data-edit-level]').value='';for(const button of container.querySelectorAll('[data-interval]'))button.setAttribute('aria-pressed',String(button.dataset.interval===interval));update();if(read().baseAsset)void loadMarket();}if(event.target.closest('[data-reset-chart]'))chartView?.reset();if(event.target.closest('[data-load-market]'))void loadMarket();if(event.target.closest('[data-review]')){const state=update();if(!state.complete)return;ticketOpen=true;writeTicket(state.input,state.result);q('[data-ticket]').hidden=false;q('[data-ticket-text]').focus();}if(event.target.closest('[data-close-ticket]')){ticketOpen=false;q('[data-ticket]').hidden=true;q('[data-review]').focus();}if(event.target.closest('[data-select-ticket]')){q('[data-ticket-text]').focus();q('[data-ticket-text]').select();}});
 chartView=chartFactory({container:q('[data-chart]'),onInspect:inspectCandle,onLevelChange:(name,value)=>{field(name).value=value;update();},onStatus:status=>{chartStatus=status;chart(read());}});
 window.addEventListener('resize',()=>chartView?.resize());
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)update();});
 update();return {refresh:update,clear(){++request;controller?.abort();market=null;loading=false;marketMessage='';ticketOpen=false;chartView?.clear();q('[data-edit-level]').value='';for(const name of fields)if(name!=='quoteCurrency')field(name).value='';field('customAsset').value='';q('[data-custom]').hidden=true;field('quoteCurrency').value='USDT';q('[name="exitMode"][value="fixed"]').checked=true;q('[name="exitMode"][value="trailing"]').checked=false;q('[data-ticket]').hidden=true;q('[data-ticket-text]').value='';update();}};
}
