import {calculateTradePlan,formatDraftTicket} from './trade-plan.mjs?v=20261003.desk1';
import {readMarketReference,MARKET_DOCUMENTATION} from './market-reference.mjs?v=20261003.pepe1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>v!==''&&v!=null&&Number.isFinite(Number(v))?Number(v):null;
const fmt=v=>v==null?'—':new Intl.NumberFormat('en-AU',{maximumSignificantDigits:9}).format(v);
const stamp=v=>new Date(v).toLocaleString('en-AU',{dateStyle:'medium',timeStyle:'short'});
const coinOptions=[['BTC','Bitcoin'],['ETH','Ethereum'],['SOL','Solana'],['XRP','XRP'],['HBAR','Hedera'],['PEPE','Pepe'],['DOGE','Dogecoin'],['LINK','Chainlink'],['SUI','Sui']];
const fields=['baseAsset','quoteCurrency','budget','entry','stop','target','entryFeePercent','exitFeePercent','slippagePercent','riskBudget','trailingActivation','trailingCallbackPercent'];
const levels=[{field:'entry',label:'Buy limit',color:'#92dacf'},{field:'stop',label:'Stop trigger',color:'#ffa4aa'},{field:'target',label:'Take profit',color:'#c5b5ff'},{field:'trailingActivation',label:'Trail activation',color:'#e9c283'}];
export function createTradePlanner({container,onRender=()=>{},fetchMarket=readMarketReference}={}){
 let market=null,loading=false,marketMessage='',controller=null,request=0,drag=null,ticketOpen=false;
 const input=(name,label,help='',extra='')=>`<label class="tp-field"><span>${label}</span><input name="${name}" inputmode="decimal" autocomplete="off" type="text" placeholder="Enter amount" ${extra}>${help?`<small>${help}</small>`:''}</label>`;
 container.innerHTML=`<div class="tp-toolbar"><label class="tp-field"><span>Coin</span><select name="baseAsset"><option value="">Choose a coin</option>${coinOptions.map(([symbol,name])=>`<option value="${symbol}">${name} · ${symbol}</option>`).join('')}<option value="CUSTOM">Other coin</option></select></label><label class="tp-field" data-custom hidden><span>Coin ticker</span><input name="customAsset" maxlength="15" autocomplete="off" placeholder="e.g. ticker"></label><label class="tp-field"><span>Price currency</span><select name="quoteCurrency">${['USDT','USD','USDC','AUD'].map(c=>`<option value="${c}">${c}</option>`).join('')}</select></label><button class="button" type="button" data-load-market>Load daily prices</button></div>
 <p class="tp-toolbar-note">Public prices only. Selecting a coin loads public daily prices. USDT/USDC references use Binance; other quotes use OKX. USD, USDT, USDC and AUD are different currencies; no FX conversion is applied.</p>
 <div class="tp-layout"><div class="glass tp-chart-panel"><div class="tp-chart-heading"><div><p class="eyebrow">YOUR PLAN, IN CONTEXT</p><h2 data-pair>Choose a coin</h2><p data-reference>Daily closing prices · not streaming</p></div><span class="small-badge">PROPOSED LEVELS</span></div><div class="tp-market-message" data-market-message role="status"></div><div class="tp-chart" data-chart></div><div class="tp-level-key"><span class="tp-entry">— Buy limit</span><span class="tp-stop">— Stop trigger</span><span class="tp-target" data-exit-key>— Take profit</span></div><p class="fine-print">Drag a labelled line or change its price in the form. Keyboard: focus a line, then use ↑ or ↓. These are draft levels, never active orders.</p><div class="tp-checkpoint"><strong>Built for an evening decision</strong><p>After 6 pm: review the price date, your spend and your exits. Breakfast or lunch: check actual orders in OKX if needed.</p></div><details class="tp-market-details"><summary>Market source &amp; dates</summary><div data-market-details>No market data loaded. The chart will not invent past prices.</div><a data-market-documentation href="${MARKET_DOCUMENTATION}" target="_blank" rel="noopener noreferrer">Public market documentation</a></details></div>
 <form class="glass tp-form" novalidate><div class="tp-form-heading"><h2>Build the draft</h2><span class="tp-spot">SPOT BUY</span></div><div class="tp-currency-note" data-currency-note>Amounts in USDT</div><div class="tp-fields">${input('budget','Buy amount','Includes the entry-fee assumption')}${input('entry','Limit-entry price','Maximum planned buy price per coin')}${input('stop','Stop-loss trigger','Below entry; execution may be worse')}${input('target','Take-profit price','Above entry; scenario only')}</div><fieldset class="tp-exit-choice"><legend>Exit plan</legend><label><input type="radio" name="exitMode" value="fixed" checked> Fixed take profit</label><label><input type="radio" name="exitMode" value="trailing"> Trail after a run</label></fieldset><div class="tp-fields" data-trailing hidden>${input('trailingActivation','Trail activation price','At or above entry')}${input('trailingCallbackPercent','Trailing distance · %','Below the best price after activation')}</div><p class="tp-exit-note" data-exit-note>Fixed target for the full planned quantity. Confirm available paired stop/target order types in OKX.</p><details class="tp-costs" open><summary>Costs &amp; risk assumptions</summary><p>No exchange fee rate is assumed. Enter your actual fee tier or a deliberate estimate, including zero if that is your assumption.</p><div class="tp-fields">${input('entryFeePercent','Entry fee · %')}${input('exitFeePercent','Exit fee · %')}${input('slippagePercent','Exit slippage · %','Assumed adverse price movement')}${input('riskBudget','Loss budget · optional','A warning threshold, not protection')}</div></details><div data-validation class="tp-validation" role="status"></div><div class="tp-metrics" data-metrics></div><button type="button" class="button primary tp-review" data-review disabled>Review draft ticket</button><p class="tp-execution-warning">A stop can slip or fail to fill. Loss can exceed this estimate. Fees, lot size and supported exits must be checked in OKX.</p></form></div>
 <section class="glass tp-ticket" data-ticket hidden aria-labelledby="tradeTicketTitle"><div class="panel-heading"><div><p class="eyebrow">MANUAL REVIEW</p><h2 id="tradeTicketTitle">Draft ticket</h2></div><button class="button" type="button" data-close-ticket>Close</button></div><p>Nothing has been sent. Review and enter the order yourself in OKX. Only the exchange can confirm an order or exit is active.</p><textarea readonly data-ticket-text aria-label="Draft spot trade ticket"></textarea><div class="tp-ticket-actions"><a class="button" href="https://www.okx.com/" target="_blank" rel="noopener noreferrer">Open OKX ↗</a><button type="button" class="button" data-select-ticket>Select ticket text</button></div><p class="fine-print">This draft is held in this page only. It clears on sign-out, account reload or page exit.</p></section>`;
 const q=s=>container.querySelector(s),field=name=>q(`[name="${name}"]`);
 function read(){const value=Object.fromEntries(fields.map(name=>[name,field(name).value.trim()]));if(value.baseAsset==='CUSTOM')value.baseAsset=field('customAsset').value.trim().toUpperCase();const trailing=q('[name="exitMode"][value="trailing"]').checked;if(trailing)value.target='';else{value.trailingActivation='';value.trailingCallbackPercent='';}return value;}
 function pairChanged(){drag=null;++request;controller?.abort();loading=false;market=null;marketMessage='';for(const name of ['entry','stop','target','budget','riskBudget','trailingActivation'])field(name).value='';q('[data-custom]').hidden=field('baseAsset').value!=='CUSTOM';ticketOpen=false;q('[data-ticket]').hidden=true;q('[data-ticket-text]').value='';update();}
 function chart(input){
  const active=levels.filter(l=>number(input[l.field])>0),candles=market?.candles||[],values=[...active.map(l=>number(input[l.field])),...candles.map(c=>c.close)];
  const width=Math.max(340,Math.min(900,q('[data-chart]').clientWidth||900)),height=390,left=16,right=width-186,top=24,bottom=355;
  if(!values.length){q('[data-chart]').innerHTML='<div class="tp-chart-empty"><strong>Give your plan a shape</strong><span>Choose a coin and load daily prices, or enter your own proposed levels. No invented market line.</span></div>';return;}
  let min=Math.min(...values),max=Math.max(...values);const span=max-min||max*.1||1;min=Math.max(0,min-span*.12);max+=span*.12;if(drag){min=drag.scale.min;max=drag.scale.max;}if(!Number.isFinite(min)||!Number.isFinite(max)||max<=min){q('[data-chart]').innerHTML='<div class="tp-chart-empty"><strong>Check your price range</strong><span>These levels cannot be shown reliably. Adjust the numeric inputs.</span></div>';return;}const y=p=>bottom-(p-min)/(max-min)*(bottom-top);
  const first=candles[0]?.closeAt,last=candles.at(-1)?.closeAt,x=time=>first===last?(left+right)/2:left+(time-first)/(last-first)*(right-left);
  let svg=`<svg viewBox="0 0 ${width} ${height}" role="group" aria-label="${esc(input.baseAsset||'Coin')} draft price levels in ${esc(input.quoteCurrency)}${candles.length?', with verified completed daily close prices':'. No market history loaded'}"><path class="tp-grid" d="M${left} 24H${right}M${left} 134H${right}M${left} 245H${right}M${left} 355H${right}"/>`;
  const entry=number(input.entry),stop=number(input.stop),target=number(input.target);
  if(entry>0&&stop>0&&stop<entry)svg+=`<rect x="${left}" y="${y(entry)}" width="${right-left}" height="${y(stop)-y(entry)}" fill="#ff8c9810"/>`;
  if(entry>0&&target>entry)svg+=`<rect x="${left}" y="${y(target)}" width="${right-left}" height="${y(entry)-y(target)}" fill="#b4a1f712"/>`;
  if(candles.length){let path='';for(let i=0;i<candles.length;i++){const c=candles[i],previous=candles[i-1];path+=`${!previous||c.closeAt-previous.closeAt>86400000?'M':'L'}${x(c.closeAt)},${y(c.close)} `;}svg+=`<path class="tp-market-line" d="${path}"/>`;svg+=`<circle cx="${x(last)}" cy="${y(candles.at(-1).close)}" r="4" fill="#edf6f4"/>`;}
  // Labels stay readable when nearby levels overlap; leaders point to their exact prices.
  const labelOrder=active.map(l=>({...l,value:number(input[l.field]),actual:y(number(input[l.field]))})).sort((a,b)=>a.actual-b.actual);let previous=-30;for(const l of labelOrder){l.labelY=Math.max(l.actual,previous+48);previous=l.labelY;}const excess=Math.max(0,(labelOrder.at(-1)?.labelY||0)-bottom);for(const l of labelOrder)l.labelY-=excess;
  for(const l of labelOrder){svg+=`<path d="M${left} ${l.actual}H${right}L${right+12} ${l.labelY}H${width-10}" fill="none" stroke="${l.color}" stroke-width="1.8" stroke-dasharray="7 5"/><g data-drag-level="${l.field}" tabindex="0" role="button" aria-label="Adjust ${esc(l.label)}, ${esc(fmt(l.value))} ${esc(input.quoteCurrency)}; use up or down arrows"><rect x="${right+10}" y="${l.labelY-20}" width="166" height="40" rx="9" fill="#0d2029" stroke="${l.color}"/><text x="${right+21}" y="${l.labelY-3}" fill="${l.color}" font-size="12">${l.label}</text><text x="${right+21}" y="${l.labelY+13}" fill="#f0f5f5" font-size="14">${esc(fmt(l.value))}</text></g>`;}
  svg+=`<text x="20" y="382" class="tp-axis">${candles.length?esc(new Date(first).toLocaleDateString('en-AU')):'Proposed price levels'}</text><text x="${right}" y="382" text-anchor="end" class="tp-axis">${candles.length?esc(new Date(last).toLocaleDateString('en-AU')):'No market history'}</text></svg>`;
  q('[data-chart]').innerHTML=svg;q('[data-chart]')._scale={min,max,top,bottom,height};
 }
 function update(){
  if(market)market.stale=Date.now()-market.latest.closeAt>2*86400000;
  const input=read(),result=calculateTradePlan(input),trailing=q('[name="exitMode"][value="trailing"]').checked,currency=input.quoteCurrency;
  field('target').closest('label').hidden=trailing;q('[data-trailing]').hidden=!trailing;q('[data-exit-key]').textContent=trailing?'— Trail activation':'— Take profit';q('[data-exit-key]').className=trailing?'tp-trail':'tp-target';
  q('[data-exit-note]').textContent=trailing?'Trailing is an alternative to a fixed target for the full planned quantity. It is not an extra full-size exit. Confirm how it interacts with your stop in OKX.':'Fixed target for the full planned quantity. Confirm available paired stop/target order types in OKX.';
  q('[data-pair]').textContent=input.baseAsset?input.baseAsset+' / '+currency:'Choose a coin';q('[data-currency-note]').textContent='Spend, prices and loss budget in '+currency+' · no FX conversion';
  q('[data-load-market]').disabled=loading||!input.baseAsset;q('[data-load-market]').textContent=loading?'Loading daily prices…':'Load daily prices';q('[data-market-message]').textContent=marketMessage;
  q('[data-reference]').textContent=market?`${market.venue||'Public reference'} · Latest daily close ${fmt(market.latest.close)} ${currency} · ${stamp(market.latest.closeAt)}${market.stale?' · Stale reference':''}`:'Daily closing prices · not streaming';
  q('[data-market-details]').textContent=market?`${market.venue||'Public reference'} · ${market.pair}. ${market.candles.length} completed UTC-day observations. Retrieved ${stamp(market.retrievedAt)}. Missing days are not filled. The latest daily close is not a live executable quote. ${market.venue==='Binance'?'Binance is a separate venue; OKX prices and fills can differ.':''}`:'No market data loaded. The chart will not invent past prices.';
  q('[data-market-documentation]').href=market?.documentation||MARKET_DOCUMENTATION;
  q('[data-market-documentation]').textContent=(market?.venue||'OKX')+' public market documentation';
  const extraErrors=[];if(trailing&&(!input.trailingActivation||!input.trailingCallbackPercent))extraErrors.push('Enter both trailing activation and distance.');if(!trailing&&!input.target)extraErrors.push('Enter a take-profit price for the fixed-target draft.');
  const complete=result.valid&&!extraErrors.length;
  const names={baseAsset:'Coin',budget:'Buy amount',entry:'Entry price',stop:'Stop loss',target:'Take profit',entryFeePercent:'Entry fee',exitFeePercent:'Exit fee',slippagePercent:'Slippage',riskBudget:'Loss budget',trailingActivation:'Trail activation',trailingCallbackPercent:'Trailing distance'};
  const errors=Array.isArray(result.errors)?result.errors:Object.entries(result.errors||{}).map(([key,message])=>(names[key]||key)+': '+message);
  q('[data-validation]').innerHTML=complete?`<strong>${result.plan.riskExceeded?'Review your loss budget':'Draft ready for your review'}</strong><p>${result.plan.riskExceeded?'The estimated stop scenario exceeds your loss budget.':'Check the chart, assumptions and exchange order rules before using it.'}</p>`:`<strong>Draft incomplete</strong><p>${esc([...errors,...extraErrors].slice(0,3).join(' '))}</p>`;
  for(const name of fields){const error=!Array.isArray(result.errors)&&result.errors?.[name];if(error)field(name).setAttribute('aria-invalid','true');else field(name).removeAttribute('aria-invalid');}
  const p=result.plan,metric=(label,value,kind='')=>`<div class="${kind}"><span>${label}</span><strong>${value}</strong></div>`;
  q('[data-metrics]').innerHTML=p?metric('Planned quantity',esc(fmt(p.quantity))+' '+esc(input.baseAsset))+metric('Stop scenario · estimated loss',esc(fmt(p.stopLoss))+' '+currency,'tp-loss')+metric('Entry fee / stop-exit fee',esc(fmt(p.entryFee))+' / '+esc(fmt(p.stopExitFee))+' '+currency)+metric(trailing?'Trail starts below activation':'Target scenario · net gain',trailing?esc(fmt(p.trailingInitialTrigger))+' '+currency:p.targetGain==null?'—':esc(fmt(p.targetGain))+' '+currency,'tp-gain')+metric('Stop distance',esc(fmt(p.stopDistancePercent))+'%')+metric('Net reward / estimated risk',p.rewardRisk==null?'—':esc(fmt(p.rewardRisk))+'×'):metric('Stop scenario · estimated loss','—','tp-loss')+metric('Target scenario · net gain','—','tp-gain');
  q('[data-review]').disabled=!complete;
  chart(input);
  if(ticketOpen){if(!complete){ticketOpen=false;q('[data-ticket]').hidden=true;q('[data-ticket-text]').value='';}else writeTicket(input,result);}
  onRender();return {input,result,complete};
 }
 function writeTicket(input,result){q('[data-ticket-text]').value=formatDraftTicket(input,result)+'\n\nExit mode: '+(q('[name="exitMode"][value="trailing"]').checked?'Trailing alternative for the full planned quantity, no fixed target. Confirm interaction with the protective stop in OKX.':'Fixed target for the full planned quantity. Confirm supported paired stop/target order types in OKX.')+'\nMarket reference: '+(market?(market.venue||'Public reference')+' '+market.pair+' daily close '+fmt(market.latest.close)+' at '+stamp(market.latest.closeAt)+'; retrieved '+stamp(market.retrievedAt)+(market.stale?' · STALE, recheck in OKX':''):'Not loaded. Recheck the current exchange quote before placing any order.')+'\nNo FX conversion. Market-reference venue may differ from OKX; verify the current OKX quote. This draft is not an active order.';}
 async function loadMarket(){if(loading)return;const input=read(),id=++request;controller?.abort();controller=new AbortController();const activeController=controller,timeout=setTimeout(()=>activeController.abort(),12000);loading=true;marketMessage='Reading public daily prices. No portfolio or draft amounts are sent.';update();try{const loaded=await fetchMarket({baseAsset:input.baseAsset,quoteCurrency:input.quoteCurrency,signal:controller.signal});if(id!==request)return;market=loaded;marketMessage=market.stale?'Prices loaded, but this reference is stale. Check current prices in OKX before deciding.':`${market.venue||'Public reference'} daily prices loaded. ${market.venue==='Binance'?'This is a reference from a separate venue, not an OKX execution quote. ':''}Your proposed levels are unchanged.`;}catch{if(id!==request)return;marketMessage='Public prices are unavailable for this pair here. You can still sketch levels; check the market in OKX. No price history has been invented.';}finally{clearTimeout(timeout);if(id===request){loading=false;update();}}}
 container.addEventListener('submit',event=>event.preventDefault());
 container.addEventListener('input',event=>{if(event.target.name==='customAsset'){pairChanged();return;}if(event.target.matches('input'))update();});
 container.addEventListener('change',event=>{if(['baseAsset','quoteCurrency'].includes(event.target.name)){pairChanged();if(read().baseAsset&&field('baseAsset').value!=='CUSTOM')void loadMarket();}else if(event.target.name==='customAsset'){if(read().baseAsset)void loadMarket();}else{if(event.target.name==='exitMode')drag=null;update();}});
 container.addEventListener('click',event=>{if(event.target.closest('[data-load-market]'))void loadMarket();if(event.target.closest('[data-review]')){const state=update();if(!state.complete)return;ticketOpen=true;writeTicket(state.input,state.result);q('[data-ticket]').hidden=false;q('[data-ticket-text]').focus();}if(event.target.closest('[data-close-ticket]')){ticketOpen=false;q('[data-ticket]').hidden=true;q('[data-review]').focus();}if(event.target.closest('[data-select-ticket]')){q('[data-ticket-text]').focus();q('[data-ticket-text]').select();}});
 const chartElement=q('[data-chart]');
 function pointerY(event,matrix){const point=document.createElementNS('http://www.w3.org/2000/svg','svg').createSVGPoint();point.x=event.clientX;point.y=event.clientY;return point.matrixTransform(matrix).y;}
 chartElement.addEventListener('pointerdown',event=>{const handle=event.target.closest('[data-drag-level]');if(!handle)return;const svg=chartElement.querySelector('svg'),matrix=svg.getScreenCTM?.()?.inverse();if(!matrix)return;event.preventDefault();drag={field:handle.dataset.dragLevel,scale:chartElement._scale,matrix,startY:pointerY(event,matrix),startClientY:event.clientY,price:Number(field(handle.dataset.dragLevel).value),moved:false};chartElement.setPointerCapture?.(event.pointerId);});
 function move(event){if(!drag||Math.abs(event.clientY-drag.startClientY)<2&&!drag.moved)return;const {scale}=drag,y=pointerY(event,drag.matrix),value=Math.max(Number.MIN_VALUE,drag.price-(y-drag.startY)/(scale.bottom-scale.top)*(scale.max-scale.min));drag.moved=true;field(drag.field).value=String(Number(value.toPrecision(8)));update();}
 chartElement.addEventListener('pointermove',move);chartElement.addEventListener('pointerup',event=>{if(!drag)return;move(event);drag=null;chartElement.releasePointerCapture?.(event.pointerId);update();});chartElement.addEventListener('pointercancel',()=>{drag=null;update();});
 chartElement.addEventListener('lostpointercapture',()=>{if(drag){drag=null;update();}});
 chartElement.addEventListener('keydown',event=>{const handle=event.target.closest('[data-drag-level]');if(!handle||!['ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const name=handle.dataset.dragLevel,old=Number(field(name).value),step=(chartElement._scale.max-chartElement._scale.min)/(event.shiftKey?20:100);field(name).value=String(Number(Math.max(Number.MIN_VALUE,old+(event.key==='ArrowUp'?step:-step)).toPrecision(8)));update();q(`[data-drag-level="${name}"]`)?.focus();});
 window.addEventListener('resize',()=>{drag=null;update();});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)update();});
 update();return {refresh:update,clear(){++request;controller?.abort();market=null;loading=false;marketMessage='';ticketOpen=false;drag=null;for(const name of fields)if(name!=='quoteCurrency')field(name).value='';field('customAsset').value='';q('[data-custom]').hidden=true;field('quoteCurrency').value='USDT';q('[name="exitMode"][value="fixed"]').checked=true;q('[name="exitMode"][value="trailing"]').checked=false;q('[data-ticket]').hidden=true;q('[data-ticket-text]').value='';update();}};
}
