import {publicScoutDisplay} from './public-scout.mjs?v=public-scout-review-20261010';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createWebEvidenceStore,setupMarketWeb,WEB_MARKET_IDS} from './agent-web.mjs';
const T=Date.parse('2026-10-10T00:00:00.000Z'),iso=at=>new Date(at).toISOString();
const packet=(n=0,state='observed')=>({version:1,nodes:Array.from({length:6},(_,i)=>({slot:i+1,key:`record-${i}-${n}`,at:iso(T+n*1000),state}))});
const see=(s,p,n=0,active=true)=>s.observe(p,{now:T+n*1000,active});
test('first snapshot baselines six evidence groups; no independent agents or first-load playback',()=>{const s=createWebEvidenceStore();assert.deepEqual(see(s,packet()),{accepted:true,pulses:[]});assert.equal(s.size(),6);});
test('new real observation pulses once, duplicates and age refresh never replay',()=>{const s=createWebEvidenceStore();see(s,packet());assert.deepEqual(see(s,packet(1),1).pulses,[1,2,3,4,5,6]);for(let n=1;n<30;n++)assert.deepEqual(see(s,packet(1),n).pulses,[]);assert.equal(s.size(),6);});
test('absent evidence never creates events, and late first record remains baseline',()=>{const s=createWebEvidenceStore(),p=packet();p.nodes.forEach(node=>{node.key=null;node.at=null;node.state='waiting';});for(let n=0;n<30;n++)assert.deepEqual(see(s,p,n).pulses,[]);assert.equal(s.size(),0);assert.deepEqual(see(s,packet(30),30).pulses,[]);});
test('stale, offline, catalogue snapshots and over-age records never pulse',()=>{for(const state of ['stale','offline','waiting','snapshot']){const s=createWebEvidenceStore();see(s,packet());assert.deepEqual(see(s,packet(1,state),1).pulses,[]);assert.deepEqual(see(s,packet(2),18).pulses,[]);}});
test('future/invalid/missing/duplicate slot markers fail closed atomically',()=>{for(const mutate of [p=>p.version=2,p=>p.nodes.pop(),p=>p.nodes[0].slot=2,p=>p.nodes[0].slot=7,p=>p.nodes[1].at='tomorrow',p=>p.nodes[1].state='working',p=>p.nodes[0].key='x'.repeat(201)]){const s=createWebEvidenceStore(),p=packet();mutate(p);assert.equal(see(s,p).accepted,false);assert.equal(s.size(),0);}assert.equal(see(createWebEvidenceStore(),packet(1)).accepted,false);});
test('old or changed identity at the same timestamp cannot replay or freshen',()=>{const s=createWebEvidenceStore();see(s,packet());see(s,packet(2),2);assert.deepEqual(see(s,packet(1),3).pulses,[]);const p=packet(2);p.nodes.forEach(node=>node.key='replacement');assert.deepEqual(see(s,p,4).pulses,[]);});
test('clock rollback, hidden receipt, pause and resume require genuinely newer observations',()=>{const s=createWebEvidenceStore();see(s,packet());assert.deepEqual(see(s,packet(1),1,false).pulses,[]);assert.deepEqual(see(s,packet(1),2).pulses,[]);s.pause(T+3000);assert.deepEqual(see(s,packet(2),4).pulses,[]);assert.deepEqual(see(s,packet(5),5).pulses,[1,2,3,4,5,6]);assert.deepEqual(see(s,packet(4),4).pulses,[]);assert.deepEqual(see(s,packet(5),6).pulses,[]);assert.deepEqual(see(s,packet(7),7).pulses,[1,2,3,4,5,6]);});
class Node{constructor(){this.attrs={};this.events={};}setAttribute(k,v){this.attrs[k]=v;}getAttribute(k){return this.attrs[k];}addEventListener(k,fn){this.events[k]=fn;}removeEventListener(k){delete this.events[k];}}
function ui(){const nodes=Object.fromEntries([...WEB_MARKET_IDS,'teamTerminal','showCodingTeam'].map(id=>[id,new Node()])),events={},timers=[];nodes.teamTerminal.setAttribute('data-view','market');let now=T;const document={hidden:false,getElementById:id=>nodes[id],addEventListener:(k,fn)=>events[k]=fn,removeEventListener:k=>delete events[k]};const app=setupMarketWeb({document,now:()=>now,setTimeout:fn=>{timers.push(fn);return timers.length;},clearTimeout(){}});return {nodes,events,timers,document,app,send(p,n){now=T+n*1000;events['neptune:market-evidence']({detail:p});}};}
test('DOM pulse clears immediately on offline, rejected events never relabel nodes',()=>{const b=ui();b.send(packet(),0);b.send(packet(1),1);assert.equal(b.nodes.openDepthStream.attrs['data-pulse'],'true');b.send(packet(1,'offline'),2);assert.equal(b.nodes.openDepthStream.attrs['data-pulse'],'false');const bad=packet(3);bad.nodes[5].slot=1;b.send(bad,3);assert.equal(b.nodes.openDepthStream.attrs['data-state'],'offline');assert.equal(b.timers.length,6);b.app.dispose();assert.equal(b.events['neptune:market-evidence'],undefined);});
test('worker selection and hidden document clear market animation with no replay on return',()=>{const b=ui();b.send(packet(),0);b.send(packet(1),1);b.nodes.showCodingTeam.events.click();assert.equal(b.nodes.openDepthStream.attrs['data-pulse'],'false');b.document.hidden=true;b.events.visibilitychange();b.send(packet(2),2);b.document.hidden=false;b.events.visibilitychange();b.send(packet(2),3);assert.equal(b.nodes.openDepthStream.attrs['data-pulse'],'false');assert.equal(b.timers.length,6);});
test('web stays bounded with accessible role controls and motion opt-outs',()=>{const css=fs.readFileSync(new URL('./team-work.css',import.meta.url),'utf8'),html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8'),source=fs.readFileSync(new URL('./agent-web.mjs',import.meta.url),'utf8');assert.match(html,/6 check groups/);assert.match(html,/travelling currents are decorative ambient motion, not live network connections or proof of worker activity/);assert.equal((html.match(/class="stream-window"/g)||[]).length,6);assert.doesNotMatch(html,/aria-label="AGENT 00[1-6]\./);for(const id of WEB_MARKET_IDS)assert.ok(html.includes('id="'+id+'"'));assert.match(css,/\.agent-web-strands\{[^}]*pointer-events:none/);assert.match(css,/craft-observation 850ms ease-out 1/);assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/body\.still \.agent-web/);assert.match(css,/:focus-visible/);assert.doesNotMatch(source,/Math\.random|requestAnimationFrame|setInterval|fetch\(|innerHTML/);});
test('visual event markers come only from existing evidence and carry no balances or credentials',()=>{const source=fs.readFileSync(new URL('./neptune.mjs',import.meta.url),'utf8'),markers=source.slice(source.indexOf('const marker='),source.indexOf('function renderPortfolio'));assert.match(markers,/marker\(2,depth\?\.id,depth\?\.at/);assert.match(markers,/marker\(5,latestFill\?\.id,latestFill\?\.at/);assert.doesNotMatch(markers,/account|publicKey|wallet|balance|fetch/);});

test('decorative orbit and spin are explicitly labelled and never animate the input target',()=>{
 const css=fs.readFileSync(new URL('./team-work.css',import.meta.url),'utf8'),html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
 assert.match(html,/Ambient flight · tap for real evidence/);assert.match(html,/Ship circulation and spinning are decorative ambient motion, not worker activity/);
 assert.match(css,/animation:craft-ambient-orbit var\(--craft-period,9s\) linear infinite/);
 assert.match(css,/\.worker-slot:not\(\[data-state=working\]\) \.worker-number:before\{animation:none/);
 assert.match(css,/body\.still \.agent-web \.stream-name:before/);
 assert.match(css,/@media\(prefers-reduced-motion:reduce\)\{\.team-terminal \.agent-web \.stream-name:before/);
 assert.match(css,/@keyframes worker-handoff-laser/);assert.match(css,/worker-handoff-laser 850ms ease-out 1/);
 for(const match of css.matchAll(/([^{}]+)\{[^{}]*animation:craft-ambient-orbit[^{}]*\}/g))assert.ok(match[1].split(',').every(selector=>selector.trim().endsWith(':before')));
});

test('six small original SVG hulls are local static artwork, with no scripted activity or network resources',()=>{
 const css=fs.readFileSync(new URL('./team-work.css',import.meta.url),'utf8');
 for(let n=1;n<=6;n++){const path=`assets/web-craft-${String(n).padStart(2,'0')}.svg`,svg=fs.readFileSync(new URL('./'+path,import.meta.url),'utf8');assert.ok(svg.length<2000);assert.match(svg,/<svg xmlns="http:\/\/www.w3.org\/2000\/svg" viewBox="0 0 64 64">/);assert.doesNotMatch(svg,/<script|<foreignObject|<animate|<image|href=|onload=|onclick=/);assert.ok(css.includes(path+'?v=web-craft-20261010'));}
});

test('actual renderStreams dispatches only the six matching public evidence markers',()=>{
 const source=fs.readFileSync(new URL('./neptune.mjs',import.meta.url),'utf8'),code=source.slice(source.indexOf('function renderStreams('),source.indexOf('function renderPortfolio('));
 for(const connected of [true,false]){
  const events=[],nodes=new Map(),at=iso(T+1000),report={heartbeat_at:at,risk:{entry_paused:false,per_entry_pct:.25,max_positions:2,aggregate_pct:1,daily_drawdown_pct:2,total_drawdown_pct:5},account:{initial_cash:10000,fills:1,private_balance:123456},decisions:[{id:'decision-1',at,asset:'ETH/USD',action:'hold',reason:'spread_too_wide',source:'fixture'}],fills:[{id:'fill-1',at,asset:'ETH/USD',side:'buy',price:1000}],status:'running'};
  const context=vm.createContext({publicScout:{snapshot:()=>null},publicScoutDisplay,report,connected,busy:false,polls:1,runtimeEvents:[{at,message:'Report validated'}],readResearchV1:()=>null,readNativePaper:()=>({state:'unavailable'}),nativeFillLabel:()=>'',fresh:(at,now,limit)=>now-Date.parse(at)>=0&&now-Date.parse(at)<=limit,safe:x=>String(x??''),stamp:x=>x,sampleAge:()=>'',quote:x=>String(x),Date:class extends Date{static now(){return T+1000;}},$:id=>{if(!nodes.has(id))nodes.set(id,{textContent:''});return nodes.get(id);},document:{dispatchEvent:event=>events.push(event)},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail;}}});
  vm.runInContext(code+`;renderStreams({status:'${connected?'running':'offline'}'});`,context);
  assert.equal(events.length,1);assert.equal(events[0].type,'neptune:market-evidence');const markers=JSON.parse(JSON.stringify(events[0].detail));assert.equal(markers.nodes[1].key,'decision-1');assert.equal(markers.nodes[2].key,'decision-1');assert.equal(markers.nodes[4].key,'fill-1');assert.equal(markers.nodes[1].state,connected?'observed':'offline');assert.equal(see(createWebEvidenceStore(),markers,1).accepted,true);assert.doesNotMatch(JSON.stringify(markers),/123456|private_balance|account|initial_cash/);
 }
});
