import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {SCENE_LIMITS,pose,layout,skeleton,point,mul,renderScene}from'./cosmos-scene.mjs?v=neptune-v2-20261009-r8';
test('deterministic bounded decorative choreography and seamless cycle',()=>{for(const t of [NaN,Infinity,-3,0,1.375,7,13,18,1e6]){const p=pose(t);assert.deepEqual(p,pose(t));for(const v of Object.values(p))assert.ok(Number.isFinite(v));assert.ok(p.beam>=0&&p.beam<=1);assert.ok(p.attend>=0&&p.attend<=1);assert.ok(p.section>=0&&p.section<3);}assert.deepEqual(pose(0),pose(7.5));});
test('both planted foot anchors stay exactly fixed throughout full cycle',()=>{for(const [w,h]of[[320,568],[390,844],[768,1024],[1280,800]]){const initial=skeleton(0,w,h).feet;for(let i=0;i<1800;i++)assert.deepEqual(skeleton(i/100,w,h).feet,initial);}});
test('foot anchors lie on visible rock plane and above reserved lower UI',()=>{for(const [w,h]of[[320,568],[390,844],[768,1024],[1280,800]]){const {feet,l}=skeleton(1.375,w,h);for(const f of feet){assert.ok(f.x>l.rock.x+l.rock.w*.15&&f.x<l.rock.x+l.rock.w*.85);assert.ok(f.y>l.rock.y&&f.y<l.rock.y+l.rock.h*.35);assert.ok(f.y<h*.73);}}});
test('head and arm actually articulate relative to fixed lower body',()=>{const a=skeleton(0,1280,800),b=skeleton(1.375,1280,800);assert.notDeepEqual(a.head,b.head);assert.notDeepEqual(a.fore,b.fore);assert.notDeepEqual(a.torso,b.torso);assert.deepEqual(a.feet,b.feet);const hand=s=>point(mul(s.l.root,s.fore),840,775);assert.ok(Math.hypot(hand(a).x-hand(b).x,hand(a).y-hand(b).y)>55);assert.ok(Math.hypot(a.eyes[0].x-b.eyes[0].x,a.eyes[0].y-b.eyes[0].y)>10);});
test('left-arm inverse kinematics keep the staff-gripping wrist fixed',()=>{for(let i=0;i<180;i++){const s=skeleton(i/10,1280,800),w=point(s.leftFore,220,600);assert.ok(Math.hypot(w.x-220,w.y-600)<.001);}});
test('eye anchors are transformed with same independent head matrix',()=>{for(const t of[0,1.375,7,13]){const s=skeleton(t,390,844);assert.deepEqual(s.eyes,[point(mul(s.l.root,s.head),580,206),point(mul(s.l.root,s.head),619,211)]);}});
function ctx(){return{draws:0,strokes:0,clearRect(){},drawImage(){this.draws++;},save(){},restore(){},translate(){},scale(){},transform(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},clip(){},ellipse(){},arc(){},fill(){},fillText(){},fillRect(){},setLineDash(){},stroke(){this.strokes++;}};}
test('renderer has ten bounded draw calls and two short ambient beams',()=>{const c=ctx();renderScene(c,[{},{},{}],1.375,390,844);assert.equal(c.draws,10);assert.equal(c.strokes,2);});
test('reduced-motion scene remains static and has no laser beam',()=>{const c=ctx(),a=renderScene(c,[{},{},{}],1.375,390,844,{reduced:true}),b=renderScene(c,[{},{},{}],12,390,844,{reduced:true});assert.deepEqual(a,b);assert.equal(c.strokes,0);});
test('preview never creates financial state or real-looking trade cue',()=>{const src=fs.readFileSync(new URL('./cosmos-scene.mjs',import.meta.url),'utf8');assert.doesNotMatch(src,/fetch\(|localStorage|sessionStorage|setInterval|requestAnimationFrame|AudioContext|innerHTML|QUALIFYING|PAPER BUY|PAPER SELL/);assert.match(src,/AMBIENT SCAN · NOT A TRADE SIGNAL/);assert.equal(SCENE_LIMITS.coinNodes,6);});
test('responsive phone figure is smaller with head and raised wrist visible',()=>{for(const [w,h]of[[320,568],[390,844],[430,932]])for(const t of[0,1.375,9.3,15.3]){const s=skeleton(t,w,h),hand=point(mul(s.l.root,s.fore),840,775);for(const p of[...s.eyes,hand])assert.ok(p.x>0&&p.x<w&&p.y>0&&p.y<h*.73);assert.ok(layout(w,h).s*1460<=h*.33);}});
test('integrated eye target uses the shared DOM market centre without duplicate canvas labels',()=>{const c=ctx(),labels=[];c.fillText=t=>labels.push(t);const result=renderScene(c,[{},{},{}],1.375,390,844,{showMarketLabels:false,showCaption:false,marketPositions:[{label:'ETH',x:80,y:300}]});assert.equal(result.target.label,'ETH');assert.equal(result.target.x,80);assert.equal(result.target.y,300);assert.ok(!labels.includes('ETH'));});
