import test from 'node:test';import assert from 'node:assert/strict';import fs from'node:fs';import{createCanvas,loadImage,hasNativeCanvas}from'./canvas-test-support.mjs';import{choreography,drawEyeBeams,createActionSelector,TRANSITION_POSES}from'./character-motion.mjs?v=neptune-native-20261009';import{ASSETS,renderScene}from'./cosmos-scene.mjs?v=neptune-native-20261009';import{configureCosmicCanvas}from'./cosmic-motion.mjs?v=neptune-native-20261009';
configureCosmicCanvas(createCanvas);const images=await Promise.all(ASSETS.map(x=>loadImage(new URL('./assets/'+x,import.meta.url).pathname)));
test('bounded direction-aware locomotion includes all five action silhouettes',()=>{const kinds=new Set();for(const[w,h]of[[320,568],[390,844],[768,1024],[1280,800]])for(let i=0;i<4000;i++){const a=choreography(i/100,w,h);kinds.add(a.kind);for(const v of[a.x,a.ground,a.size,...a.eyes.flatMap(p=>[p.x,p.y])])assert.ok(Number.isFinite(v));assert.ok(a.x>a.size*.5&&a.x<w-a.size*.3);assert.ok(a.ground<=h*.71);assert.ok(a.frame>=0&&a.frame<6);}assert.deepEqual([...kinds].sort(),['crouch','fire','roll','run','turn']);});
test('adjacent ambient and receipt variants do not repeat',()=>{for(let i=0;i<16;i++)assert.notEqual(choreography(i*5,1280,800).variant,choreography((i+1)*5,1280,800).variant);const s=createActionSelector();let last;for(let i=0;i<100;i++){const c={eventId:'test-'+i},v=s.select(c);assert.notEqual(v,last);assert.equal(v,s.select(c));last=v;}});
test('left/right anatomy and eye anchors mirror together',()=>{for(const w of[390,1280]){const l=choreography(2,w,844,{target:{x:0,y:100}}),r=choreography(2,w,844,{target:{x:w,y:100}});assert.equal(l.facing,-1);assert.equal(r.facing,1);for(let i=0;i<2;i++){assert.ok(Math.abs((l.eyes[i].x-l.x)+(r.eyes[i].x-r.x))<1e-9);assert.equal(l.eyes[i].y,r.eyes[i].y);}}});
test('roll and running never emit beams, facing-away endpoints are rejected',()=>{const c=createCanvas(10,10).getContext('2d');for(const t of[.5,5.3,15.2,15.4]){const a=choreography(t,1280,800);assert.equal(drawEyeBeams(c,a,{x:1200,y:200}),0);}const a=choreography(2,1280,800,{target:{x:0,y:300}});assert.equal(drawEyeBeams(c,a,{x:1200,y:200}),0);assert.equal(drawEyeBeams(c,a,{x:0,y:300}),2);});
test('900ms receipt completes anticipation and fire without moving ground location',()=>{for(let variant=0;variant<4;variant++){const cue={eventId:'fixture',createdAt:1000,until:1900};const first=choreography(1.7,1280,800,{cue,eventId:cue.eventId,actionVariant:variant,now:1010});const fire=choreography(1.7,1280,800,{cue,eventId:cue.eventId,actionVariant:variant,now:1500});assert.equal(first.fire,false);assert.equal(fire.kind,'fire');assert.equal(first.x,fire.x);assert.equal(first.ground,fire.ground);}});
test('coherent beams use no dash and exactly eight bounded layered line strokes',()=>{let lines=0;const c=new Proxy(createCanvas(100,100).getContext('2d'),{get(o,k){if(k==='stroke')return()=>lines++;if(k==='setLineDash')return a=>assert.equal(a.length,0);const v=o[k];return typeof v==='function'?v.bind(o):v;},set(o,k,v){o[k]=v;return true;}});const a=choreography(2,1280,800);drawEyeBeams(c,a,{x:1200,y:200});assert.equal(lines,8);});
test('actual reduced-motion frames are byte-identical and have no laser',{skip:!hasNativeCanvas},()=>{const c=createCanvas(390,844),ctx=c.getContext('2d');renderScene(ctx,images,0,390,844,{reduced:true});const a=c.toBuffer('image/png');const r=renderScene(ctx,images,19,390,844,{reduced:true});assert.equal(r.pose.fire,false);assert.deepEqual(a,c.toBuffer('image/png'));});
test('sprite PNGs have actual alpha, not opaque gradient rectangles',{skip:!hasNativeCanvas},()=>{for(const i of[1,2,4]){const im=images[i],c=createCanvas(im.width,im.height),ctx=c.getContext('2d');ctx.drawImage(im,0,0);const p=ctx.getImageData(0,0,im.width,im.height).data;for(const[x,y]of[[0,0],[im.width-1,0],[0,im.height-1]])assert.ok(p[(y*im.width+x)*4+3]<=1);}});
test('source never invents trading state or performs IO/timer/financial work',()=>{for(const file of['character-motion.mjs','cosmos-scene.mjs'])assert.doesNotMatch(fs.readFileSync(new URL(file,import.meta.url),'utf8'),/fetch\(|localStorage|setInterval|requestAnimationFrame|QUALIFYING|Math.random/);assert.match(fs.readFileSync(new URL('cosmos-scene.mjs',import.meta.url),'utf8'),/isVerifiedCue\(cue,now\)/);});

test('opposite-facing turn preserves outgoing direction through first recovery pose',()=>{const a=choreography(1.17,1280,800,{target:{x:0,y:200}}),b=choreography(1.42,1280,800,{target:{x:0,y:200}});assert.equal(a.transition,true);assert.equal(a.facing,1);assert.equal(b.facing,-1);});

test('measured transition source rectangles keep crowns separate and exact foot pivots',()=>{for(const [sx,sy,sw,sh,root,foot]of TRANSITION_POSES){assert.ok(sx>=0&&sy>=0&&sx+sw<=1254&&sy+sh<=1254);assert.ok(foot>=sy&&foot<sy+sh);const k=240/627;assert.equal((sy-foot)*k+(foot-sy)*k,0);}assert.equal(TRANSITION_POSES[2][1],606);assert.equal(TRANSITION_POSES[0][3],606);});

test('queued receipt entry never flashes a frozen mid-run or mid-roll pose',()=>{for(const t of[.5,5.4])for(let actionVariant=0;actionVariant<4;actionVariant++){const cue={eventId:'burst-'+actionVariant,createdAt:1000,until:1900};for(const now of[1000,1030,1070]){const a=choreography(t,1280,800,{cue,eventId:cue.eventId,actionVariant,now});assert.ok(!['run','roll'].includes(a.kind));assert.equal(a.fire,false);}}});
