import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{createCanvas,loadImage,hasNativeCanvas}from'./canvas-test-support.mjs';import {COSMIC_LIMITS,cosmicGeometry,cosmicState,configureCosmicCanvas,drawCosmicMotion}from'./cosmic-motion.mjs?v=neptune-specialists-20261009';
const images=await Promise.all(['cosmos-ocean-background.webp',null,null,'cosmos-ocean-phone.webp'].map(x=>x?loadImage(new URL('./assets/'+x,import.meta.url).pathname):null));
const render=(w,h,t,reduced=false)=>{const c=createCanvas(w,h),ctx=c.getContext('2d');ctx.fillStyle='#123456';ctx.fillRect(0,0,w,h);drawCosmicMotion(ctx,images,t,w,h,{reduced});return ctx.getImageData(0,0,w,h).data;};
test('state is deterministic, nonfinite safe and reduced-motion time invariant',()=>{for(const t of[NaN,Infinity,-1,0,5,10000]){const s=cosmicState(t);for(const n of[s.time,...s.galaxyAngles,s.skyX,s.skyY,s.ringAngle,s.planetSpin])assert.ok(Number.isFinite(n));assert.deepEqual(s,cosmicState(t));assert.deepEqual(cosmicState(t,{reduced:true}),cosmicState(0));}});
test('galaxies rotate visibly and Saturn particles travel in seconds',()=>{const a=cosmicState(0),b=cosmicState(5);assert.ok(b.galaxyAngles[0]-a.galaxyAngles[0]>.3);assert.ok(b.ringAngle-a.ringAngle>1.4);assert.ok(Math.abs(b.skyX-a.skyX)>5);});
test('all canvas texture memory is bounded and cached across time/resizes',()=>{let count=0;configureCosmicCanvas((w,h)=>{count++;assert.ok(w<=512&&h<=512);return createCanvas(w,h);});render(1280,800,0);render(1280,800,1);render(960,600,2);assert.equal(count,3);render(390,844,0);render(390,844,3);assert.equal(count,6);assert.equal(COSMIC_LIMITS.stars,44);assert.equal(COSMIC_LIMITS.ringParticles,104);});
test('actual rendered sky changes substantially while water remains byte-identical',{skip:!hasNativeCanvas},()=>{configureCosmicCanvas(createCanvas);for(const [w,h]of[[1280,800],[390,844]]){const a=render(w,h,0),b=render(w,h,5),g=cosmicGeometry(w,h),cut=Math.ceil(g.horizon),skyBytes=Math.floor(g.horizon)*w*4;let changed=0;for(let i=0;i<skyBytes;i+=4)if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>20)changed++;assert.ok(changed/(skyBytes/4)>.22,`Substantial changed pixels ${changed/(skyBytes/4)}`);assert.deepEqual(a.slice(cut*w*4),b.slice(cut*w*4));for(let i=cut*w*4;i<a.length;i+=4)assert.equal(a[i],0x12);}});
test('actual reduced/off rendering is byte-identical at different times',{skip:!hasNativeCanvas},()=>{for(const [w,h]of[[390,844],[1280,800]])assert.deepEqual(render(w,h,0,true),render(w,h,29,true));});
test('renderer owns no timer, finance, IO, interaction, or light flashes',()=>{const s=fs.readFileSync(new URL('./cosmic-motion.mjs',import.meta.url),'utf8');assert.doesNotMatch(s,/requestAnimationFrame|setInterval|setTimeout|fetch\(|localStorage|sessionStorage|addEventListener|Date.now|Math.random|shadowBlur/);assert.ok(COSMIC_LIMITS.ringBands<=14);});
