import {createCanvas} from './canvas-test-support.mjs';
import test from'node:test';import assert from'node:assert/strict';import{makeCosmosScene}from'./cosmos-controller.mjs?v=experiment-provenance-v3-r2';
class Image{constructor(){this.events={};this.naturalWidth=0;}addEventListener(k,fn){this.events[k]=fn;}removeEventListener(k){delete this.events[k];}load(){this.naturalWidth=1024;this.events.load?.();}}
function boot(w=390,h=844){let id=0,draws=0;const pending=new Map(),ims=[],ctx=new Proxy(createCanvas(2,2).getContext('2d'),{get(o,k){if(k==='drawImage')return()=>{draws++;};const v=o[k];return typeof v==='function'?v.bind(o):v;},set(o,k,v){o[k]=v;return true;}}),canvas={style:{},getBoundingClientRect:()=>({width:w,height:h})},a=makeCosmosScene({canvas,ctx,request:fn=>{pending.set(++id,fn);return id;},cancel:i=>pending.delete(i),getDpr:()=>3,createImage:()=>{const im=new Image();ims.push(im);return im;}});return{a,canvas,pending,ims,draws:()=>draws,resize(x,y){w=x;h=y;a.resize();},step(t){const e=pending.entries().next().value;if(e){pending.delete(e[0]);e[1](t);}},load(){ims.forEach(i=>i.load());}};}
test('loads only portrait background plus four actor sheets on phone',()=>{const h=boot();h.a.resize();assert.equal(h.ims.length,5);assert.ok(h.ims.some(i=>i.src.endsWith('cosmos-ocean-phone.webp')));assert.ok(!h.ims.some(i=>i.src.endsWith('cosmos-ocean-background.webp')));h.load();assert.equal(h.canvas.style.opacity,'1');assert.equal(h.pending.size,0);});
test('on/off hidden offscreen and page resume never duplicate RAF',()=>{const h=boot();h.a.resize();h.load();h.a.setState({enabled:true});for(let i=0;i<20;i++)h.a.setState({enabled:true});assert.equal(h.pending.size,1);h.step(0);h.step(45);for(const s of[{enabled:false},{visible:false},{inView:false}]){h.a.setState({enabled:true,visible:true,inView:true});h.a.setState(s);assert.equal(h.pending.size,0);}h.a.setState({enabled:true,visible:true,inView:true});h.step(10000);assert.ok(h.a.snapshot().time<=.05);});
test('24fps and elapsed time are bounded after long stalls',()=>{const h=boot();h.a.resize();h.load();h.a.setState({enabled:true});h.step(0);const n=h.draws();h.step(10);assert.equal(h.draws(),n);h.step(100000);assert.ok(h.a.snapshot().time<=.05);});
test('iOS DPR/pixel caps and responsive background switching are bounded',()=>{const h=boot();h.a.resize();assert.equal(h.canvas.width,487);h.load();h.resize(1024,768);assert.equal(h.ims.length,6);h.load();h.resize(1e6,1e6);assert.ok(h.canvas.width*h.canvas.height<=1800000);h.resize(390,844);assert.equal(h.ims.length,6);});
test('asset failure cancels animation and returns original fallback',()=>{const h=boot();h.a.resize();h.load();h.a.setState({enabled:true});h.ims[0].events.error();assert.equal(h.pending.size,0);assert.equal(h.canvas.style.opacity,'0');assert.equal(h.a.snapshot().failed,true);});
test('destroy releases listeners and prevents more scheduling',()=>{const h=boot();h.a.resize();h.load();h.a.setState({enabled:true});h.a.destroy();assert.equal(h.pending.size,0);for(const im of h.ims)assert.equal(Object.keys(im.events).length,0);h.a.resize();h.a.setState({enabled:true});assert.equal(h.pending.size,0);});
