import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {LIMITS,makeNodes,project,imagePoint,protection,depthFrame,paintDepth,makeAtmosphere} from './depth-motion.mjs';
test('seed is deterministic, bounded and independent of finances',()=>{assert.deepEqual(makeNodes(),makeNodes());for(const n of [NaN,Infinity,-3,0,44,1e9])assert.ok(makeNodes(n).length<=88);assert.doesNotMatch(fs.readFileSync(new URL('./depth-motion.mjs',import.meta.url),'utf8'),/fetch\(|localStorage|sessionStorage|QUALIFYING|report\?\./);});
test('perspective makes near nodes larger and farther from vanishing point',()=>{const near=project(.8,.7,.1,1000,800),far=project(.8,.7,1.9,1000,800);assert.ok(near.scale>far.scale);assert.ok(near.x>far.x);assert.ok(near.y>far.y);for(const p of [project(NaN,Infinity,-5,NaN,Infinity),project(1,2,Infinity,1,1)])for(const v of Object.values(p))assert.ok(Number.isFinite(v));});
test('zero and invalid viewport produce no render geometry',()=>{for(const [w,h] of [[0,5],[5,0],[NaN,4],[2,Infinity]])assert.deepEqual(depthFrame(makeNodes(),5,w,h),{points:[],edges:[]});});
test('all viewports and long durations remain bounded, rear-first and deterministic',()=>{for(const [w,h] of [[390,844],[1440,900],[320,568],[8192,8192]])for(const t of [0,1,40,1e6]){const a=depthFrame(makeNodes(),t,w,h);assert.deepEqual(a,depthFrame(makeNodes(),t,w,h));assert.equal(a.points.length,88);assert.ok(a.edges.length<=96);assert.ok(a.points.every((p,i)=>!i||a.points[i-1].z>=p.z));for(const p of a.points){assert.ok(p.z>=.08&&p.z<=1.95);assert.ok(p.alpha>=0&&p.alpha<.45);assert.ok(p.radius>0&&p.radius<2);assert.ok(Number.isFinite(p.x+p.y));}const degrees={};for(const e of a.edges){degrees[e.a.id]=(degrees[e.a.id]||0)+1;degrees[e.b.id]=(degrees[e.b.id]||0)+1;}assert.ok(Object.values(degrees).every(d=>d<=2));}});
test('currents move through x y and depth with endpoint fade',()=>{const a=depthFrame(makeNodes(),0,1440,900),b=depthFrame(makeNodes(),10,1440,900);for(const p of a.points){const q=b.points.find(n=>n.id===p.id);assert.notEqual(p.x,q.x);assert.notEqual(p.y,q.y);assert.notEqual(p.z,q.z);}assert.equal(a.points.find(n=>n.id===0).alpha,0);});
test('face and measured text bounds attenuate points',()=>{for(const [w,h] of [[390,844],[1440,900]]){const face=imagePoint(.475,.19,w,h);assert.equal(protection(face.x,face.y,w,h),.15);assert.equal(protection(10,20,w,h,[{left:0,right:30,top:0,bottom:50}]),.1);}});
function harness({w=390,h=844,dpr=3,context=true}={}){let id=0,draws=0,cancels=0,box={width:w,height:h};const pending=new Map(),canvas={getBoundingClientRect:()=>box},ctx=context?{setTransform(){},clearRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){draws++;},arc(){},fill(){draws++;}}:null;const a=makeAtmosphere({canvas,ctx,getDpr:()=>dpr,request:fn=>{pending.set(++id,fn);return id;},cancel:i=>{pending.delete(i);cancels++;}});return {a,canvas,pending,setBox:v=>{box=v;},step(t){const next=pending.entries().next().value;if(!next)return;pending.delete(next[0]);next[1](t);},draws:()=>draws,cancels:()=>cancels};}
test('motion-off, hidden, offscreen and destruction cancel all frames',()=>{const h=harness();h.a.resize();assert.equal(h.pending.size,0);h.a.setState({enabled:true});assert.equal(h.pending.size,1);h.step(0);assert.ok(h.draws()>0);for(const state of [{enabled:false},{visible:false},{inView:false}]){h.a.setState({enabled:true,visible:true,inView:true});h.a.setState(state);assert.equal(h.pending.size,0);assert.equal(h.a.snapshot().active,false);}h.a.setState({enabled:true,visible:true,inView:true});h.a.destroy();assert.equal(h.pending.size,0);h.a.setState({enabled:true});h.a.resize();assert.equal(h.pending.size,0);assert.equal(h.a.snapshot().nodeCount,0);});
test('repeated resume never duplicates RAF and hidden time never jumps',()=>{const h=harness();h.a.resize();for(let i=0;i<20;i++)h.a.setState({enabled:true});assert.equal(h.pending.size,1);h.step(0);h.step(40);assert.equal(h.a.snapshot().time,.04);h.a.setState({visible:false});h.a.setState({visible:true});h.step(100000);assert.equal(h.a.snapshot().time,.04);h.step(200000);assert.ok(h.a.snapshot().time<=.09);});
test('30 fps budget skips short frames and rejects invalid time',()=>{const h=harness();h.a.resize();h.a.setState({enabled:true});h.step(0);const d=h.draws();h.step(10);h.step(NaN);assert.equal(h.draws(),d);h.step(34);assert.ok(h.draws()>d);assert.equal(h.pending.size,1);});
test('resize caps DPR, pixel allocation and mobile node budget',()=>{const h=harness();h.a.resize();assert.equal(h.canvas.width,585);assert.equal(h.a.snapshot().nodeCount,44);h.setBox({width:100000,height:100000});h.a.resize();assert.ok(h.canvas.width*h.canvas.height<=LIMITS.pixels);assert.equal(h.a.snapshot().nodeCount,88);h.a.setState({enabled:true});h.setBox({width:0,height:0});h.a.resize();assert.equal(h.pending.size,0);});
test('missing canvas context remains safely inactive',()=>{const h=harness({context:false});h.a.resize();h.a.setState({enabled:true});assert.equal(h.pending.size,0);h.a.destroy();});
test('paint uses rear/front geometry with finite low-opacity drawing only',()=>{const styles=[],ctx={beginPath(){},moveTo(){},lineTo(){},stroke(){},arc(){},fill(){},set fillStyle(v){styles.push(v);},set strokeStyle(v){styles.push(v);}};paintDepth(ctx,depthFrame(makeNodes(),15,1440,900));assert.ok(styles.length>88);assert.ok(styles.every(s=>/^rgba\(\d+,\d+,\d+,[\d.e-]+\)$/.test(s)));});
