import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHistory,validateHistoryRow,historyCsv} from './paper-history-v2.mjs?v=experiment-provenance-v3-r2';
const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-history-v2.json',import.meta.url)));
const page=({cursor,watermark,limit})=>fixture.rows.filter(r=>r.seq>cursor&&r.seq<=watermark).slice(0,limit);
import {nativeClosedProfit} from './native-history-validation.mjs';
function native(seq=1000){return {seq,kind:'native_fill_attribution',id:'native-'+seq,at:'2026-10-09T12:00:00Z',source_hash:'a'.repeat(64),config_hash:'b'.repeat(64),payload:{schema_version:3,id:'native-'+seq,at:'2026-10-09T12:00:00Z',asset:'binance:SOLUSDT',venue:'binance',quote_currency:'USDT',position_status:'dust_held',qty_remaining:'0.000000000000000001',dust_inventory:'0.000000000000000001',pnl_base:'1.2',closed_at:null,status:'settled'}};}
test('Mixed legacy native export retains exact decimals and all legacy rows',async()=>{const rows=[...fixture.rows,native()],h=createHistory({fetchPage:async q=>rows.filter(r=>r.seq>q.cursor&&r.seq<=q.watermark).slice(0,q.limit)});h.reset(1000);const csv=await h.exportAll();assert.equal(h.getState().rows.length,rows.length);assert(csv.includes('0.000000000000000001'));assert(csv.includes('native_fill_attribution'));assert.deepEqual(h.getState().rows.slice(0,fixture.rows.length),fixture.rows.map(validateHistoryRow));});
test('Native partial and dust cannot become closed profit',()=>{const r=native();validateHistoryRow(r);assert.equal(nativeClosedProfit(r.payload),false);r.payload.closed_at=r.at;assert.throws(()=>validateHistoryRow(r));r.payload.position_status='closed';assert.throws(()=>validateHistoryRow(r));r.payload.qty_remaining='0';assert.equal(nativeClosedProfit(r.payload),true);validateHistoryRow(r);});
test('Native payload rejects sensitive fields, nested objects and numeric precision loss',()=>{for(const changes of [{wallet:'SECRET'},{amount:{private:'SECRET'}},{qty_remaining:0.1},{quote_currency:'USD'},{schema_version:4}])assert.throws(()=>validateHistoryRow({...native(),payload:{...native().payload,...changes}}));const r=validateHistoryRow({...native(),wallet:'SECRET'});assert.equal(r.wallet,undefined);});
test('Native CSV formula escape and numeric-string precision are retained',()=>{const r=native();r.payload.reason='\t=HYPERLINK("evil")';assert(historyCsv([r]).includes("'\t=HYPERLINK"));});
test('Native duplicate correction rejects changed immutable event atomically',async()=>{let count=0;const r=native(1),other=native(2);const h=createHistory({fetchPage:async()=>++count===1?[r]:[{...r,payload:{...r.payload,pnl_base:'2'}},other]});h.reset(2);await h.more();await h.more();assert(h.getState().error);assert.equal(h.getState().rows.length,1);assert.equal(h.getState().cursor,1);});
test('Restart revalidates frozen watermark from authoritative source, not mutable cache',async()=>{const rows=[native(1),native(9)];let calls=0;const h=createHistory({fetchPage:async q=>{calls++;return rows.filter(r=>r.seq>q.cursor);}});h.reset(9);await h.exportAll();const saved=h.checkpoint();saved.rows[0].payload.pnl_base='999';h.restore(saved);assert.equal(h.getState().complete,false);await h.exportAll();assert.equal(calls,2);assert.equal(h.getState().rows[0].payload.pnl_base,'1.2');const snap=h.getState();snap.rows[0].payload.pnl_base='888';assert.equal(h.getState().rows[0].payload.pnl_base,'1.2');});
test('Immutable verified dust proof preserves boolean evidence and rejects contradictions',()=>{const r=native();Object.assign(r.payload,{verified_fee_dust:true,sold_entire_sellable_inventory:true,exit_reason:'protective_stop',sellable_inventory:'0',valuation_basis:'non_executable_conservative_floor',liquidation_floor_base:'0',conservative_risk_base:'0.000000000001'});validateHistoryRow(r);for(const change of [{verified_fee_dust:'true'},{sold_entire_sellable_inventory:false},{sellable_inventory:'1'},{exit_reason:'unknown'},{position_status:'closed',qty_remaining:'0'}])assert.throws(()=>validateHistoryRow({...r,payload:{...r.payload,...change}}));assert.equal(nativeClosedProfit(r.payload),false);});
test('native and exit model provenance survives validated history and complete CSV',()=>{const r=native();Object.assign(r.payload,{native_model_version:'native-paper-v1',native_model_hash:'c'.repeat(64),exit_native_model_hash:'d'.repeat(64)});const v=validateHistoryRow(r);assert.equal(v.payload.native_model_version,'native-paper-v1');assert.equal(v.payload.native_model_hash,'c'.repeat(64));assert.equal(v.payload.exit_native_model_hash,'d'.repeat(64));const csv=historyCsv([r]);assert.ok(csv.includes('native_model_version'));assert.ok(csv.includes('c'.repeat(64)));assert.ok(csv.includes('d'.repeat(64)));});
test('native provenance validates hash shape and version without rejecting historical absence',()=>{validateHistoryRow(native());for(const fields of [{native_model_hash:'bad'},{exit_native_model_hash:'g'.repeat(64)},{native_model_version:''},{native_model_version:'x'.repeat(129)}])assert.throws(()=>validateHistoryRow({...native(),payload:{...native().payload,...fields}}));});
