import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {readNativePaper,renderNativePaper,nativeFillLabel} from './native-paper.mjs';import {readPortfolioSnapshot} from './portfolio-snapshot.mjs';import {settledProfits} from './profit-events.mjs';
const now=Date.parse('2026-10-09T13:20:00Z'),at=new Date(now).toISOString(),old=new Date(now-90001).toISOString();
function report(){return {mode:'PAPER',currency:'AUD',heartbeat_at:at,quote_at:null,status:'data_stale',positions:[],results:[],fills:[],settlements:[],account:{fills:1,initial_cash:10000,cash:9500,equity:10007.5,unsettled_usd:0,valuation_at:at},native_paper:{version:1,mode:'PAPER',observed_at:at,valuation_at:at,valuation_complete:true,history_complete:false,positions:[{asset:'binance:SOLUSDT',agent_id:'binance',venue:'binance',base:'SOL',quote_currency:'USDT',owned_qty:.122877,sellable_qty:.122,dust_qty:.000877,cost_base:490,initial_risk_base:2,mark_base:500,position_status:'open'}],pending_quote_balances:[{agent_id:'binance',currency:'USDT',amount:5,mark_base:7.5}],recent_fills:[{id:'native-buy-1',asset:'binance:SOLUSDT',venue:'binance',side:'buy',quote_currency:'USDT',gross_qty:.123,fee_qty:.000123,fee_quote:0,fee_currency:'SOL',net_inventory_delta:.122877,net_quote_delta:-300,cash_delta_base:-450,fee_base:.45,fx_cost_base:1,position_status:'open',settlement_status:'settled',at}]}};}
function render(p){const nodes=Object.fromEntries(['nativeStatus','nativePositions','nativeBalances','nativeFills'].map(id=>[id,{textContent:'',replaceChildren(...c){this.children=c;}}]));const document={getElementById:id=>nodes[id],createElement:()=>({textContent:'',set innerHTML(v){throw Error('unsafe HTML');}})};const v=renderNativePaper(document,p,now);return {v,nodes,text:JSON.stringify(nodes)};}
test('owned net quantity, sellable lot, dust and typed stablecoin proceeds remain distinct',()=>{const p=report(),v=readNativePaper(p,now);assert.equal(v.state,'valid');assert.equal(v.markedTotal,507.5);assert.equal(v.positions[0].owned_qty,.122877);assert.equal(v.positions[0].dust_qty,.000877);const out=render(p);assert.match(out.text,/fee 0.000123 SOL/);assert.match(out.text,/5 USDT awaiting conversion/);assert.match(out.text,/not assumed equal to USD/);});
test('combined equity includes native holdings and typed balances exactly once',()=>{const p=report(),v=readPortfolioSnapshot(p,true,now);assert.equal(v.cash,9500);assert.equal(v.equity,10007.5);assert.equal(v.exposure,507.5);p.account.equity+=507.5;assert.equal(readPortfolioSnapshot(p,true,now).equity,null);});
test('missing native mark or incomplete conversion suppresses combined equity, not settled AUDcash',()=>{const p=report();p.native_paper.pending_quote_balances[0].mark_base=null;p.native_paper.valuation_complete=false;assert.equal(readNativePaper(p,now).state,'valid');const v=readPortfolioSnapshot(p,true,now);assert.equal(v.cash,9500);assert.equal(v.equity,null);assert.match(render(p).text,/marked AUD —/);});
test('legacy optional extension absence stays backwards compatible',()=>{const p=report();delete p.native_paper;p.account.equity=p.account.cash;assert.equal(readNativePaper(p,now).state,'absent');assert.equal(readPortfolioSnapshot(p,true,now).equity,9500);});
const bad={
 'wrong root currency':p=>p.currency='USD',
 'root live mode':p=>p.mode='LIVE',
 'hidden native fill count':p=>p.account.fills=0,
 'future fill':p=>p.native_paper.recent_fills[0].at=new Date(now+1).toISOString(),
 'cross-venue label':p=>p.native_paper.positions[0].venue='hyperliquid',
 'unknown asset':p=>p.native_paper.positions[0].asset='solana:any',
 'wrong owner':p=>p.native_paper.positions[0].agent_id='ethereum',
 'wrong base':p=>p.native_paper.positions[0].base='ETH',
 'USDT silently USD':p=>p.native_paper.pending_quote_balances[0].currency='USD',
 'duplicate position':p=>p.native_paper.positions.push({...p.native_paper.positions[0]}),
 'duplicate balance':p=>p.native_paper.pending_quote_balances.push({...p.native_paper.pending_quote_balances[0]}),
 'duplicate fill':p=>p.native_paper.recent_fills.push({...p.native_paper.recent_fills[0]}),
 'lost dust':p=>p.native_paper.positions[0].dust_qty=0,
 'tiny lost inventory':p=>{const x=p.native_paper.positions[0];x.owned_qty=1e-10;x.sellable_qty=1e-12;x.dust_qty=0;},
 'dust pretending sellable':p=>p.native_paper.positions[0].position_status='dust_held',
 'settled unknown AUD fee':p=>p.native_paper.recent_fills[0].fee_base=null,
 'settled unknown AUD FX':p=>p.native_paper.recent_fills[0].fx_cost_base=null,
 'missing fee':p=>delete p.native_paper.recent_fills[0].fee_qty,
 'gross credited as net':p=>p.native_paper.recent_fills[0].net_inventory_delta=.123,
 'wrong fee currency':p=>p.native_paper.recent_fills[0].fee_currency='USDT',
 'negative cost':p=>p.native_paper.positions[0].cost_base=-1,
 'missing mark despite complete':p=>p.native_paper.positions[0].mark_base=null,
 'pretending complete history':p=>p.native_paper.history_complete=true,
 'unsafe venue type':p=>p.native_paper.positions[0].venue=42,
 'numeric cash string':p=>p.native_paper.recent_fills[0].cash_delta_base='-450',
};for(const [name,mutate]of Object.entries(bad))test('rejects '+name+' without native values',()=>{const p=report();mutate(p);assert.equal(readNativePaper(p,now).state,'invalid');assert.equal(readPortfolioSnapshot(p,true,now).equity,null);assert.equal(readPortfolioSnapshot(p,true,now).cash,p.currency==='AUD'?9500:null);});
test('stale/future projection and heartbeat clear native values',()=>{for(const target of ['observed_at','heartbeat_at'])for(const value of [old,new Date(now+1).toISOString()]){const p=report();(target==='heartbeat_at'?p:p.native_paper)[target]=value;assert.notEqual(readNativePaper(p,now).state,'valid');assert.match(render(p).text,/withheld/);}});
test('stale native valuation does not become current from a fresh receipt',()=>{const p=report();p.native_paper.valuation_at=old;assert.equal(readNativePaper(p,now).valuationComplete,false);assert.equal(readPortfolioSnapshot(p,true,now).equity,null);});
function sell(status='dust_held',settled=false){return {id:'native-sell-1',asset:'binance:SOLUSDT',venue:'binance',side:'sell',quote_currency:'USDT',gross_qty:.122,fee_qty:0,fee_quote:.5,fee_currency:'USDT',net_inventory_delta:-.122,net_quote_delta:399.5,cash_delta_base:settled?599.25:null,fee_base:settled?.75:null,fx_cost_base:settled?1:null,position_status:status,settlement_status:settled?'settled':'pending_native_conversion',at};}
test('partial, dust and pending FX exits are displayed without a full-close profit cue',()=>{for(const status of ['open','dust_held','closed'])for(const settled of [false,true]){const p=report();p.native_paper.recent_fills=[sell(status,settled)];assert.equal(readNativePaper(p,now).state,'valid');assert.deepEqual(settledProfits(p),[]);assert.match(render(p).text,new RegExp(nativeFillLabel(p.native_paper.recent_fills[0])));}});
test('pending native proceeds never invent AUD cash, and venue text remains inert',()=>{const p=report();p.native_paper.recent_fills=[sell()];p.native_paper.recent_fills[0].cash_delta_base=10;assert.equal(readNativePaper(p,now).state,'invalid');p.native_paper.recent_fills[0].cash_delta_base=null;p.native_paper.positions[0].venue='<img src=x onerror=alert(1)>';assert.equal(readNativePaper(p,now).state,'invalid');});
test('native detail section stays inside same dialog and calm backdrop changes no asset',()=>{const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');assert.equal((html.match(/class="stream-window"/g)||[]).length,6);assert.ok(html.indexOf('id="nativeTitle"')>html.indexOf('id="historyDialog"'));assert.ok(html.indexOf('id="nativeTitle"')<html.indexOf('id="findingsDialog"'));const css=fs.readFileSync(new URL('./single-frame.css',import.meta.url),'utf8');assert.match(css,/\.lower-deck\{background:linear-gradient\(180deg,#071c2c/);});
test('mixed legacy/native equity requires explicit authoritative legacy subtotal and rejects native double count',()=>{const p=report();p.account.cash=9800;p.account.equity=10100;p.positions=[{qty:1,last_bid:100,quote_at:at}];p.native_paper.positions[0].mark_base=200;p.native_paper.pending_quote_balances=[];assert.equal(readPortfolioSnapshot(p,true,now).equity,null);p.native_paper.legacy_mark_base=100;assert.equal(readPortfolioSnapshot(p,true,now).equity,10100);p.account.equity=10300;assert.equal(readPortfolioSnapshot(p,true,now).equity,null);});
test('combined-native scope cannot silently omit the native extension',()=>{const p=report();p.account.valuation_scope='combined_native_v1';delete p.native_paper;p.account.equity=p.account.cash;assert.equal(readPortfolioSnapshot(p,true,now).cash,9500);assert.equal(readPortfolioSnapshot(p,true,now).equity,null);});
test('verified fee dust may use explicit conservative floor while retaining cost and lineage',()=>{const p=report(),x=p.native_paper.positions[0];Object.assign(x,{owned_qty:.000877,sellable_qty:0,dust_qty:.000877,qty_step:.001,cost_base:.000000000001,initial_risk_base:0,mark_base:0,position_status:'dust_held',verified_fee_dust:true,valuation_basis:'non_executable_conservative_floor',liquidation_floor_base:0,conservative_risk_base:.000000000001,inventory_cycle_id:'cycle1',last_fill_id:'dust-exit'});p.native_paper.pending_quote_balances=[];p.account.equity=p.account.cash;assert.equal(readNativePaper(p,now).state,'valid');assert.equal(readPortfolioSnapshot(p,true,now).exposure,0);assert.match(render(p).text,/not a quoted market price/);assert.match(render(p).text,/cycle cycle1/);assert.match(render(p).text,/0.000000000001/);assert.deepEqual(settledProfits(p),[]);for(const change of [{verified_fee_dust:false},{qty_step:.0001},{cost_base:0},{conservative_risk_base:0},{inventory_cycle_id:null}]){const q=structuredClone(p);Object.assign(q.native_paper.positions[0],change);assert.equal(readNativePaper(q,now).state,'invalid');}});
test('ordinary untradeable holding or typed quote cannot masquerade as a zero dust mark',()=>{const p=report();p.native_paper.positions[0].mark_base=0;assert.equal(readNativePaper(p,now).state,'invalid');const q=report();q.native_paper.pending_quote_balances[0].mark_base=0;assert.equal(readNativePaper(q,now).state,'invalid');});
