import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createCanvas} from './canvas-test-support.mjs';
import {neuralLinks,drawNeuralLinks,NEURAL_LIMITS} from './cosmos-scene.mjs?v=neural-links-20261010';
const now=Date.parse('2026-10-10T04:45:00Z');
const points=(n=42)=>Array.from({length:n},(_,i)=>({asset:'catalogue-'+i,label:'C'+i,x:40+(i%6)*80,y:40+Math.floor(i/6)*40,kind:'discovered',active:false,opacity:.6}));
const ctx=()=>createCanvas(600,350).getContext('2d');
test('visible coins form one bounded sparse spatial graph without self or duplicate links',()=>{const p=points(),e=neuralLinks(p);assert.ok(e.length>=p.length-1);assert.ok(e.length<=NEURAL_LIMITS.edges);const keys=e.map(({a,b})=>[a.asset,b.asset].sort().join('|'));assert.equal(new Set(keys).size,e.length);assert.ok(e.every(({a,b})=>a.asset!==b.asset));const reached=new Set([p[0].asset]);for(let i=0;i<p.length;i++)for(const {a,b}of e)if(reached.has(a.asset)||reached.has(b.asset)){reached.add(a.asset);reached.add(b.asset);}assert.equal(reached.size,p.length);});
test('node processing and edge output remain bounded even with an oversized input',()=>{const e=neuralLinks(points(1000));assert.ok(e.length<=NEURAL_LIMITS.edges);assert.ok(e.every(({a,b})=>Number(a.asset.split('-')[1])<NEURAL_LIMITS.nodes&&Number(b.asset.split('-')[1])<NEURAL_LIMITS.nodes));});
test('edges cannot cross a control mask and isolated sides remain separate',()=>{const p=[{asset:'a',x:20,y:50},{asset:'b',x:20,y:100},{asset:'c',x:180,y:50},{asset:'d',x:180,y:100}];const e=neuralLinks(p,{masks:[{left:80,right:120,top:0,bottom:150}]});assert.equal(e.length,2);assert.ok(e.every(({a,b})=>a.x===b.x));});
test('empty, one-node and fully masked views safely have no edges',()=>{assert.deepEqual(neuralLinks([]),[]);assert.deepEqual(neuralLinks(points(1)),[]);assert.deepEqual(neuralLinks(points(),{masks:[{left:0,right:600,top:0,bottom:350}]}),[]);});
test('catalogue identities are static connections with no activity pulse',()=>{const r=drawNeuralLinks(ctx(),points(),{now});assert.ok(r.edgeCount>0);assert.equal(r.pulses,0);assert.equal(r.beamCount,undefined);});
function checked(overrides={}){const p=points(3);p[1]={...p[1],kind:'checked',active:true,at:new Date(now-100).toISOString(),until:now+6400,result:'no_trade',...overrides};return p;}
test('fresh recorded check produces one short directional pulse without a beam cue',()=>{assert.equal(drawNeuralLinks(ctx(),checked(),{now}).pulses,1);assert.equal(drawNeuralLinks(ctx(),checked(),{now:now+1000}).pulses,0);});
for(const [name,fields]of [['inactive',{active:false}],['fill',{kind:'buy'}],['catalogue',{kind:'discovered'}],['expired',{until:now}],['future',{at:new Date(now+1).toISOString()}],['stale',{at:new Date(now-90001).toISOString()}]])test(name+' markers never create check pulses',()=>{assert.equal(drawNeuralLinks(ctx(),checked(fields),{now}).pulses,0);});
test('pending check uses its bounded marker lifetime and does not pulse for the whole pending window',()=>{const p=checked({result:'pending',until:now+11900});assert.equal(drawNeuralLinks(ctx(),p,{now}).pulses,1);assert.equal(drawNeuralLinks(ctx(),p,{now:now+1500}).pulses,0);});
test('reduced motion retains static spatial connections and suppresses every moving pulse',()=>{const r=drawNeuralLinks(ctx(),checked(),{now,reduced:true});assert.ok(r.edgeCount>0);assert.equal(r.pulses,0);});
test('spatial meaning is disclosed and renderer cannot write or mint receipt authority',()=>{const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8'),src=fs.readFileSync(new URL('./cosmos-scene.mjs',import.meta.url),'utf8');assert.match(html,/decorative spatial connections/);assert.match(html,/Amber pulses mark fresh recorded checks/);assert.doesNotMatch(src,/fetch\(|setInterval\(|trusted\.add|observeReport\(/);});
