import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createOwnerControl,controlAcknowledgement} from './paper-owner-v2.mjs';
const now=Date.parse('2026-10-09T06:00:00Z'),at=new Date(now).toISOString();
const initial=()=>({id:'neptune-paper-v2',enabled:false,epoch:0,changed_at:new Date(now-1000).toISOString(),owner_id:'synthetic-private-owner'});
function clientMock({signedIn=true,denied=false,writeHook,readHook}={}){let row=initial();const log=[];const client={auth:{getUser:async()=>({data:{user:signedIn?{id:'synthetic-private-owner',email:'synthetic@example.invalid'}:null},error:null})},from(table){let write=null,fields='',filters=[];const q={select(f){fields=f;return q;},update(v){write=v;return q;},eq(k,v){filters.push([k,v]);return q;},then(resolve,reject){log.push({table,fields,filters,write});let result;if(denied)result={data:[],error:{status:403,message:'private owner raw error'}};else if(write){if(writeHook)return Promise.resolve(writeHook({row,write,filters})).then(resolve,reject);const match=filters.find(([k])=>k==='epoch')?.[1]===row.epoch;if(!match)result={data:[],error:null};else{row={...row,enabled:write.enabled,epoch:row.epoch+1,changed_at:at};result={data:[row],error:null};}}else{result=readHook?readHook(row):{data:[row],error:null};}return Promise.resolve(result).then(resolve,reject);}};return q;}};return {client,log,getRow:()=>row};}
const ack=(control,extra={})=>({heartbeat_at:at,control:{requested_enabled:control.enabled,requested_epoch:control.epoch,ack_epoch:control.epoch,enabled:control.enabled,ack_status:'applied',ack_at:at,...extra}});
test('signed-out/public viewer never sees controls or sends a mutation',async()=>{const m=clientMock({signedIn:false}),o=createOwnerControl({getClient:async()=>m.client,now:()=>now});await o.refresh();await o.requestEnabled(true);assert.equal(o.getState().access,'signed-out');assert.equal(m.log.length,0);});
test('owner verification selects no identity and never exposes auth identity',async()=>{const m=clientMock(),changes=[],o=createOwnerControl({getClient:async()=>m.client,now:()=>now,onChange:s=>changes.push(s)});await o.refresh();assert.equal(o.getState().access,'owner');assert.doesNotMatch(JSON.stringify(changes),/synthetic-private-owner|example.invalid/);assert.ok(m.log.every(l=>l.fields==='id,enabled,epoch,changed_at'));});
test('owner writes only enabled using fresh id/epoch lease and awaits separate acknowledgement',async()=>{const m=clientMock(),o=createOwnerControl({getClient:async()=>m.client,now:()=>now});await o.refresh();await o.requestEnabled(true);const request=m.log.find(l=>l.write);assert.equal(request.table,'neptune_paper_v2_control');assert.deepEqual(request.write,{enabled:true});assert.deepEqual(request.filters,[['id','neptune-paper-v2'],['epoch',0]]);assert.match(o.getState().message,/Waiting/);o.observe(ack(o.getState().control));assert.match(o.getState().message,/Resume acknowledged/);});
test('stale, future, mismatched or old epoch acknowledgement never claims applied',()=>{const c={...initial(),enabled:true,epoch:3,changed_at:at};for(const report of [ack(c,{ack_epoch:2}),ack(c,{requested_epoch:2}),ack(c,{ack_at:new Date(now-1).toISOString()}),{...ack(c),heartbeat_at:new Date(now-90001).toISOString()},ack(c,{ack_at:new Date(now+1).toISOString()})])assert.equal(controlAcknowledgement(c,report,now).applied,false);});
test('durable old acknowledgement remains valid with matching request and fresh heartbeat',()=>{const c={...initial(),epoch:3,changed_at:new Date(now-300000).toISOString()},r=ack(c,{ack_at:new Date(now-200000).toISOString()});assert.equal(controlAcknowledgement(c,r,now).applied,true);});
test('capacity rejection never claims Resume applied',()=>{const c={...initial(),enabled:true,epoch:3,changed_at:at};const result=controlAcknowledgement(c,ack(c,{ack_status:'rejected_capacity',enabled:false}),now);assert.equal(result.applied,false);assert.equal(result.rejected,true);});
test('rapid clicks coalesce while write pending and late sign-out response is ignored',async()=>{let release;const m=clientMock({writeHook:()=>new Promise(r=>{release=r;})}),o=createOwnerControl({getClient:async()=>m.client,now:()=>now});await o.refresh();const first=o.requestEnabled(true);await new Promise(r=>setImmediate(r));await o.requestEnabled(false);assert.equal(m.log.filter(l=>l.write).length,1);o.invalidate();release({data:[{...initial(),enabled:true,epoch:1,changed_at:at}],error:null});await first;assert.equal(o.getState().access,'signed-out');assert.equal(o.getState().control,null);});
test('CAS conflict or denied owner remains unconfirmed, raw error never rendered',async()=>{for(const options of [{writeHook:async()=>({data:[],error:null})},{denied:true}]){const m=clientMock(options),o=createOwnerControl({getClient:async()=>m.client,now:()=>now});await o.refresh();await o.requestEnabled(true);assert.notEqual(o.getState().message,'Resume acknowledged');assert.doesNotMatch(o.getState().message,/private owner raw error/);}});
test('Stop remains requestable without the public feed and exposure is not prematurely frozen',async()=>{const m=clientMock(),o=createOwnerControl({getClient:async()=>m.client,now:()=>now});await o.refresh();o.observe(null);await o.requestEnabled(false);assert.match(o.getState().message,/not yet confirmed frozen/);assert.equal(m.log.filter(l=>l.write).length,1);});

test('actual SQL control projection acknowledges after its earlier heartbeat timestamp',()=>{const r=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-control-v2.json',import.meta.url)));const c={id:'neptune-paper-v2',enabled:r.control.requested_enabled,epoch:r.control.requested_epoch,changed_at:r.heartbeat_at};assert.equal(controlAcknowledgement(c,r,Date.parse(r.control.ack_at)+1000).applied,true);});
test('client initialization timeout unlocks controls and permits an explicit retry without writes',async()=>{
 let release,attempt=0;const m=clientMock(),o=createOwnerControl({getClient:()=>++attempt===1?new Promise(r=>release=r):Promise.resolve(m.client),timeoutMs:5,now:()=>now});
 const first=o.refresh();assert.equal(o.getState().busy,true);assert.match(o.getState().message,/Checking/);await first;
 assert.equal(o.getState().busy,false);assert.equal(o.getState().access,'unavailable');assert.equal(m.log.length,0);
 await o.refresh();assert.equal(o.getState().access,'owner');release(m.client);await new Promise(r=>setImmediate(r));assert.equal(m.log.filter(x=>x.write).length,0);
});
test('late client initialization after timeout or sign-out cannot send a requested write',async()=>{
 let release,attempt=0;const m=clientMock(),o=createOwnerControl({getClient:()=>++attempt===1?Promise.resolve(m.client):new Promise(r=>release=r),timeoutMs:5,now:()=>now});
 await o.refresh();const pending=o.requestEnabled(true);await pending;assert.equal(o.getState().busy,false);o.invalidate();release(m.client);await new Promise(r=>setImmediate(r));assert.equal(o.getState().access,'signed-out');assert.equal(m.log.filter(x=>x.write).length,0);
});
