import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createPaperPositionCharts,renderPaperPositionCharts,positionChartGeometry,POSITION_SAMPLE_LIMIT,POSITION_SAMPLE_WINDOW_MS,POSITION_RECEIPT_LIMIT} from './paper-position-charts.mjs?v=experiment-provenance-v3-r2';
import {paperTradePlanView} from './paper-trade-plan.mjs?v=experiment-provenance-v3-r2';
import {readPortfolioSnapshot} from './portfolio-snapshot.mjs';

// Local synthetic mutations of the checked engine fixture. These fixtures are
// never shipped as observed production prices or loaded by the runtime module.
const original=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-running-v2.json',import.meta.url)));
const NOW=Date.parse(original.heartbeat_at),iso=n=>new Date(n).toISOString();
const report=()=>{const p=structuredClone(original);for(const x of p.positions)x.tick_size=.000001;return p;};
function advance(p,delta=1000){p.heartbeat_at=iso(Date.parse(p.heartbeat_at)+delta);p.account.valuation_at=p.heartbeat_at;p.account.fx_retrieved_at=p.heartbeat_at;for(const x of p.positions)x.quote_at=p.heartbeat_at;return p;}
const ingest=(c,p,extra={})=>c.ingest({report:p,connected:true,now:Date.parse(p.heartbeat_at),...extra});
const get=(v,asset=original.positions[0].asset)=>v.rows.find(x=>x.asset===asset);
const copy=v=>structuredClone(v);

class Node{
 constructor(tag='div'){this.tag=tag;this.children=[];this.dataset={};this.attributes={};this.textContent='';}
 set innerHTML(v){throw Error('unsafe HTML');}
 append(...children){this.children.push(...children);}
 replaceChildren(...children){this.children=children;}
 setAttribute(k,v){this.attributes[k]=v;}
 querySelectorAll(selector){const matches=n=>selector==='details[open]'?n.tag==='details'&&n.open:selector.startsWith('.')?n.className?.split(' ').includes(selector.slice(1)):n.tag===selector;return this.children.flatMap(n=>[...(matches(n)?[n]:[]),...n.querySelectorAll(selector)]);}
 querySelector(selector){return this.querySelectorAll(selector)[0]??null;}
 focus(options){this.ownerDocument.activeElement=this;this.focusOptions=options;}
}
function dom(){const nodes=Object.fromEntries(['paperPositionWindows','paperPositionStatus','paperPositionPnl'].map(id=>[id,new Node()]));const document={activeElement:null,getElementById:id=>nodes[id],createElement:t=>{const n=new Node(t);n.ownerDocument=document;return n;},createElementNS:(_,t)=>new Node(t)};return {nodes,document};}
const textTree=n=>n.textContent+' '+n.children.map(textTree).join(' ');
const find=(n,tag)=>[...(n.tag===tag?[n]:[]),...n.children.flatMap(x=>find(x,tag))];

test('one independent window per verified open legacy position uses exact receipt identity',()=>{const p=report(),v=ingest(createPaperPositionCharts(),p);assert.equal(v.rows.length,3);assert.equal(new Set(v.rows.map(x=>x.key)).size,3);for(const row of v.rows){const pos=p.positions.find(x=>x.asset===row.asset);assert.equal(row.venue,'Kraken');assert.equal(row.currency,'USD');assert.equal(row.fillId,pos.entry_fill_id);assert.equal(row.entry,pos.entry_price);assert.equal(row.samples.length,1);assert.equal(row.samples[0].price,pos.last_bid);assert.equal(row.quoteCurrent,true);assert.equal(row.samples[0].receivedAt,NOW);}});
test('target estimates exactly reuse the independently reviewed plan; input and portfolio remain unchanged',()=>{const p=report(),before=copy(p),portfolio=readPortfolioSnapshot(p,true,NOW),v=ingest(createPaperPositionCharts(),p),plan=paperTradePlanView({report:p,connected:true,now:NOW});for(const r of v.rows){const expected=plan.rows.find(x=>x.asset===r.asset);assert.equal(r.estimatedNet,expected.estimatedNet);assert.equal(r.estimatedExit,expected.estimatedExit);}assert.deepEqual(p,before);assert.deepEqual(readPortfolioSnapshot(p,true,NOW),portfolio);});
test('all received bids, even unchanged prices, retain distinct source timestamps',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);advance(p);const v=ingest(c,p);assert.equal(get(v).samples.length,2);assert.equal(get(v).samples[0].price,get(v).samples[1].price);assert.notEqual(get(v).samples[0].at,get(v).samples[1].at);});
test('identical timestamps and repeated renders never create duplicate samples or receipt times',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);for(let i=1;i<20;i++){const v=ingest(c,p,{now:NOW+i});assert.equal(get(v).samples.length,1);assert.equal(get(v).samples[0].receivedAt,NOW);}advance(p);p.positions.forEach(x=>x.quote_at=iso(NOW));const v=ingest(c,p);assert.equal(get(v).samples.length,1);assert.equal(get(v).receivedAt,NOW);});
test('conflicting bids at one quote timestamp are removed and not replaced or revived',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);advance(p);const pos=p.positions[0];pos.quote_at=iso(NOW);pos.last_bid=105;let r=get(ingest(c,p));assert.equal(r.samples.length,0);assert.equal(r.latestBid,null);assert.match(r.sampleReason,/Conflicting/);advance(p);pos.quote_at=iso(NOW);pos.last_bid=104;r=get(ingest(c,p));assert.equal(r.samples.length,0);advance(p);r=get(ingest(c,p));assert.equal(r.samples.length,1);assert.equal(r.samples[0].breakBefore,true);});
test('same heartbeat with changed values is quarantined until a newer accepted report',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);p.positions[0].last_bid=999;let v=ingest(c,p);assert.equal(v.state,'CONFLICT');assert.equal(get(v).samples[0].price,104);assert.equal(get(v).latestBid,null);p.positions[0].last_bid=104;assert.equal(ingest(c,p).state,'CONFLICT');advance(p);v=ingest(c,p);assert.equal(v.state,'RECEIVED');assert.equal(get(v).samples[1].breakBefore,true);});
test('older report cannot undo a later close or reopen its line window',()=>{const p=report(),old=copy(p),c=createPaperPositionCharts();ingest(c,p);const asset=p.positions[0].asset;p.positions.shift();advance(p);assert.equal(ingest(c,p).rows.some(x=>x.asset===asset),false);const v=ingest(c,old,{now:NOW+2000});assert.equal(v.state,'LATE REPORT');assert.equal(v.rows.some(x=>x.asset===asset),false);});
test('newer replay of an already closed entry receipt fails closed instead of restarting history',()=>{const p=report(),old=copy(p),c=createPaperPositionCharts();ingest(c,p);p.positions.shift();advance(p);ingest(c,p);advance(old,2000);const r=get(ingest(c,old));assert.equal(r.identityVerified,false);assert.equal(r.entry,null);assert.equal(r.samples.length,0);assert.match(r.sampleReason,/closed/);});
function reopen(p){const x=p.positions[0],f=p.fills.find(f=>f.id===x.entry_fill_id);f.id+='-reopened';f.order_id+='-reopened';f.at=p.heartbeat_at;x.entry_fill_id=f.id;x.opened_at=f.at;}
test('genuine reopened cycle starts a new independent one-point series',()=>{const p=report(),c=createPaperPositionCharts(),first=get(ingest(c,p));advance(p);reopen(p);const r=get(ingest(c,p));assert.notEqual(r.key,first.key);assert.equal(r.samples.length,1);assert.equal(r.openedAt,NOW+1000);});
test('older entry cycle cannot replace a newer acknowledged cycle even under a new heartbeat',()=>{const p=report(),old=copy(p),c=createPaperPositionCharts();ingest(c,p);advance(p);reopen(p);ingest(c,p);advance(old,2000);const r=get(ingest(c,old));assert.equal(r.samples.length,0);assert.equal(r.identityVerified,false);});
test('mutation of acknowledged fill-linked entry cost cannot silently retain the same cycle',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);advance(p);p.positions[0].cost_base+=1;const r=get(ingest(c,p));assert.equal(r.identityVerified,false);assert.equal(r.samples.length,0);assert.equal(r.estimatedNet,null);});
for(const [name,change] of Object.entries({missing:p=>p.fills=p.fills.filter(f=>f.id!==p.positions[0].entry_fill_id),wrong:p=>p.positions[0].entry_fill_id=p.positions[1].entry_fill_id,venue:p=>p.positions[0].venue='Binance',quoteVenue:p=>p.positions[0].quote_venue='Hyperliquid',quoteMarket:p=>p.positions[0].quote_asset='ETH/USD',fillVenue:p=>p.fills.find(f=>f.id===p.positions[0].entry_fill_id).venue='Binance'}))test('no confirmed line for '+name+' entry/market identity',()=>{const p=report();change(p);const r=get(ingest(createPaperPositionCharts(),p));assert.equal(r.identityVerified,false);assert.equal(r.samples.length,0);assert.equal(r.estimatedNet,null);});
test('identity mismatch followed by correct receipt recovers without crashing or adopting mismatch data',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);advance(p);p.positions[0].venue='Binance';ingest(c,p);advance(p);delete p.positions[0].venue;const r=get(ingest(c,p));assert.equal(r.identityVerified,true);assert.equal(r.samples.length,1);});
for(const [name,change] of Object.entries({missing:p=>p.positions[0].last_bid=null,stale:p=>p.positions[0].quote_at=iso(NOW-90001),future:p=>p.positions[0].quote_at=iso(NOW+1),beforeEntry:p=>p.positions[0].quote_at=iso(NOW-1),badDate:p=>p.positions[0].quote_at='2026-02-30T00:00:00Z'}))test('no sample for '+name+' bid receipt',()=>{const p=report();change(p);const r=get(ingest(createPaperPositionCharts(),p));assert.equal(r.samples.length,0);assert.equal(r.quoteCurrent,false);assert.equal(r.estimatedNet,null);});
test('late quotes cannot move the line backwards',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);advance(p);ingest(c,p);advance(p);p.positions[0].quote_at=iso(NOW);const r=get(ingest(c,p));assert.equal(r.samples.length,2);assert.equal(r.latestBid,null);assert.match(r.sampleReason,/Out-of-order/);});
test('pending intentions create no position windows',()=>{const p=report();p.positions=[];p.fills=[];p.decisions=p.decisions.filter(d=>d.result==='pending');assert.equal(ingest(createPaperPositionCharts(),p).rows.length,0);});
test('fresh explicit flat report removes windows and discards their series',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);advance(p);p.positions=[];const v=ingest(c,p);assert.equal(v.rows.length,0);assert.equal(v.state,'RECEIVED');});
test('offline keeps clearly labelled last samples and withholds all current bid/estimated P&L',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);const v=ingest(c,p,{connected:false});assert.equal(v.state,'OFFLINE');for(const r of v.rows){assert.equal(r.reportCurrent,false);assert.equal(r.quoteCurrent,false);assert.equal(r.latestBid,null);assert.equal(r.estimatedNet,null);assert.equal(r.samples.length,1);}assert.equal(v.unrealised,null);});
test('stale report cannot remove a position or create a newly reported position',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);p.positions=[];const v=ingest(c,p,{now:NOW+90001});assert.equal(v.state,'STALE');assert.equal(v.rows.length,3);assert.ok(v.rows.every(r=>!r.reportCurrent));});
test('stale quote expires while a newer report remains fresh',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);advance(p,80000);for(const x of p.positions)x.quote_at=iso(NOW);ingest(c,p);const r=get(c.snapshot(NOW+90001));assert.equal(r.reportCurrent,true);assert.equal(r.quoteCurrent,false);assert.equal(r.sampleState,'STALE');assert.equal(r.latestBid,null);assert.equal(r.estimatedNet,null);});
test('bad or future report does not introduce prices or erase the last checked snapshot',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);advance(p);const v=ingest(c,p,{now:NOW});assert.equal(get(v).samples.length,1);assert.equal(get(v).latestBid,null);assert.equal(v.rows.length,3);});
test('invalid or backwards clocks neither erase samples nor show current values',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);for(const now of [NaN,Infinity,NOW-1]){const v=ingest(c,p,{now});assert.equal(get(v).samples.length,1);assert.equal(get(v).quoteCurrent,false);}assert.equal(get(ingest(c,p,{now:NOW+1})).quoteCurrent,true);});
test('sample count is capped per position and eviction is disclosed',()=>{const p=report(),c=createPaperPositionCharts();for(let i=0;i<POSITION_SAMPLE_LIMIT+20;i++){if(i)advance(p);ingest(c,p);}const r=get(c.snapshot(Date.parse(p.heartbeat_at)));assert.equal(r.samples.length,POSITION_SAMPLE_LIMIT);assert.equal(r.trimmed,true);assert.equal(r.samples[0].at,NOW+20000);});
test('one-hour window prunes old prices even during extended disconnection',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);const r=get(ingest(c,p,{connected:false,now:NOW+POSITION_SAMPLE_WINDOW_MS+1}));assert.equal(r.samples.length,0);assert.equal(r.trimmed,true);});
test('return after missing/offline data starts a gap rather than joining across the absence',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);advance(p);ingest(c,p);ingest(c,p,{connected:false});advance(p);const r=get(ingest(c,p));assert.equal(positionChartGeometry(r).segments.length,2);});
test('geometry has no fake line for a single point and splits natural time gaps',()=>{const row={entry:100,target:120,stop:90,samples:[{at:0,price:100},{at:10000,price:101},{at:100001,price:99}]};const g=positionChartGeometry(row);assert.equal(g.segments.length,2);assert.equal(g.levels.length,3);assert.equal(g.points.length,3);const one=positionChartGeometry({...row,samples:row.samples.slice(0,1)});assert.equal(one.points[0].x,500);assert.equal(one.segments[0].length,1);});
test('null levels stay absent; zero-price or overflow geometry never generates invalid SVG numbers',()=>{assert.equal(positionChartGeometry({entry:null,target:null,stop:null,samples:[]}),null);assert.equal(positionChartGeometry({entry:Number.MAX_VALUE,target:Number.MAX_VALUE,stop:Number.MAX_VALUE,samples:[]}),null);const g=positionChartGeometry({entry:1e-10,samples:[{at:100,price:1e-10}]});assert.ok(g.points.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)));});
function native(p){p.native_paper={version:1,mode:'PAPER',observed_at:p.heartbeat_at,valuation_at:null,valuation_complete:false,history_complete:false,positions:[{asset:'binance:SOLUSDT',agent_id:'binance',venue:'binance',base:'SOL',quote_currency:'USDT',owned_qty:1,sellable_qty:.999,dust_qty:.001,cost_base:200,initial_risk_base:2,mark_base:null,position_status:'open'}],pending_quote_balances:[],recent_fills:[]};return p;}
test('native holding has a separate explicit unsupported-price window; USDT never becomes USD',()=>{const p=native(report()),v=ingest(createPaperPositionCharts(),p),r=get(v,'binance:SOLUSDT');assert.equal(v.rows.length,4);assert.equal(r.currency,'USDT');assert.equal(r.entry,null);assert.equal(r.target,null);assert.equal(r.samples.length,0);assert.equal(r.cost,200);assert.equal(r.qty,1);assert.match(r.sampleReason,/no linked entry/);});
test('invalid/missing native projection retains only an unconfirmed placeholder; valid empty projection removes it',()=>{const p=native(report()),c=createPaperPositionCharts();ingest(c,p);advance(p);p.native_paper.observed_at=p.heartbeat_at;p.native_paper.positions[0].quote_currency='USD';let r=get(ingest(c,p),'binance:SOLUSDT');assert.equal(r.unconfirmed,true);assert.equal(r.reportCurrent,false);advance(p);delete p.native_paper;r=get(ingest(c,p),'binance:SOLUSDT');assert.equal(r.unconfirmed,true);advance(p);native(p);p.native_paper.positions=[];assert.equal(get(ingest(c,p),'binance:SOLUSDT'),undefined);});
test('target changes only update reference/estimate, never rewrite observed prices or account equity',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);const equity=p.account.equity;advance(p);p.positions[0].target*=2;const r=get(ingest(c,p));assert.equal(r.samples[0].price,104);assert.equal(p.account.equity,equity);assert.equal(r.target,p.positions[0].target);});
test('text-only DOM renderer emits cards, SVG points, explicit missing history and sample receipts',()=>{const p=report(),d=dom(),c=createPaperPositionCharts();renderPaperPositionCharts(d.document,c,{report:p,connected:true,now:NOW});assert.equal(d.nodes.paperPositionWindows.children.length,3);const card=d.nodes.paperPositionWindows.children[0];assert.equal(find(card,'circle').length,1);assert.equal(find(card,'polyline').length,0);assert.match(textTree(card),/at most 240 points \/ one hour/);assert.match(textTree(card),/Earlier history is unavailable/);assert.match(textTree(card),/does not allocate current net P&L/);assert.match(textTree(card),/first received/);assert.equal(find(card,'svg')[0].attributes.role,'img');});
test('identical render retains DOM nodes and new samples preserve expanded receipt detail',()=>{const p=report(),d=dom(),c=createPaperPositionCharts(),options={report:p,connected:true,now:NOW};renderPaperPositionCharts(d.document,c,options);const children=d.nodes.paperPositionWindows.children;renderPaperPositionCharts(d.document,c,options);assert.equal(d.nodes.paperPositionWindows.children,children);find(children[0],'details')[0].open=true;advance(p);renderPaperPositionCharts(d.document,c,{...options,now:NOW+1000});assert.equal(find(d.nodes.paperPositionWindows.children[0],'details')[0].open,true);});
test('receipt IDs containing HTML remain inert visible text with no script nodes',()=>{const p=report(),f=p.fills.find(f=>f.id===p.positions[0].entry_fill_id);f.id='<img src=x onerror=alert(1)>';p.positions[0].entry_fill_id=f.id;const d=dom();renderPaperPositionCharts(d.document,createPaperPositionCharts(),{report:p,connected:true,now:NOW});assert.match(textTree(d.nodes.paperPositionWindows),/<img src=x onerror=alert\(1\)>/);assert.equal(find(d.nodes.paperPositionWindows,'img').length,0);});
test('offline DOM labels historical values without current numbers or realised-profit claims',()=>{const p=report(),d=dom(),c=createPaperPositionCharts();renderPaperPositionCharts(d.document,c,{report:p,connected:true,now:NOW});renderPaperPositionCharts(d.document,c,{report:p,connected:false,now:NOW});assert.match(textTree(d.nodes.paperPositionWindows),/OPEN\/CLOSED UNCONFIRMED/);assert.match(d.nodes.paperPositionPnl.textContent,/Unavailable/);assert.equal(find(d.nodes.paperPositionWindows,'polyline').length,0);});
test('new controller/reload never receives persistent history from the previous page',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);advance(p);ingest(c,p);assert.equal(get(ingest(createPaperPositionCharts(),p)).samples.length,1);});
test('chart source has no new network, persistence, interval, writer or estimated-equity route',()=>{const src=fs.readFileSync(new URL('./paper-position-charts.mjs?v=experiment-provenance-v3-r2',import.meta.url),'utf8');assert.doesNotMatch(src,/\bfetch\s*\(|WebSocket|EventSource|localStorage|sessionStorage|setInterval|setTimeout|\.innerHTML\s*=|\.account\.\w+\s*=/);assert.match(src,/paperTradePlanView/);assert.doesNotMatch(src,/candlestick|OHLC/);});
test('new section is after main scene, scoped natural flow on phone/laptop, and preserves navigation',()=>{const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8'),css=fs.readFileSync(new URL('./paper-position-charts.css',import.meta.url),'utf8');assert.ok(html.indexOf('</main>')<html.indexOf('id="paperPositionCharts"'));assert.ok(html.indexOf('id="paperPositionCharts"')<html.indexOf('<dialog'));assert.match(css,/repeat\(2,minmax\(0,1fr\)\)/);assert.match(css,/@media\(max-width:900px\)/);assert.match(css,/grid-template-columns:minmax\(0,1fr\)/);assert.match(css,/overflow-wrap:anywhere/);assert.doesNotMatch(css,/font-family|\.observatory|\.world|#atmosphere|#art|position:fixed|100vw|min-width:\d+px/);for(const id of ['openPortfolio','openProgress','ownerStop','ownerResume','teamActivityPreview','openSeaChat'])assert.ok(html.includes('id="'+id+'"'));});

test('unconfirmed entry identity never renders even reference-level-only chart geometry',()=>{const p=report(),d=dom();p.fills=p.fills.filter(f=>f.id!==p.positions[0].entry_fill_id);renderPaperPositionCharts(d.document,createPaperPositionCharts(),{report:p,connected:true,now:NOW});assert.equal(find(d.nodes.paperPositionWindows.children[0],'svg').length,0);assert.match(textTree(d.nodes.paperPositionWindows.children[0]),/Matching actual entry receipt unavailable/);});

test('REVIEW: advancing the same closed fill timestamp cannot reopen its immutable identity',()=>{
 const p=report(),c=createPaperPositionCharts(),x=copy(p.positions[0]);ingest(c,p);p.positions.shift();advance(p);ingest(c,p);
 p.positions.unshift(x);advance(p);x.opened_at=p.heartbeat_at;p.fills.find(f=>f.id===x.entry_fill_id).at=p.heartbeat_at;
 const r=get(ingest(c,p));assert.equal(r.identityVerified,false);assert.equal(r.samples.length,0);assert.equal(r.entry,null);assert.equal(r.openedAt,null);assert.equal(r.cost,null);
});
test('REVIEW: same immutable fill cannot migrate into a different market',()=>{
 const p=report(),c=createPaperPositionCharts();ingest(c,p);advance(p);const x=p.positions[0],f=p.fills.find(f=>f.id===x.entry_fill_id);x.asset='AAVE/USD';f.asset=x.asset;x.opened_at=p.heartbeat_at;f.at=p.heartbeat_at;
 const r=get(ingest(c,p),'AAVE/USD');assert.equal(r.identityVerified,false);assert.equal(r.samples.length,0);
});
test('REVIEW: missing receipt recovery creates isolated points across unavailable interval',()=>{
 const p=report(),c=createPaperPositionCharts(),f=copy(p.fills.find(f=>f.id===p.positions[0].entry_fill_id));ingest(c,p);advance(p);p.fills=p.fills.filter(x=>x.id!==f.id);ingest(c,p);advance(p);p.fills.push(f);
 const r=get(ingest(c,p));assert.equal(r.identityVerified,true);assert.equal(r.samples.length,2);assert.equal(r.samples[1].breakBefore,true);assert.deepEqual(positionChartGeometry(r).segments.map(s=>s.length),[1,1]);
});
test('REVIEW: temporarily inconsistent cost/receipt recovery also interrupts continuity',()=>{
 const p=report(),c=createPaperPositionCharts(),cost=p.positions[0].cost_base;ingest(c,p);advance(p);p.positions[0].cost_base=cost+1;ingest(c,p);advance(p);p.positions[0].cost_base=cost;
 const r=get(ingest(c,p));assert.equal(r.samples.length,2);assert.deepEqual(positionChartGeometry(r).segments.map(s=>s.length),[1,1]);
});
test('immutable entry order cannot be reused by a different fill with a new timestamp',()=>{
 const p=report(),c=createPaperPositionCharts();ingest(c,p);advance(p);const x=p.positions[0],f=p.fills.find(f=>f.id===x.entry_fill_id);f.id+='-changed';x.entry_fill_id=f.id;f.at=p.heartbeat_at;x.opened_at=f.at;
 const r=get(ingest(c,p));assert.equal(r.identityVerified,false);assert.equal(r.samples.length,0);
});
test('a superseded old fill ID cannot be revived after newer genuine cycles',()=>{
 const p=report(),old=copy(p),c=createPaperPositionCharts();ingest(c,p);advance(p);reopen(p);ingest(c,p);advance(old,2000);const x=old.positions[0];x.opened_at=old.heartbeat_at;old.fills.find(f=>f.id===x.entry_fill_id).at=old.heartbeat_at;
 assert.equal(get(ingest(c,old)).identityVerified,false);
});
test('bounded immutable receipt registry fails closed rather than forgetting retired IDs',()=>{
 const p=report(),c=createPaperPositionCharts(),x=p.positions[0];p.positions=[x];p.fills=[p.fills.find(f=>f.id===x.entry_fill_id)];p.account.fills=1;
 for(let i=0;i<POSITION_RECEIPT_LIMIT;i++){if(i){advance(p);const f=p.fills[0];f.id='capacity-fill-'+i;f.order_id='capacity-order-'+i;f.at=p.heartbeat_at;x.opened_at=f.at;x.entry_fill_id=f.id;}assert.equal(get(ingest(c,p)).identityVerified,true);}
 advance(p);reopen(p);const r=get(ingest(c,p));assert.equal(r.identityVerified,false);assert.match(r.sampleReason,/capacity reached/);assert.equal(r.samples.length,0);
});
test('changed entry observation lineage interrupts the verified cycle',()=>{const p=report(),c=createPaperPositionCharts();ingest(c,p);advance(p);p.fills.find(f=>f.id===p.positions[0].entry_fill_id).observation_id='changed-observation';assert.equal(get(ingest(c,p)).identityVerified,false);});

test('REVIEW: advancing heartbeat preserves keyboard summary focus and sample-list scroll',()=>{
 const p=report(),d=dom(),c=createPaperPositionCharts();renderPaperPositionCharts(d.document,c,{report:p,connected:true,now:NOW});let details=find(d.nodes.paperPositionWindows.children[0],'details')[0];details.open=true;details.querySelector('summary').focus();details.querySelector('.position-sample-receipts').scrollTop=87;
 advance(p);renderPaperPositionCharts(d.document,c,{report:p,connected:true,now:NOW+1000});details=find(d.nodes.paperPositionWindows.children[0],'details')[0];assert.equal(details.open,true);assert.equal(d.document.activeElement,details.querySelector('summary'));assert.equal(details.querySelector('.position-sample-receipts').scrollTop,87);assert.deepEqual(d.document.activeElement.focusOptions,{preventScroll:true});
});
test('REVIEW: unknown/native entry identity uses unknown exit wording rather than asserting no matched exit',()=>{
 const p=native(report()),d=dom();p.fills=p.fills.filter(f=>f.id!==p.positions[0].entry_fill_id);renderPaperPositionCharts(d.document,createPaperPositionCharts(),{report:p,connected:true,now:NOW});for(const card of [d.nodes.paperPositionWindows.children[0],d.nodes.paperPositionWindows.children.at(-1)]){assert.match(textTree(card),/Unavailable: no verified entry-cycle or linked exit evidence/);assert.doesNotMatch(textTree(card),/No matched exit for this displayed open cycle/);}
});
test('REVIEW: linked exit evidence contradicting reported open holding is explicitly labelled',()=>{
 const p=report(),x=p.positions[0],d=dom();p.results.push({id:'contradictory-open-result',asset:x.asset,status:'settled',entry_fill_id:x.entry_fill_id,exit_fill_id:'missing-exit',closed_at:p.heartbeat_at,pnl_base:1,net_r:1});renderPaperPositionCharts(d.document,createPaperPositionCharts(),{report:p,connected:true,now:NOW});const card=d.nodes.paperPositionWindows.children[0];assert.match(textTree(card),/Linked exit evidence conflicts with this reported open holding/);assert.equal(find(card,'svg').length,0);
});
