import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHistory,validateHistoryRow,historyCsv} from './paper-history-v2.mjs';
const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-history-v2.json',import.meta.url)));
const page=({cursor,watermark,limit})=>fixture.rows.filter(r=>r.seq>cursor&&r.seq<=watermark).slice(0,limit);
test('all eight SQL history kinds validate and complete fixed-watermark export spans pages',async()=>{assert.equal(new Set(fixture.rows.map(r=>r.kind)).size,8);fixture.rows.forEach(validateHistoryRow);const requests=[],h=createHistory({fetchPage:async q=>{requests.push(q);return page(q);}});h.reset(fixture.watermark);await h.more();assert.equal(h.getState().rows.length,100);assert.equal(h.getState().complete,false);const csv=await h.exportAll();assert.equal(h.getState().rows.length,fixture.rows.length);assert.equal(h.getState().complete,true);assert.ok(requests.every(q=>q.watermark===fixture.watermark&&q.limit===100));assert.match(csv,/"fills"/);assert.match(csv,/"seq"/);});
test('legitimate sequence rollback gaps do not imply missing data',async()=>{const rows=[fixture.rows[0],{...fixture.rows[1],seq:10}],h=createHistory({fetchPage:async()=>rows});h.reset(10);await h.more();assert.equal(h.getState().complete,true);assert.equal(h.getState().rows.length,2);});
test('duplicate retries dedupe identical records but reject changed immutable rows',async()=>{let calls=0;const h=createHistory({fetchPage:async q=>{calls++;if(calls===1)return fixture.rows.slice(0,100);return [fixture.rows[99],...fixture.rows.slice(100)];}});h.reset(fixture.watermark);await h.more();await h.more();assert.equal(h.getState().rows.length,fixture.rows.length);const bad=createHistory({fetchPage:async q=>q.cursor===0?fixture.rows.slice(0,100):[{...fixture.rows[99],at:'2000-01-01T00:00:00Z'}]});bad.reset(fixture.watermark);await bad.more();await bad.more();assert.match(bad.getState().error,/incomplete/);assert.equal(bad.getState().rows.length,100);});
test('network failure keeps cursor and loaded rows; retry resumes exactly',async()=>{let fail=true;const h=createHistory({fetchPage:async q=>{if(q.cursor&&fail){fail=false;throw Error('network');}return page(q);}});h.reset(fixture.watermark);await h.more();const cursor=h.getState().cursor;await assert.rejects(h.exportAll());assert.equal(h.getState().cursor,cursor);assert.equal(h.getState().rows.length,100);await h.exportAll();assert.equal(h.getState().complete,true);});
test('empty premature page cannot be called complete or exported partially',async()=>{const h=createHistory({fetchPage:async()=>[]});h.reset(100);await assert.rejects(h.exportAll());assert.equal(h.getState().complete,false);});
test('history strips unknown outer identity and rejects payload identity/objects',()=>{const r=validateHistoryRow({...fixture.rows[0],owner_id:'synthetic-private-marker'});assert.equal(r.owner_id,undefined);assert.doesNotMatch(JSON.stringify(r),/synthetic-private-marker/);assert.throws(()=>validateHistoryRow({...fixture.rows[0],payload:{...fixture.rows[0].payload,owner_id:'synthetic-private-marker'}}));assert.throws(()=>validateHistoryRow({...fixture.rows[0],payload:{...fixture.rows[0].payload,reason:{nested:'identity'}}}));});
test('complete history CSV escapes formula strings in real projected fields',()=>{const r=structuredClone(fixture.rows.find(r=>r.kind==='decisions'));r.payload.reason='=HYPERLINK("malicious")';assert.match(historyCsv([r]),/"'=HYPERLINK\(""malicious""\)"/);});
test('rapid More clicks coalesce and reset invalidates late responses',async()=>{let resolve,calls=0;const h=createHistory({fetchPage:()=>{calls++;return new Promise(r=>{resolve=r;});}});h.reset(fixture.watermark);const first=h.more();await h.more();assert.equal(calls,1);h.reset(0);resolve(fixture.rows.slice(0,100));await first;assert.equal(h.getState().rows.length,0);assert.equal(h.getState().complete,true);});

test('order event transitions reject unknown status labels',()=>{const r=structuredClone(fixture.rows.find(r=>r.kind==='order_events'));r.payload.status='pretend_executed';assert.throws(()=>validateHistoryRow(r));});
