import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import {createPaperCueBridge,isVerifiedCue}from'./paper-eye-cues.mjs?v=neptune-v2-20261009-r8';import {validateV2}from'./status-v2.mjs?v=neptune-v2-20261009-r8';
const now=Date.parse('2026-10-09T10:32:00Z'),at=new Date(now).toISOString(),fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-running-v2.json',import.meta.url)));
function report(){const p=structuredClone(fixture);p.heartbeat_at=at;return p;}
function changed(p){p=structuredClone(p);p.fills[0].id='new-receipt';p.fills[0].at=at;return p;}
test('first real snapshot seeds without replaying previous buys',()=>{const b=createPaperCueBridge();b.observe(changed(report()),now);assert.equal(b.current(now),null);assert.ok(b.snapshot().seeded);});
test('only newly validated actual fill creates simulated buy cue',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);b.observe(changed(p),now);const cue=b.current(now);assert.equal(cue.kind,'buy');assert.equal(cue.asset,p.fills[0].asset);assert.ok(isVerifiedCue(cue,now));assert.ok(Object.isFrozen(cue));assert.equal(b.current(now+2600),null);});
test('verified protective sell may be shown while settlement is pending',()=>{const p=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-unsettled-v2.json',import.meta.url)));p.heartbeat_at=at;const b=createPaperCueBridge();b.observe(p,now);const f=p.fills.find(f=>f.side==='sell');assert.ok(f);f.id='new-protective-sell';f.at=at;b.observe(p,now);assert.equal(b.current(now).kind,'sell');});
test('decision intent can only yield review, never pretend execution or qualification',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);p.decisions[0].id='new-decision';p.decisions[0].at=at;p.decisions[0].action='buy';b.observe(p,now);assert.equal(b.current(now).kind,'review');});
test('faked or inconsistent account event fails existing authoritative schema',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);const bad=changed(p);bad.fills[0].fee_usd=0;assert.throws(()=>b.observe(bad,now));assert.equal(b.current(now),null);assert.equal(isVerifiedCue({kind:'buy',asset:'ETH/USD',createdAt:now,until:now+2600},now),false);});
test('stale heartbeat, stale events and future events cannot create cue',()=>{for(const variant of['heartbeat','stale','future']){const b=createPaperCueBridge(),p=report();b.observe(p,now);const q=changed(p);if(variant==='heartbeat')q.heartbeat_at=new Date(now-100000).toISOString();if(variant==='stale')q.fills[0].at=new Date(now-100000).toISOString();if(variant==='future')q.fills[0].at=new Date(now+1000).toISOString();b.observe(q,now);assert.equal(b.current(now),null);}});
test('poll repeats do not re-ignite cue or extend its expiry',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);const q=changed(p);b.observe(q,now);b.observe(q,now+2000);assert.equal(b.current(now+2600),null);});
test('fill takes precedence over simultaneous decision review',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);const q=changed(p);q.decisions[0].id='new-review';q.decisions[0].at=at;b.observe(q,now);assert.equal(b.current(now).kind,'buy');});
test('dedupe resource remains bounded and disconnect clears current cue',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);for(let i=0;i<400;i++){const q=changed(p);q.fills[0].id='fill-'+i;b.observe(q,now+i);}assert.ok(b.snapshot().seenCount<=256);b.disconnect();assert.equal(b.current(now+500),null);});
test('unknown market and real-money envelope cannot create trusted cue',()=>{for(const mutate of[p=>p.mode='LIVE',p=>p.fills[0].asset='BTC/USD']){const b=createPaperCueBridge(),p=report();b.observe(p,now);const q=changed(p);mutate(q);assert.throws(()=>b.observe(q,now));assert.equal(b.current(now),null);}});
test('reconnect snapshot rebaselines instead of replaying missed history',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);b.disconnect();b.observe(changed(p),now+1000);assert.equal(b.current(now+1000),null);});
test('out-of-order earlier report cannot flash a superseded event',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);const newer=structuredClone(p);newer.heartbeat_at=new Date(now+1000).toISOString();b.observe(newer,now+1000);const older=changed(p);b.observe(older,now+1500);assert.equal(b.current(now+1500),null);});
test('stale-to-fresh transition rebaselines without historical fill animation',()=>{const b=createPaperCueBridge(),p=report();p.heartbeat_at=new Date(now-200000).toISOString();b.observe(p,now);const q=changed(report());b.observe(q,now);assert.equal(b.current(now),null);});
test('companions only pulse matched verified role receipts',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);const q=changed(p);b.observe(q,now);assert.equal(b.current(now).role,'Trades');const d=report(),c=createPaperCueBridge();c.observe(d,now);d.decisions[0].id='blocked-hold';d.decisions[0].at=at;d.decisions[0].action='hold';d.decisions[0].result='blocked';c.observe(d,now);assert.equal(c.current(now).role,'Risk');const r=report(),s=createPaperCueBridge();s.observe(r,now);r.decisions[0].id='normal-hold';r.decisions[0].at=at;r.decisions[0].action='hold';r.decisions[0].result='no_trade';r.scan_complete=false;s.observe(r,now);assert.equal(s.current(now).role,null);});
test('absent null feed rebaselines next valid snapshot just like reconnect',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);b.observe(null,now+500);assert.equal(b.snapshot().seeded,false);b.observe(changed(p),now+1000);assert.equal(b.current(now+1000),null);});
