import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import {createPaperCueBridge,isVerifiedCue}from'./paper-eye-cues.mjs?v=neptune-v2-20261009-r9';import {validateV2}from'./status-v2.mjs?v=neptune-v2-20261009-r9';
const now=Date.parse('2026-10-09T10:32:00Z'),at=new Date(now).toISOString(),fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-running-v2.json',import.meta.url)));
function report(){const p=structuredClone(fixture);p.heartbeat_at=at;return p;}
function changed(p){p=structuredClone(p);p.fills[0].id='new-receipt';p.fills[0].at=at;return p;}
test('first real snapshot seeds without replaying previous buys',()=>{const b=createPaperCueBridge();b.observe(changed(report()),now);assert.equal(b.current(now),null);assert.ok(b.snapshot().seeded);});
test('only newly validated actual fill creates simulated buy cue',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);b.observe(changed(p),now);const cue=b.current(now);assert.equal(cue.kind,'buy');assert.equal(cue.asset,p.fills[0].asset);assert.ok(isVerifiedCue(cue,now));assert.ok(Object.isFrozen(cue));assert.equal(b.current(now+2600),null);});
test('verified protective sell may be shown while settlement is pending',()=>{const p=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-unsettled-v2.json',import.meta.url)));p.heartbeat_at=at;const b=createPaperCueBridge();b.observe(p,now);const f=p.fills.find(f=>f.side==='sell');assert.ok(f);f.id='new-protective-sell';f.at=at;b.observe(p,now);assert.equal(b.current(now).kind,'sell');});
test('decision intent can only yield review, never pretend execution or qualification',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);p.decisions[0].id='new-decision';p.decisions[0].at=at;p.decisions[0].action='buy';b.observe(p,now);assert.equal(b.current(now).kind,'review');});
test('faked or inconsistent account event fails existing authoritative schema',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);const bad=changed(p);bad.fills[0].fee_usd=0;assert.throws(()=>b.observe(bad,now));assert.equal(b.current(now),null);assert.equal(isVerifiedCue({kind:'buy',asset:'ETH/USD',createdAt:now,until:now+2600},now),false);});
test('stale heartbeat, stale events and future events cannot create cue',()=>{for(const variant of['heartbeat','stale','future']){const b=createPaperCueBridge(),p=report();b.observe(p,now);const q=changed(p);if(variant==='heartbeat')q.heartbeat_at=new Date(now-100000).toISOString();if(variant==='stale')q.fills[0].at=new Date(now-100000).toISOString();if(variant==='future')q.fills[0].at=new Date(now+1000).toISOString();b.observe(q,now);assert.equal(b.current(now),null);}});
test('poll repeats do not re-ignite cue or extend its expiry',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);const q=changed(p);b.observe(q,now);b.observe(q,now+2000);assert.equal(b.current(now+2600),null);});
test('fill takes precedence over simultaneous decision review',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);const q=changed(p);q.decisions[0].id='new-review';q.decisions[0].at=at;b.observe(q,now);assert.equal(b.current(now).kind,'buy');});
test('dedupe resource remains bounded and disconnect clears current cue',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);for(let i=0;i<400;i++){const q=changed(p);q.fills[0].id='fill-'+i;b.observe(q,now+i);}assert.ok(b.snapshot().seenCount<=256);b.disconnect();assert.equal(b.current(now+500),null);});
test('unknown market and real-money envelope cannot create trusted cue',()=>{for(const mutate of[p=>p.mode='LIVE',p=>p.fills[0].asset='BTC/USD']){const b=createPaperCueBridge(),p=report();b.observe(p,now);const q=changed(p);mutate(q);assert.throws(()=>b.observe(q,now));assert.equal(b.current(now),null);}});
test('reconnect snapshot rebaselines instead of replaying missed history',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);b.disconnect();b.observe(changed(p),now+1000);assert.equal(b.current(now+1000),null);});
test('out-of-order earlier report cannot flash a superseded event',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);const newer=structuredClone(p);newer.heartbeat_at=new Date(now+1000).toISOString();b.observe(newer,now+1000);const older=changed(p);b.observe(older,now+1500);assert.equal(b.current(now+1500),null);});
test('stale-to-fresh transition rebaselines without historical fill animation',()=>{const b=createPaperCueBridge(),p=report();p.heartbeat_at=new Date(now-200000).toISOString();b.observe(p,now);const q=changed(report());b.observe(q,now);assert.equal(b.current(now),null);});
test('companions only pulse matched verified role receipts',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);const q=changed(p);b.observe(q,now);assert.equal(b.current(now).role,'Trades');const d=report(),c=createPaperCueBridge();c.observe(d,now);d.decisions[0].id='blocked-hold';d.decisions[0].at=at;d.decisions[0].action='hold';d.decisions[0].result='blocked';c.observe(d,now);assert.equal(c.current(now).role,'Risk');const r=report(),s=createPaperCueBridge();s.observe(r,now);r.decisions[0].id='normal-hold';r.decisions[0].at=at;r.decisions[0].action='hold';r.decisions[0].result='no_trade';r.scan_complete=false;s.observe(r,now);assert.equal(s.current(now).role,null);});
test('absent null feed rebaselines next valid snapshot just like reconnect',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);b.observe(null,now+500);assert.equal(b.snapshot().seeded,false);b.observe(changed(p),now+1000);assert.equal(b.current(now+1000),null);});
function burst(count){const p=report(),template=p.fills[0];p.fills=Array.from({length:count},(_,i)=>({...template,id:'burst-'+String(i).padStart(2,'0'),at:new Date(now-100+ i).toISOString()}));p.account.fills=Math.max(p.account.fills,count);return p;}
test('fresh receipt bursts are FIFO bounded to eight including current and expire within six seconds',()=>{const b=createPaperCueBridge();b.observe(report(),now);const p=burst(12);b.observe(p,now);assert.equal(b.snapshot().queued,7);const ids=[];for(let dt=0;dt<6000;dt+=900){const c=b.current(now+dt);if(c)ids.push(c.eventId);}assert.deepEqual(ids,['burst-00','burst-01','burst-02','burst-03','burst-04','burst-05','burst-06']);assert.equal(b.current(now+6000),null);b.observe(p,now+6100);assert.equal(b.current(now+6100),null);});
test('queued receipts are copied at validation boundary and cannot be changed by caller',()=>{const b=createPaperCueBridge();b.observe(report(),now);const p=burst(2);b.observe(p,now);p.fills[1].asset='BTC/USD';p.fills[1].id='forged';const next=b.current(now+900);assert.equal(next.eventId,'burst-01');assert.notEqual(next.asset,'BTC/USD');});
test('fills preempt review cues, preserve fill FIFO and discard lower priority simultaneous reviews',()=>{const b=createPaperCueBridge(),p=report();b.observe(p,now);p.decisions[0].id='review-first';p.decisions[0].at=at;b.observe(p,now);assert.equal(b.current(now).kind,'review');const q=burst(2);q.decisions[0].id='review-next';q.decisions[0].at=at;b.observe(q,now+1);assert.equal(b.current(now+1).eventId,'burst-00');assert.equal(b.current(now+901).eventId,'burst-01');assert.equal(b.current(now+1801),null);});
test('pause or reduced motion drops queue and reactivation baselines without replay',()=>{const b=createPaperCueBridge();b.observe(report(),now);b.observe(burst(3),now);b.setActive(false);assert.equal(b.current(now+1),null);assert.equal(b.snapshot().queued,0);b.observe(burst(4),now+100);b.setActive(true);b.observe(burst(5),now+200);assert.equal(b.current(now+200),null);});
test('close/reopen, stale report and older heartbeat cannot replay a pending burst',()=>{for(const reset of [b=>b.disconnect(),b=>b.observe(null,now+1),b=>{const p=report();p.heartbeat_at=new Date(now+100000).toISOString();b.observe(p,now+1);}]){const b=createPaperCueBridge();b.observe(report(),now);b.observe(burst(3),now);reset(b);b.observe(burst(4),now+100);assert.equal(b.current(now+100),null);}const b=createPaperCueBridge(),p=report();p.heartbeat_at=new Date(now+1000).toISOString();b.observe(p,now+1000);b.observe(burst(3),now+1100);assert.equal(b.current(now+1100),null);});
test('delayed hidden backlog and receipt TTL cannot start an old cue',()=>{const b=createPaperCueBridge();b.observe(report(),now);b.observe(burst(3),now);assert.equal(b.current(now+10000),null);const c=createPaperCueBridge();c.observe(report(),now);const p=burst(2);p.fills[1].at=new Date(now-89900).toISOString();p.fills[0].at=new Date(now-89901).toISOString();c.observe(p,now);assert.equal(c.current(now+901),null);});
