import test from 'node:test';import assert from 'node:assert/strict';import {readPortfolioSnapshot} from './portfolio-snapshot.mjs';
const now=Date.parse('2026-10-09T13:00:00Z'),at=new Date(now).toISOString(),old=new Date(now-90001).toISOString();
const report=()=>({currency:'AUD',status:'data_stale',heartbeat_at:at,quote_at:null,scan_complete:false,positions:[],account:{initial_cash:10000,cash:10000,equity:10000,unsettled_usd:0,valuation_at:at}});
test('fresh flat account remains visible despite incomplete global market screen',()=>{assert.deepEqual(readPortfolioSnapshot(report(),true,now),{cash:10000,equity:10000,exposure:0,cashCurrent:true,valuationCurrent:true});});
test('stopped engine can have a current verified ledger and flat valuation',()=>{const p=report();p.status='stopped';assert.equal(readPortfolioSnapshot(p,true,now).equity,10000);});
test('stale or absent valuation hides equity/exposure but keeps fresh settled cash',()=>{for(const at of [null,old,new Date(now+1).toISOString()]){const p=report();p.account.valuation_at=at;const r=readPortfolioSnapshot(p,true,now);assert.equal(r.cash,10000);assert.equal(r.equity,null);assert.equal(r.exposure,null);}});
test('offline or stale/future heartbeat blanks all current numbers',()=>{assert.equal(readPortfolioSnapshot(report(),false,now).cash,null);for(const at of [null,old,new Date(now+1).toISOString()]){const p=report();p.heartbeat_at=at;const r=readPortfolioSnapshot(p,true,now);assert.equal(r.cash,null);assert.equal(r.equity,null);}});
test('held positions require fresh own marks independently of global quotes',()=>{const p=report();p.account.cash=9500;p.positions=[{qty:1,last_bid:500,quote_at:at}];assert.equal(readPortfolioSnapshot(p,true,now).exposure,500);for(const quote_at of [null,old,new Date(now+1).toISOString()]){p.positions[0].quote_at=quote_at;const r=readPortfolioSnapshot(p,true,now);assert.equal(r.cash,9500);assert.equal(r.equity,null);}});
test('unknown held bid, unsettled USD, and inconsistent flat equity hide valuation',()=>{for(const mutate of [p=>p.account.unsettled_usd=10,p=>p.account.equity=10001,p=>p.positions=null,p=>p.positions=[{qty:1,last_bid:null,quote_at:at}]]){const p=report();mutate(p);assert.equal(readPortfolioSnapshot(p,true,now).equity,null);assert.equal(readPortfolioSnapshot(p,true,now).cash,10000);}});
