import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createPaperCueBridge} from './paper-eye-cues.mjs?v=neptune-native-20261009';
import {choreography} from './character-motion.mjs?v=neptune-native-20261009';
import {createLaserAudio,LASER_LIMITS} from './laser-audio.mjs?v=neptune-native-20261009';
const now=Date.parse('2026-10-09T12:00:00Z'),iso=t=>new Date(t).toISOString();
function base(){const p=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-running-v2.json',import.meta.url)));p.heartbeat_at=iso(now);p.decisions=[];p.results=[];p.settlements=[];p.positions=[];p.fills=[fill('buy',100,now-10000)];p.account.fills=1;return p;}
function fill(side,price,at){const gross=price,fee=gross*.008,net=side==='buy'?-gross-fee:gross-fee,fx=1.5,applied=fx*(side==='buy'?1.0025:.9975);return{id:side,order_id:side,decision_id:side,observation_id:side,at:iso(at),asset:'ETH/USD',side,qty:1,price,quote_currency:'USD',slippage_pct:.25,gross_usd:gross,fee_usd:fee,net_usd:net,settlement_status:'settled',fx,fx_source:'Frankfurter ECB reference',fx_at:iso(at),fx_rate_date:'2026-10-09',fx_retrieved_at:iso(at),fx_applied_rate:applied,fx_cost_base:Math.abs(net)*Math.abs(applied-fx),gross_base:gross*fx,fee_base:fee*fx,cash_delta_base:net*applied};}
function close(p,{price=110,at=now+1000,pending=false}={}){const x=fill('sell',price,at);p.heartbeat_at=iso(at);p.fills.push(x);p.account.fills=2;const pnl=x.cash_delta_base+p.fills[0].cash_delta_base;p.results=[{id:'result',asset:'ETH/USD',entry_fill_id:'buy',exit_fill_id:'sell',closed_at:iso(at),status:pending?'pending_conversion':'settled',pnl_base:pending?null:pnl,net_r:null}];if(pending){x.settlement_status='pending_conversion';for(const k of ['fx','fx_source','fx_at','fx_rate_date','fx_retrieved_at','fx_applied_rate','fx_cost_base','gross_base','fee_base','cash_delta_base'])x[k]=null;}return p;}
function settle(p,at=now+2000){const f=p.fills[1],fx=1.5,applied=fx*.9975,cash=f.net_usd*applied;p.heartbeat_at=iso(at);p.settlements=[{id:'settlement',exit_fill_id:f.id,at:iso(at),usd_amount:f.net_usd,fx,fx_source:'Frankfurter ECB reference',fx_at:iso(at),fx_rate_date:'2026-10-09',fx_retrieved_at:iso(at),fx_applied_rate:applied,fx_cost_base:f.net_usd*(fx-applied),cash_delta_base:cash,pnl_base:cash+p.fills[0].cash_delta_base}];return p;}
test('net settled simulated sale yields one trusted profit cue and varied planted victory frames',()=>{const p=base(),b=createPaperCueBridge();b.observe(p,now);b.observe(close(p),now+1000);const c=b.current(now+1000);assert.equal(c.kind,'profit');assert.ok(c.pnl_base>0);const a=choreography(2,1200,800,{cue:c,eventId:c.eventId,now:now+1200});assert.equal(a.kind,'victory');assert.equal(a.fire,false);assert.ok(a.feet.every(f=>f.y===a.ground));assert.notEqual(choreography(2,1200,800,{reduced:true,cue:c}).kind,'victory');b.observe(p,now+1100);assert.equal(b.current(now+7000),null);});
test('gross-positive losing sale, zero, unknown or contradictory result, missing entry and wrong quantity never celebrate',()=>{for(const mutate of[p=>{p.results[0].pnl_base=null;},p=>{p.results[0].pnl_base=999;},p=>{p.fills.shift();},p=>{p.results[0].entry_fill_id='missing';},p=>{p.results[0].closed_at=iso(now);},p=>{const f=p.fills[0];f.qty=2;f.price=50;},p=>{p.results[0].pnl_base=0;},p=>{p.results[0].status='pending_conversion';p.results[0].pnl_base=null;}]){const p=base(),b=createPaperCueBridge();b.observe(p,now);close(p);mutate(p);try{b.observe(p,now+1000);}catch{}assert.notEqual(b.current(now+1000)?.kind,'profit');}const p=base(),b=createPaperCueBridge();b.observe(p,now);close(p,{price:101});assert.ok(p.fills[1].price>p.fills[0].price);assert.ok(p.results[0].pnl_base<0);b.observe(p,now+1000);assert.notEqual(b.current(now+1000)?.kind,'profit');});
test('pending FX sale only celebrates fresh matching final settlement, once',()=>{const p=base(),b=createPaperCueBridge();b.observe(p,now);b.observe(close(p,{pending:true}),now+1000);assert.equal(b.current(now+1000).kind,'sell');b.observe(settle(p),now+2000);assert.equal(b.current(now+2000).kind,'profit');b.observe(p,now+2100);assert.equal(b.current(now+7000),null);});
test('reload, disconnect, hidden pause, stale and future settlements cannot replay',()=>{for(const reset of[b=>b.disconnect(),b=>{b.setActive(false);b.setActive(true);},b=>b.observe(null,now+1500)]){const p=close(base(),{pending:true}),b=createPaperCueBridge();b.observe(p,now+1000);reset(b);b.observe(settle(p),now+2000);assert.equal(b.current(now+2000),null);}const p=settle(close(base(),{pending:true})),b=createPaperCueBridge();b.observe(p,now+2000);assert.equal(b.current(now+2000),null);for(const at of[now-100000,now+5000]){const q=base(),c=createPaperCueBridge();c.observe(q,now);close(q,{pending:true});settle(q,at);try{c.observe(q,now+2000);}catch{}assert.notEqual(c.current(now+2000)?.kind,'profit');}});
test('historical backfill, changed result IDs, repeat receipt and expired backlog do not repeat profit',()=>{const p=base(),b=createPaperCueBridge();b.observe(p,now);b.observe(close(p),now+1000);b.current(now+8000);p.results[0].id='changed';b.observe(p,now+8000);assert.notEqual(b.current(now+8000)?.kind,'profit');const c=createPaperCueBridge();c.observe(base(),now+2000);c.observe(p,now+2000);assert.notEqual(c.current(now+2000)?.kind,'profit');});
function audio(){let enabled=true,time=0;const events=[],ctx={state:'running',currentTime:0,destination:{},createOscillator(){return{frequency:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(g){return g;},start(){events.push('start');},stop(){events.push('stop');},disconnect(){}};},createGain(){return{gain:{setValueAtTime(){},linearRampToValueAtTime(v){assert.ok(v<=.055);},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}};}};const a=createLaserAudio({getContext:()=>ctx,canPlay:()=>enabled,clock:()=>time});return{a,ctx,events,setEnabled:v=>enabled=v,setTime:v=>time=v};}
test('laser audio only follows visible beam edges, bounded volume and rate, never starts context',()=>{const {a,ctx,events,setTime}=audio();assert.equal(a.observe({beamCount:0}),false);ctx.state='suspended';assert.equal(a.observe({beamCount:2,beamKey:'one'}),false);ctx.state='running';a.observe({beamCount:0});assert.equal(a.observe({beamCount:2,beamKey:'one'}),true);assert.equal(a.observe({beamCount:2,beamKey:'one'}),false);setTime(100);assert.equal(a.observe({beamCount:2,beamKey:'two'}),false);setTime(LASER_LIMITS.gapMs);assert.equal(a.observe({beamCount:2,beamKey:'three'}),true);assert.equal(events.filter(x=>x==='start').length,2);});
test('mute, hidden or reduced-motion gate stops sound and cannot queue replay',()=>{const {a,events,setEnabled,setTime}=audio();a.observe({beamCount:2,beamKey:'one'});setEnabled(false);assert.equal(a.observe({beamCount:2,beamKey:'two'}),false);assert.equal(a.snapshot().playing,0);setTime(2000);setEnabled(true);assert.equal(a.observe({beamCount:0}),false);assert.equal(events.filter(x=>x==='start').length,1);});

test('duplicate result aliases sharing one exit do not create two profit cues',()=>{const p=base(),b=createPaperCueBridge();b.observe(p,now);close(p);p.results.push({...p.results[0],id:'alias'});b.observe(p,now+1000);assert.equal(b.current(now+1000).kind,'profit');assert.notEqual(b.current(now+3400)?.kind,'profit');});

test('tiny partial lot cannot pass a fixed absolute quantity tolerance',()=>{const p=base(),b=createPaperCueBridge();p.fills[0].qty=1e-10;p.fills[0].price=1e12;b.observe(p,now);close(p);p.fills[1].qty=1e-12;p.fills[1].price=110e12;b.observe(p,now+1000);assert.notEqual(b.current(now+1000)?.kind,'profit');});
