import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {progressView,renderProgressWindow,PROGRESS_WINDOW_MS} from './progress-window.mjs?v=experiment-provenance-v3-r2';
const pending=JSON.parse(fs.readFileSync(new URL('./fixtures/pending-v2.json',import.meta.url)));
const now=Date.parse('2026-10-10T10:00:00Z'),at=new Date(now).toISOString(),iso=n=>new Date(n).toISOString();
function report(){return {...structuredClone(pending),currency:'AUD',risk:{...pending.risk,entry_paused:false},status:'running',heartbeat_at:at,quote_at:at,scan_at:at,scan_complete:true,message:'Nothing to report',account:{initial_cash:10000,cash:10000,equity:10000,realized_pnl:0,unrealized_pnl:0,fees:0,fills:0},native_paper:{version:1,mode:'PAPER',observed_at:at,valuation_at:at,valuation_complete:true,history_complete:false,positions:[],pending_quote_balances:[],recent_fills:[]}};}
function sell(id='sell1',when=at){return {id,order_id:'order1',decision_id:'decision1',observation_id:'observation2',at:when,asset:'ETH/USD',side:'sell',qty:1,price:2000,quote_currency:'USD',settlement_status:'pending_conversion',gross_usd:2000,fee_usd:16,net_usd:1984,fx:null,fx_source:null,fx_at:null,fx_rate_date:null,fx_retrieved_at:null,fx_applied_rate:null,gross_base:null,fee_base:null,fx_cost_base:null,cash_delta_base:null,slippage_pct:.25};}
function buy(id='buy1',when=at){return {id,asset:'binance:SOLUSDT',venue:'binance',side:'buy',quote_currency:'USDT',gross_qty:.123,fee_qty:.000123,fee_quote:0,fee_currency:'SOL',net_inventory_delta:.122877,net_quote_delta:-300,cash_delta_base:-450,fee_base:.45,fx_cost_base:1,position_status:'open',settlement_status:'settled',at:when};}
const view=(p,extra={})=>progressView({report:p,connected:true,now,...extra});
test('missing, invalid and uncreated reports mean unknown, never zero trades',()=>{for(const p of [null,{},pending]){const v=view(p);assert.match(v.headline,/unknown/);assert.equal(v.fills.length,0);assert.doesNotMatch(v.headline,/0|No buys/);}});
test('only completed fill records count; fresh prices and filled decisions cannot create a trade',()=>{const p=report();p.decisions=[{id:'d',at,asset:'ETH/USD',action:'buy',price:2000,quote_currency:'USD',reason:'later_observation_entry',source:'Kraken public spot',observation_id:'o',risk_base:null,stop:null,target:null,invalidation:null,confidence:'unvalidated',result:'filled'}];const v=view(p);assert.equal(v.fills.length,0);assert.equal(v.headline,'No buys or sells in received data');assert.match(v.details.join(' '),/Some records may be missing/);});
test('received legacy sell and native buy are counted once with time and venue',()=>{const p=report();p.fills=[sell()];p.native_paper.recent_fills=[buy()];p.account.fills=2;const v=view(p);assert.equal(v.headline,'1 paper buy · 1 sell seen');assert.equal(v.fills.length,2);assert.match(v.fills.join(' '),/Kraken ETH\/USD/);assert.match(v.fills.join(' '),/Binance SOL\/USDT/);assert.match(v.fills.join(' '),/waiting to convert proceeds to AUD/);assert.match(v.observed,/18:00:00 Perth/);assert.doesNotMatch(JSON.stringify(v),/10000|1984|cash_delta/);});
test('15 minute cutoff is strict and future or post-report fills fail closed',()=>{const p=report();p.fills=[sell('boundary',iso(now-PROGRESS_WINDOW_MS)),sell('within',iso(now-PROGRESS_WINDOW_MS+1))];p.account.fills=2;assert.equal(view(p).fills.length,1);for(const when of [iso(now+1),iso(now+10000)]){p.fills=[sell('future',when)];assert.equal(view(p).fills.length,0);assert.equal(view(p).state,'PARTIAL');}});
test('future and malformed report time cannot appear fresh',()=>{for(const value of [iso(now+1),'not-a-time','2026-02-30T00:00:00Z',null]){const p=report();p.heartbeat_at=value;const v=view(p);assert.match(v.headline,/unknown/);assert.equal(v.fills.length,0);}});
test('repeated refreshes retain the report timestamp and later become stale',()=>{const p=report(),first=view(p),second=view(p,{now:now+1000}),stale=view(p,{now:now+90001});assert.equal(first.state,'OBSERVED');assert.equal(second.state,'OBSERVED');assert.match(second.observed,/18:00:00 Perth · 1s ago/);assert.equal(stale.state,'STALE');assert.match(stale.headline,/unknown/);assert.match(stale.details.join(' '),/This report is old/);});
test('offline report cannot claim current trades, even while cached receipts remain visible',()=>{const p=report();p.fills=[sell()];p.account.fills=1;const v=view(p,{connected:false});assert.equal(v.state,'OFFLINE');assert.equal(v.fills.length,1);assert.match(v.details.join(' '),/connection is down/);});
test('missing, stale or malformed native records are disclosed as partial',()=>{for(const mutate of [p=>delete p.native_paper,p=>p.native_paper.observed_at=iso(now-90001),p=>p.native_paper.mode='LIVE',p=>p.native_paper.observed_at=iso(now+1)]){const p=report();mutate(p);const v=view(p);assert.equal(v.state,'PARTIAL');assert.match(v.headline,/some data missing/);assert.match(v.details.join(' '),/cannot say that no trades happened/);}});
test('native partial exits and pending conversion do not claim full exit or profit',()=>{const p=report();p.native_paper.recent_fills=[{...buy(),side:'sell',fee_qty:0,fee_quote:.5,fee_currency:'USDT',net_inventory_delta:-.123,net_quote_delta:399.5,cash_delta_base:null,fee_base:null,fx_cost_base:null,position_status:'open',settlement_status:'pending_native_conversion'}];p.account.fills=1;const v=view(p);assert.match(v.fills[0],/sold part; some coins remain/);assert.match(v.fills[0],/waiting to convert proceeds to AUD/);assert.doesNotMatch(v.fills[0],/profit|closed/);});
test('duplicate or contradictory receipts do not create multiple counted trades',()=>{const p=report();p.fills=[sell(),sell()];p.account.fills=2;assert.match(view(p).headline,/unknown/);const n=report();n.native_paper.recent_fills=[buy(),buy()];n.account.fills=2;assert.equal(view(n).state,'PARTIAL');assert.equal(view(n).fills.length,0);});
test('known waiting reasons use simple prose and incomplete checks remain explicit',()=>{const p=report();const record={key:'kraken:string:d1',at,asset:'ETH/USD',action:'hold',result:'blocked',reason:'spread_too_wide',source:'Kraken paper decision'};const v=view(p,{marketSnapshot:{connected:true,nativeStatus:'ready',records:[record],latestAt:at}});assert.match(v.details.join(' '),/gap between buy and sell prices was too big/);assert.match(v.details.join(' '),/only part of the check history/);assert.doesNotMatch(v.details.join(' '),/spread_too_wide/);});
test('unknown decision reasons stay unknown; forged scout snapshots are ignored',()=>{const p=report();const record={key:'kraken:string:d1',at,asset:'ETH/USD',action:'hold',result:'blocked',reason:null,source:'Kraken paper decision'};const v=view(p,{marketSnapshot:{connected:true,nativeStatus:'ready',records:[record],latestAt:at},scoutSnapshot:{feed:{run:{completed_at:at}},status:'ready',records:[]}});assert.match(v.details.join(' '),/reason not explained/);assert.doesNotMatch(v.details.join(' '),/Public research/);});
test('rendering uses textContent only and unchanged fill list is not rebuilt',()=>{const ids=Object.fromEntries(['progressState','progressHeadline','progressObserved','progressDetails','progressFills'].map(id=>[id,{textContent:'',dataset:{},calls:0,replaceChildren(...rows){this.calls++;this.rows=rows;}}]));const document={getElementById:id=>ids[id],createElement:()=>({textContent:'',set innerHTML(v){throw Error('unsafe HTML');}})};renderProgressWindow(document,{report:report(),connected:true,now});renderProgressWindow(document,{report:report(),connected:true,now:now+1000});assert.equal(ids.progressFills.calls,1);assert.match(ids.progressDetails.textContent,/Chat updates are separate/);assert.match(ids.progressObserved.textContent,/1s ago/);});
test('summary module has no network, storage, financial mutation or event-dispatch path',()=>{const source=fs.readFileSync(new URL('./progress-window.mjs?v=experiment-provenance-v3-r2',import.meta.url),'utf8');assert.doesNotMatch(source,/fetch\(|setInterval\(|setTimeout\(|localStorage|sessionStorage|dispatchEvent\(|innerHTML|insertAdjacentHTML|apikey|publicKey|POST|PATCH|DELETE/);});
test('summary and activity controls stay inside existing terminal and preserve native font inheritance',()=>{const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8'),css=fs.readFileSync(new URL('./team-work.css',import.meta.url),'utf8');assert.match(html,/class="team-console"><button id="openProgress"/);assert.match(css,/\.progress-window\{[^}]*font:inherit/);assert.match(css,/\.progress-window\{grid-column:2;grid-row:1;max-height:32px/);assert.match(html,/id="pauseTeamActivity" aria-pressed="false"/);assert.match(css,/\.team-terminal\[data-view=market\] \.team-source\{grid-column:1;grid-row:1/);assert.match(css,/\.team-terminal\[data-view=market\] \.progress-window\{grid-column:2;grid-row:1/);const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);});

test('ChatGPT link uses the exact user-supplied dots home destination without private identifiers',()=>{const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');assert.match(html,/<a id="openSeaChat" href="https:\/\/chatgpt.com\/dots\/home" target="_blank" rel="noopener noreferrer" aria-label="Open sea in ChatGPT\. Opens dots home; select sea if needed"/);assert.match(html,/>Open sea in ChatGPT<\/a>/);assert.doesNotMatch(html,/chatgpt.com\/dots\/home[?#]/);assert.ok(html.indexOf('id="openSeaChat"')>html.indexOf('id="about"'));assert.match(html,/Open sea in ChatGPT<\/a><\/div><\/footer>/);});
test('short narrow and zoomed viewports do not inherit the 215px summary minimum',()=>{const css=fs.readFileSync(new URL('./team-work.css',import.meta.url),'utf8'),fallback=css.slice(css.indexOf('@media(max-width:539px) and (max-height:500px)'));assert.match(fallback,/grid-template-columns:auto minmax\(0,1fr\)/);assert.match(fallback,/\.team-source\{display:contents\}/);assert.match(fallback,/\.team-source-bar\{grid-column:1;grid-row:1/);assert.match(fallback,/#teamActivityPreview\{grid-column:1 \/ -1;grid-row:2;height:27px\}/);assert.doesNotMatch(fallback,/overflow:hidden|position:fixed/);});

test('prominent portfolio total reuses the existing verified AUD balance and Perth-day change',()=>{const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8'),css=fs.readFileSync(new URL('./team-work.css',import.meta.url),'utf8');assert.match(html,/Paper portfolio <small>Simulated · AUD/);assert.match(html,/<small>Total \(AUD\)<\/small><strong id="portfolioBalance">—<\/strong>/);assert.match(css,/#portfolioBalance\{font-size:18px/);assert.match(css,/@media\(max-width:760px\),\(max-height:500px\)\{#portfolioBalance\{font-size:14px/);assert.match(html,/id="portfolioSince">Perth day/);assert.match(html,/id="portfolioPnl">—/);});
