// Frozen public-only research fixtures. No network or real credentials are used.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validatePublicReviews,associateReviews,safeReviewSource,REVIEW_LIMITS,REVIEWER_REGISTRY,publicReviewSchema} from './public-review-contract.mjs';
import {createPublicReviewFeed,readPublicReviewSnapshot,PUBLIC_REVIEWS_URL} from './public-reviews.mjs?v=independent-reviews-20261010';
import {createPublicScoutFeed,publicScoutDisplay,PUBLIC_SCOUT_URL} from './public-scout.mjs?v=public-scout-review-20261010';
import {payloadDigest,identityKey} from './public-scout-contract-v1/lead-review.mjs';
import {PUBLIC_LIMITS} from './public-scout-contract-v1/public-feed.mjs';
import {projectFeed} from '../../backend/neptune-scout/project-feed.mjs';
const BASE=JSON.parse(fs.readFileSync(new URL('./fixtures/public-reviews-test.json',import.meta.url),'utf8')),FEED=JSON.parse(fs.readFileSync(new URL('./fixtures/public-reviewed-feed-test.json',import.meta.url),'utf8'));
const NOW=Date.parse(BASE.record_created_at)+1000,clone=structuredClone,raw=JSON.stringify,settle=()=>new Promise(r=>setImmediate(r));
async function validate(d=clone(BASE),options={}){return validatePublicReviews(typeof d==='string'?d:raw(d),{now_ms:NOW,...options});}
function bad(result,reason){assert.equal(result.ok,false);assert(result.error.includes(reason),result.error);assert.equal(result.document,null);assert.deepEqual(result.records,[]);}
function response(body=raw(BASE),extra={}){const r=new Response(body,{headers:{'content-type':'application/json'}});return{ok:r.ok,body:r.body,headers:r.headers,url:PUBLIC_REVIEWS_URL,redirected:false,...extra};}
function client({fetch=async()=>response(),onChange=()=>{},...options}={}){let now=NOW;const app=createPublicReviewFeed({fetch,now:()=>now,onChange,...options});return{app,setNow:n=>{now=n;}};}

test('actual completed four-lead review retains true late completion and expired quote clocks',async()=>{const r=await validate();assert.equal(r.ok,true,r.error);assert.equal(r.records.length,4);for(const row of r.records){assert.equal(row.review_completed_at,'2026-10-10T06:24:57.051567+00:00');assert.equal(row.subject.quote_expires_at,'2026-10-10T06:16:55.045Z');assert.equal(row.quote_state,'expired');assert.equal(row.review_timing,'completed_after_quote_expiry');assert.equal(row.verdict,'needs_more_evidence');assert.equal(row.original_raw_reproduced,false);assert.equal(row.paper_entry_allowed,false);assert.equal(row.execution_eligible,false);assert.equal(row.qualified_buy,false);}});
test('registry states configured Astra while denying cryptographic model attestation',async()=>{const r=await validate();assert.equal(r.records[0].reviewer.model,'gpt-6-astra');assert.match(r.records[0].reviewer.model_identity,/not_cryptographic_attestation/);assert.equal(r.document.authority.cryptographic_model_attestation,false);});
test('exact current feed association requires all immutable bindings',async()=>{const r=await validate(),digest=await payloadDigest(FEED,PUBLIC_LIMITS);const a=associateReviews(r.records,FEED,digest,NOW);assert.equal(a.current.length,4);assert.equal(a.history.length,0);for(const row of a.current)assert.equal(row.paper_entry_allowed,false);});
test('older review never reviews a same-ticker newer run, payload or source version',async()=>{const r=await validate(),digest=await payloadDigest(FEED,PUBLIC_LIMITS);for(const mutation of [f=>f.run.workflow_run_id='999999',f=>f.run.source_commit='a'.repeat(40),f=>f.leads.forEach(l=>l.evidence_sha256='b'.repeat(64)),f=>f.leads.forEach(l=>l.payload.expires_at='2026-10-10T07:00:00Z')]){const f=clone(FEED);mutation(f);const a=associateReviews(r.records,f,digest,NOW);assert.equal(a.current.length,0);assert.equal(a.history.length,4);}assert.equal(associateReviews(r.records,FEED,'c'.repeat(64),NOW).current.length,0);});
test('unknown reviewer and self-described actor or model fields are rejected',async()=>{const d=clone(BASE);d.reviews[0].reviewer_id='new-unknown-model';bad(await validate(d),'schema_invalid');for(const field of['reviewer','model','worker_path','signature']){const f=clone(BASE);f.reviews[0][field]='fake';bad(await validate(f),'schema_invalid');}});
test('collector cannot claim owner publication authority or add model attestation',async()=>{const d=clone(BASE);d.authority.kind='deterministic-collector';bad(await validate(d),'schema_invalid');d.authority.kind='repository-owner-publication';d.authority.cryptographic_model_attestation=true;bad(await validate(d),'schema_invalid');});
test('all order and entry flags remain immutable false',async()=>{for(const key of['paper_entry_allowed','execution_eligible','qualified_buy']){const d=clone(BASE);d.reviews[0][key]=true;bad(await validate(d),'schema_invalid');}});
test('incomplete, future and backdated review completion cannot appear completed',async()=>{for(const mutation of [r=>r.status='running',r=>r.review_completed_at='2026-10-11T00:00:00Z',r=>r.review_completed_at='2026-10-10T06:10:00Z',r=>r.review_started_at='2026-10-10T06:13:00Z']){const d=clone(BASE);mutation(d.reviews[0]);bad(await validate(d),d.reviews[0].status==='running'?'schema_invalid':'invalid_completed_review_window');}});
test('expired original quote may be reviewed later without extending it',async()=>{const d=clone(BASE);assert(Date.parse(d.reviews[0].review_started_at)>Date.parse(d.reviews[0].subject.quote_expires_at));assert.equal((await validate(d)).ok,true);d.reviews[0].subject.quote_expires_at='2026-10-10T06:30:00Z';bad(await validate(d),'invalid_completed_review_window');});
test('new observation must actually fall inside review interval',async()=>{const d=clone(BASE);d.reviews[0].new_observation_at='2026-10-10T06:30:00Z';bad(await validate(d),'new_review_observation_time_invalid');});
test('quote symbol, token ID and asset representation cannot be silently substituted',async()=>{for(const patch of[{base_id:'WRAPPED_NEAR'},{quote_id:'USDC'},{base_representation:'native'}]){const d=clone(BASE);Object.assign(d.reviews[0].subject.identity,patch);d.reviews[0].subject.identity_key=identityKey(d.reviews[0].subject.identity);bad(await validate(d),'review_exact_identity_mismatch');}});
test('independent findings require valid bounded source references',async()=>{const d=clone(BASE);d.reviews[0].findings[0].source_ids=['not-present'];bad(await validate(d),'review_finding_source_mismatch');const f=clone(BASE);f.reviews[0].sources.push(clone(f.reviews[0].sources[0]));bad(await validate(f),'unsafe_or_duplicate_review_source');});
test('original feed permalink must bind its exact immutable data commit',async()=>{const d=clone(BASE);d.reviews[0].sources=d.reviews[0].sources.filter(s=>s.source_id!=='original-feed');d.reviews[0].findings[0].source_ids=[];bad(await validate(d),'immutable_original_feed_link_required');const f=clone(BASE);f.reviews[0].subject.data_commit='c'.repeat(40);bad(await validate(f),'immutable_original_feed_link_required');});
test('public source links allow only vetted HTTPS destinations and paths',()=>{for(const good of BASE.reviews.flatMap(r=>r.sources.map(s=>s.url)))assert(safeReviewSource(good),good);for(const bad of['javascript:alert(1)','http://api.kraken.com/0/public/Ticker','https://evil.invalid/x','https://api.kraken.com.evil.invalid/0/public/Ticker','https://api.kraken.com/0/private/Balance','https://api.kraken.com/0/public/Ticker?api_key=private','https://user:secret@api.kraken.com/0/public/Ticker','https://github.com/seachef/ses-chef-labs/issues/1','https://raw.githubusercontent.com/seachef/ses-chef-labs/main/public/research-feed.json','https://www.sui.io/token-schedule?email=private@example.com'])assert.equal(safeReviewSource(bad),false,bad);});
test('publication replay or same-revision replacement rejected while identical reread allowed',async()=>{const first=await validate(),last={revision:BASE.revision,record_created_at:BASE.record_created_at,digest:first.digest,record_digests:first.record_digests};assert.equal((await validate(BASE,{last_seen:last})).ok,true);const d=clone(BASE);d.reviews[0].summary='Changed text';bad(await validate(d,{last_seen:last}),'review_document_replayed_or_replaced');const f=clone(BASE);f.revision++;bad(await validate({...f,record_created_at:'2026-10-10T06:25:00Z'},{last_seen:last}),'review_document_replayed_or_replaced');});
test('completed receipt ID is immutable even under a new document revision',async()=>{const first=await validate(),d=clone(BASE);d.revision++;d.reviews[0].summary='Silently changed result';bad(await validate(d,{last_seen:{revision:BASE.revision,record_created_at:BASE.record_created_at,digest:first.digest,record_digests:first.record_digests}}),'completed_review_record_mutated');});
test('duplicate receipt IDs, duplicate JSON keys and excessive input are rejected',async()=>{const d=clone(BASE);d.reviews.push(clone(d.reviews[0]));bad(await validate(d),'duplicate_review_id');bad(await validate(raw(BASE).replace('{','{"protocol":"fake",')),'duplicate_json_key');bad(await validate(' '.repeat(65537)),'payload_budget_exceeded');});
test('private and executable text fields cannot bypass public allowlist',async()=>{for(const key of['wallet_address','account_id','password','request_body','raw_response']){const d=clone(BASE);d.reviews[0][key]='private';bad(await validate(d),'schema_invalid');}for(const value of['<img src=x>','hidden\u202edata','line\nline']){const d=clone(BASE);d.reviews[0].summary=value;bad(await validate(d),'schema_invalid');}});
test('history ages out without rejuvenating original quote or review timestamps',async()=>{const r=await validate(),digest=await payloadDigest(FEED,PUBLIC_LIMITS),later=Date.parse(BASE.reviews[0].review_completed_at)+REVIEW_LIMITS.history_ms;assert.equal(associateReviews(r.records,FEED,digest,later).current.length,0);assert.equal(BASE.reviews[0].subject.quote_expires_at,'2026-10-10T06:16:55.045Z');});
test('fixed separate review GET is bounded, credentialless, immutable and throttled',async()=>{let calls=0;const c=client({fetch:async(url,o)=>{calls++;assert.equal(url,PUBLIC_REVIEWS_URL);assert.equal(o.method,'GET');assert.equal(o.credentials,'omit');assert.equal(o.cache,'no-store');assert.equal(o.redirect,'error');assert.equal(o.referrerPolicy,'no-referrer');return response();}});const s=await c.app.refresh();assert.equal(s.status,'ready');assert.equal(readPublicReviewSnapshot(s),s);assert.equal(readPublicReviewSnapshot(clone(s)),null);assert(Object.isFrozen(s.records[0].subject));await c.app.refresh();assert.equal(calls,1);c.setNow(NOW+300000);await c.app.refresh();assert.equal(calls,2);});
test('review timeout remains bounded even when fetch or body ignores abort',async()=>{for(const body of[false,true]){let timer,signal;const c=client({fetch:async(_u,o)=>{signal=o.signal;return body?response('',{body:new ReadableStream({start(){}})}):new Promise(()=>{});},setTimeout:f=>{timer=f;return 1;},clearTimeout(){}});const p=c.app.refresh();await settle();timer();await p;assert.equal(signal.aborted,true);assert.equal(c.app.snapshot().error,'review_timeout');}});
test('redirects, wrong endpoints, invalid content types and oversized bodies fail closed',async()=>{for(const f of [()=>response('',{redirected:true}),()=>response('',{url:PUBLIC_SCOUT_URL}),()=>response('',{headers:new Headers({'content-type':'text/html'})}),()=>response(' '.repeat(65537)),()=>response('',{body:null}),()=>response(new Uint8Array([255]))]){const c=client({fetch:async()=>f()});await c.app.refresh();assert.equal(c.app.snapshot().document,null);assert.equal(c.app.snapshot().status,'unavailable');}});
test('failure retains dated prior record without pretending a new review completed',async()=>{let okay=true;const c=client({fetch:async()=>{if(!okay)throw Error('private upstream text');return response();}});await c.app.refresh();const old=c.app.snapshot();okay=false;c.setNow(NOW+300000);await c.app.refresh();assert.equal(c.app.snapshot().digest,old.digest);assert.equal(c.app.snapshot().status,'unavailable');assert(!raw(c.app.snapshot()).includes('private upstream'));assert.equal(c.app.snapshot().records[0].review_completed_at,old.records[0].review_completed_at);});
test('disconnect and disposal ignore late completion; concurrent calls share request',async()=>{for(const action of['disconnect','dispose']){let resolve,calls=0;const c=client({fetch:async()=>{calls++;return new Promise(r=>{resolve=r;});}});const a=c.app.refresh(),b=c.app.refresh();c.app[action]();resolve(response());await Promise.all([a,b]);assert.equal(calls,1);assert.equal(c.app.snapshot().document,null);}});
test('clock rollback and renderer exceptions cannot manufacture fresh reviews',async()=>{const c=client({onChange:()=>{throw Error('view');}});await c.app.refresh();c.setNow(NOW-1);await c.app.refresh();assert.equal(c.app.snapshot().status,'unavailable');assert.equal(c.app.snapshot().records[0].quote_state,'expired');});
test('existing Scout evidence window displays actual completed findings and owner provenance',async()=>{const reviews=client();await reviews.app.refresh();const scout=createPublicScoutFeed({fetch:async()=>response(raw(FEED),{url:PUBLIC_SCOUT_URL}),now:()=>NOW,reviewSnapshot:()=>reviews.app.snapshot()});await scout.refresh();const s=scout.snapshot(),d=publicScoutDisplay(s,{now:NOW});assert.match(d.output,/4 recorded reviews/);assert.match(d.evidence,/Completed Astra review: needs more evidence/);assert.match(d.evidence,/configured gpt-6-astra/);assert.match(d.evidence,/not a cryptographic model-provider attestation/);assert.match(d.evidence,/not reproduced/);assert.match(d.evidence,/2026-10-10T06:24:57.051567/);assert.match(d.evidence,/https:\/\/api.kraken.com/);assert.match(d.evidence,/Full strategy qualification remains pending/);assert.doesNotMatch(d.evidence,/momentum: Completed-bar signal retained; full strategy qualification remains outstanding/);assert.equal(s.records.filter(r=>r.key.startsWith('scout-review:')).length,4);assert(s.assessments.every(a=>a.paper_entry_allowed===false&&a.independent_review.status==='not_reviewed'));});
test('forged UI review events cannot inject a reviewed label',async()=>{const fake={status:'ready',records:[{summary:'BUY NOW'}]};const scout=createPublicScoutFeed({fetch:async()=>response(raw(FEED),{url:PUBLIC_SCOUT_URL}),now:()=>NOW,reviewSnapshot:()=>fake});await scout.refresh();const d=publicScoutDisplay(scout.snapshot(),{now:NOW});assert.match(d.output,/review awaiting/);assert.doesNotMatch(d.evidence,/BUY NOW/);});
test('history does not label a newer same-identity feed reviewed',async()=>{const r=await validate(),f=clone(FEED);f.run.workflow_run_id='99999';const a=associateReviews(r.records,f,await payloadDigest(FEED,PUBLIC_LIMITS),NOW);assert.equal(a.current.length,0);assert.equal(a.history.length,4);});
test('repeated review render emits no duplicate completion and preserves actual completion time',async()=>{const reviews=client();await reviews.app.refresh();const scout=createPublicScoutFeed({fetch:async()=>response(raw(FEED),{url:PUBLIC_SCOUT_URL}),now:()=>NOW,reviewSnapshot:()=>reviews.app.snapshot()});await scout.refresh();for(let i=0;i<10;i++)scout.reviewChanged();const rows=scout.snapshot().records.filter(r=>r.key.startsWith('scout-review:'));assert.equal(rows.length,4);assert(rows.every(r=>r.at===BASE.reviews[0].review_completed_at));});
test('backend projector separates genuine failed breakout from unperformed qualification without upgrading pass',async()=>{const report=JSON.parse(fs.readFileSync(new URL('./fixtures/public-projector-report-test.json',import.meta.url))),markets=JSON.parse(fs.readFileSync(new URL('./fixtures/public-projector-markets-test.json',import.meta.url)));const f=await projectFeed(report,markets,{source_commit:'1'.repeat(40),run_id:'12345',generated_at:report.completed_at});for(const item of f.leads){const source=report.leads.find(l=>l.id===item.payload.lead_id),momentum=item.payload.deterministic_checks.find(c=>c.check_id==='momentum'),strategy=item.payload.deterministic_checks.find(c=>c.check_id==='strategy_qualification');assert.equal(strategy.status,'unknown');assert.notEqual(momentum.status,'passed');if(source.checks.momentum.completed_close_above_previous_20_highs===false){assert.equal(momentum.status,'failed');assert.match(momentum.reason,/did not close above/);}else assert.equal(momentum.status,'unknown');assert.equal(item.payload.execution_eligible,false);}});
test('new loader never gains workflow write scope, execution bridges or account credentials',()=>{const s=fs.readFileSync(new URL('./public-reviews.mjs',import.meta.url),'utf8'),w=fs.readFileSync(new URL('./neptune.mjs',import.meta.url),'utf8');assert.doesNotMatch(s,/supabase|apikey|requestAnimationFrame|method:\s*['"](?:POST|PUT|PATCH|DELETE)/);assert.match(w,/publicReviews\.disconnect/);assert.match(w,/reviewSnapshot:\(\)=>publicReviews\.snapshot/);});
test('deleted completed ID cannot be reintroduced with changed contents later in this session',async()=>{let body=raw(BASE);const c=client({fetch:async()=>response(body)});await c.app.refresh();const removed=clone(BASE);removed.revision++;removed.reviews=[];body=raw(removed);c.setNow(NOW+300000);await c.app.refresh();assert.equal(c.app.snapshot().status,'ready');const changed=clone(BASE);changed.revision+=2;changed.reviews[0].summary='Changed after deletion';body=raw(changed);c.setNow(NOW+600000);await c.app.refresh();assert.equal(c.app.snapshot().status,'unavailable');assert.equal(c.app.snapshot().document.revision,removed.revision);});
test('new independent observations carry exact capture hashes and cannot refer to a different instrument',async()=>{const d=clone(BASE);d.reviews[0].observations[0].instrument_id='OTHER/USD';bad(await validate(d),'review_observation_binding_mismatch');const f=clone(BASE);f.reviews[0].observations[0].sha256='not-a-hash';bad(await validate(f),'schema_invalid');});
test('entry and all public-scout WeakSet consumers share the new cache identity',()=>{const paths=['neptune.mjs','team-worker-view.mjs','public-scout.test.mjs','ui-v2.test.mjs'];for(const name of paths){const s=fs.readFileSync(new URL('./'+name,import.meta.url),'utf8');assert.match(s,/public-scout\.mjs\?v=public-scout-review-20261010/);assert.doesNotMatch(s,/public-scout\.mjs\?v=public-scout-20261010/);}const entry=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');assert.match(entry,/neptune\.mjs\?v=public-scout-reviewed-20261010/);const scout=fs.readFileSync(new URL('./public-scout.mjs',import.meta.url),'utf8'),app=fs.readFileSync(new URL('./neptune.mjs',import.meta.url),'utf8');assert.match(scout,/public-reviews\.mjs\?v=independent-reviews-20261010/);assert.match(app,/public-reviews\.mjs\?v=independent-reviews-20261010/);});
test('historical completed review remains visible when current scan is absent or expired on first load',async()=>{const reviews=client();await reviews.app.refresh();for(const expired of[false,true]){const now=expired?Date.parse(FEED.discovery_expires_at)+1:NOW;const scout=createPublicScoutFeed({fetch:async()=>expired?response(raw(FEED),{url:PUBLIC_SCOUT_URL}):{ok:false},now:()=>now,reviewSnapshot:()=>reviews.app.snapshot()});await scout.refresh();const d=publicScoutDisplay(scout.snapshot(),{now});assert.equal(d.status,'UNAVAILABLE');assert.match(d.output,/4 historical independent reviews/);assert.match(d.evidence,/Historical review of an earlier or different snapshot/);assert.match(d.evidence,/No current-snapshot review or trade approval is inferred/);assert.match(d.evidence,/Astra/);}});
test('team terminal derives review summary rather than always claiming awaiting',()=>{const source=fs.readFileSync(new URL('./team-worker-view.mjs',import.meta.url),'utf8');assert.doesNotMatch(source,/\+'; independent review awaiting\.'/);assert.match(source,/publicScoutDisplay\(scoutSnapshot,\{now:now\(\)\}\)\.output/);});
