import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {readResearchV1} from './research-v1.mjs';
import {validateV2} from './status-v2.mjs?v=experiment-provenance-v3-r2';
const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/research-v1.json',import.meta.url)));const clone=()=>structuredClone(fixture);
test('six evidence streams and fixed catalogue provenance accepted',()=>{const p=readResearchV1(fixture);assert(p);assert.deepEqual(p.streams.map(x=>x.id),['scout','depth','pulse','shield','ledger','watch']);assert.equal(p.catalogue.live_screen_status,'not_connected');});
test('optional missing or malformed extension never throws',()=>{for(const x of [null,{}, {research_v1:3},{research_v1:{}}])assert.equal(readResearchV1(x),null);});
test('static catalogue time/hash/counts cannot masquerade as fresh coverage',()=>{for(const [key,value] of [['observed_at',new Date().toISOString()],['research_markets',100000],['source_sha256','a'.repeat(64)],['live_screen_status','running']]){const p=clone();p.research_v1.catalogue[key]=value;assert.equal(readResearchV1(p),null);}});
test('unknown private extras discarded, arbitrary text and foreign assets rejected',()=>{const p=clone();p.research_v1.private_key='SECRET';p.research_v1.streams[0].secret='SECRET';assert(!JSON.stringify(readResearchV1(p)).includes('SECRET'));p.research_v1.checks[0].reason='<script>';assert.equal(readResearchV1(p),null);p.research_v1.checks[0].asset='TAO/USD';assert.equal(readResearchV1(p),null);});
test('future evidence and nonfinite timestamps rejected',()=>{const p=clone();p.research_v1.streams[1].at='2099-01-01T00:00:00Z';assert.equal(readResearchV1(p),null);p.research_v1.streams[1].at='Infinity';assert.equal(readResearchV1(p),null);});
test('optional field is compatible with unchanged authoritative old frontend',()=>{const baseline=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-running-v2.json',import.meta.url)));for(const research_v1 of [undefined,fixture.research_v1,{malformed:true}]){const payload={...baseline,...(research_v1?{research_v1}:{})};assert.equal(validateV2([{id:'neptune-paper-v2',payload}]),payload);}});

test('dynamic assertions require matching actual status evidence',()=>{const p=clone();p.research_v1.checks[0].decision_id='fabricated';assert.equal(readResearchV1(p),null);const q=clone();q.research_v1.streams[4].fill_id='fabricated';assert.equal(readResearchV1(q),null);const r=clone();r.research_v1.streams[3].status='paused';assert.equal(readResearchV1(r),null);});

test('known source cannot be relabelled as a fill or moved to another gate',()=>{const p=clone();p.research_v1.checks[0].verdict='filled';p.research_v1.streams[1].status='filled';assert.equal(readResearchV1(p),null);const q=clone();q.research_v1.checks[2].reported_gate='momentum';assert.equal(readResearchV1(q),null);});
test('nonwaiting streams require exact evidence and canonical reasons',()=>{for(const mutate of [p=>{p.research_v1.streams[2].status='filled';delete p.research_v1.streams[2].decision_id;},p=>{p.research_v1.streams[3].reason='entry_risk_latch_paused';},p=>{p.research_v1.streams[5].reason='completed_15m_momentum';},p=>{p.research_v1.checks[0].verdict='not_observed';p.research_v1.checks[0].decision_id=null;}]){const p=clone();mutate(p);assert.equal(readResearchV1(p),null);}});
test('end-to-end integration fixture satisfies authoritative v2 validator',()=>{assert.equal(validateV2([{id:'neptune-paper-v2',payload:fixture}]),fixture);assert(readResearchV1(fixture));});

test('unsupported reference fields cannot escape from Scout Shield or Watch',()=>{const p=clone();for(const i of [0,3,5])Object.assign(p.research_v1.streams[i],{asset:'ETH/USD',decision_id:'fabricated',fill_id:'fabricated'});const r=readResearchV1(p);assert(r);for(const i of [0,3,5]){assert.equal(r.streams[i].asset,undefined);assert.equal(r.streams[i].decision_id,undefined);assert.equal(r.streams[i].fill_id,undefined);}});
