import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createCanvas,loadImage} from './canvas-test-support.mjs';
import {configureCosmicCanvas} from './cosmic-motion.mjs?v=neptune-native-20261009';
import {ASSETS,renderScene,constellationLayout} from './cosmos-scene.mjs?v=real-targets-20261010';
import {createSceneTargets} from './scene-targets.mjs?v=real-targets-20261010';
configureCosmicCanvas(createCanvas);
const images=await Promise.all(ASSETS.map(a=>loadImage(new URL('./assets/'+a,import.meta.url).pathname)));
const now=Date.parse('2026-10-10T04:00:00Z');
const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-running-v2.json',import.meta.url)));
const report=()=>{const p=structuredClone(fixture);p.heartbeat_at=new Date(now).toISOString();return p;};
function receipt(){const bridge=createSceneTargets(),p=report();bridge.observeReport(p,now);p.heartbeat_at=new Date(now+1).toISOString();p.fills[0].id='new-render-fill';p.fills[0].at=p.heartbeat_at;bridge.observeReport(p,now+1);return {bridge,cue:bridge.current(now+1)};}
function render(w,h,t,options={}){return renderScene(createCanvas(w,h).getContext('2d'),images,t,w,h,{now:now+800,...options});}
test('roaming keeps run roll squat and look poses without one ambient beam',()=>{const kinds=new Set();for(let i=0;i<200;i++){const r=render(390,430,i/10);kinds.add(r.pose.kind);assert.equal(r.beamCount,0);assert.equal(r.beamKey,null);}for(const k of ['run','roll','crouch','look'])assert.ok(kinds.has(k));});
test('untrusted fabricated buys or catalogue eligibility flags never create beams',()=>{for(const cue of [null,{kind:'buy',asset:'ETH/USD',createdAt:now,until:now+9000,eventId:'fake'}]){const r=render(1180,500,2,{cue,catalogue:[{id:'ETH/USD',base:'ETH',laser_eligible:true}]});assert.equal(r.beamCount,0);assert.equal(r.verified,false);}});
test('fresh check markers stay non-firing even when a decision says filled',()=>{const r=render(1180,500,2,{markers:[{asset:'ETH/USD',pair:'ETH/USD',label:'ETH',kind:'checked',result:'filled',reason:'later_observation_entry',active:true,opacity:1}]});assert.equal(r.beamCount,0);assert.equal(r.pose.fire,false);});
test('real new fill binds both eyes to one visible exact-instrument marker',()=>{for(const [w,h]of [[320,400],[390,430],[768,600],[1180,500]]){const {bridge,cue}=receipt();assert.ok(cue);const r=render(w,h,2,{cue,markers:bridge.markers(now+800)});assert.equal(r.beamCount,2);assert.equal(r.target.asset,cue.asset);assert.equal(r.beamKey,cue.eventId);for(const eye of r.eyes)assert.ok(r.pose.facing*(r.target.x-eye.x)>0);assert.ok(r.target.x>=26&&r.target.x<=w-26);assert.ok(r.target.y<h*.6);}});
test('expired, disconnected and reduced-motion receipts have no beams',()=>{const {bridge,cue}=receipt();assert.equal(render(390,430,2,{cue,now:now+6000}).beamCount,0);assert.equal(render(390,430,2,{cue,reduced:true}).beamCount,0);bridge.disconnect();assert.equal(render(390,430,2,{cue}).beamCount,0);});
test('fully occluded scene suppresses even verified fills instead of drawing offscreen',()=>{const {cue}=receipt(),r=render(390,430,2,{cue,masks:[{left:0,right:390,top:0,bottom:430}]});assert.equal(r.target,undefined);assert.equal(r.beamCount,0);});
test('constellation retains venue identities, respects phone caps and avoids control masks',()=>{const items=Array.from({length:100},(_,i)=>({asset:'catalogue-'+i,label:'C'+i,active:false}));for(const [w,h,max]of[[390,430,24],[1180,500,42]]){const masks=[{left:0,right:250,top:0,bottom:180}],r=constellationLayout(w,h,items,{masks});assert.ok(r.length<=max);assert.equal(new Set(r.map(x=>x.asset)).size,r.length);for(const p of r)assert.ok(!(p.x>=-28&&p.x<=278&&p.y>=-20&&p.y<=208));}});
test('native HYPE fill targets HYPE/USDC rather than an empty legacy-node lookup',()=>{
 const b=createSceneTargets(),p=report();p.fills=[];p.account.fills=0;p.native_paper={version:1,mode:'PAPER',observed_at:p.heartbeat_at,valuation_at:p.heartbeat_at,valuation_complete:true,history_complete:false,positions:[],pending_quote_balances:[],recent_fills:[]};b.observeReport(p,now);
 p.heartbeat_at=new Date(now+1).toISOString();p.native_paper.observed_at=p.heartbeat_at;p.account.fills=1;p.native_paper.recent_fills=[{id:'native-hype-render',asset:'hyperliquid:@107',venue:'hyperliquid',side:'buy',quote_currency:'USDC',gross_qty:.123,fee_qty:.000123,fee_quote:0,fee_currency:'HYPE',net_inventory_delta:.122877,net_quote_delta:-300,cash_delta_base:-450,fee_base:.45,fx_cost_base:1,position_status:'open',settlement_status:'settled',at:p.heartbeat_at}];b.observeReport(p,now+1);const cue=b.current(now+1);assert.ok(cue);
 const r=render(390,430,2,{cue,markers:b.markers(now+800)});assert.equal(r.beamCount,2);assert.equal(r.target.asset,'hyperliquid:@107');assert.equal(r.target.label,'HYPE');assert.equal(r.target.pair,'HYPE/USDC');
});

test('same venue and exact pair uses one display node while cross-venue tickers stay distinct',()=>{const catalogue=[{id:'kraken:XETHZUSD',venue:'kraken',pair:'ETH/USD',base:'ETH'},{id:'kraken:HYPEUSD',venue:'kraken',pair:'HYPE/USD',base:'HYPE'},{id:'hyperliquid:@107',venue:'hyperliquid',pair:'HYPE/USDC',base:'HYPE'}];const r=render(1180,500,2,{catalogue,markers:[{asset:'ETH/USD',label:'ETH',pair:'ETH/USD',venue:'Kraken',active:false,opacity:.27}]});assert.equal(r.nodes.filter(n=>n.label==='ETH').length,1);assert.equal(r.nodes.filter(n=>n.label==='HYPE').length,2);assert.equal(new Set(r.nodes.filter(n=>n.label==='HYPE').map(n=>n.venue)).size,2);assert.equal(r.beamCount,0);});
