import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {SPECIALISTS,readSpecialistAccounts,renderSpecialistAccounts} from './specialist-accounts.mjs';
import {validateV2} from './status-v2.mjs';
const now=Date.parse('2026-10-09T12:00:00Z'),at=new Date(now).toISOString();
function report(){return {currency:'AUD',status:'running',heartbeat_at:at,quote_at:at,account:{initial_cash:10000,cash:9950,available_cash:9900,reserved_cash:50,valuation_at:at},specialist_accounts:{version:1,mode:'PAPER',currency:'AUD',initial_cash:10000,total_cash:9950,source_revision:13,observed_at:at,allocation_status:'allocated',accounts:SPECIALISTS.map(id=>({id,nominal_initial_cash:2000,cash:1990,available_cash:1980,reserved_cash:10,exposure_base:0,realized_pnl:0,costs_base:null,status:'research_only',evidence_at:null}))}};}
function render(p){const nodes=Object.fromEntries(['specialistStatus','specialistAccounts'].map(id=>[id,{textContent:'',replaceChildren(...items){this.children=items;}}]));const document={getElementById:id=>nodes[id],createElement:()=>({textContent:'',set innerHTML(v){throw Error('unsafe');}})};const view=renderSpecialistAccounts(document,p,now);return {view,text:nodes.specialistAccounts.children.map(n=>n.textContent).join('\n'),message:nodes.specialistStatus.textContent};}
test('five equal nominal shares conserve existing actual cash, including legacy loss',()=>{const p=report(),v=readSpecialistAccounts(p,now);assert.equal(v.state,'allocated');assert.equal(v.totalCash,9950);assert.equal(v.accounts.reduce((n,a)=>n+a.nominal_initial_cash,0),10000);const r=render(p);assert.match(r.message,/9,950/);assert.match(r.text,/cash AUD\s1,990/);assert.match(r.text,/fees\/FX —/);assert.doesNotMatch(r.text,/Paper scan observed/);});
test('missing optional projection never fabricates five funded wallets',()=>{for(const p of [null,{}, {specialist_accounts:null}]){const r=render(p);assert.equal(r.view.state,'missing');assert.equal((r.text.match(/Planned initial share/g)||[]).length,5);assert.match(r.text,/settled cash —/);assert.doesNotMatch(r.text,/cash AUD|Paper scan observed|fills/);}});
test('pending is planned only, all cash and PnL unknown',()=>{const p=report();p.specialist_accounts.allocation_status='pending';p.specialist_accounts.accounts.forEach(a=>{for(const k of ['cash','reserved_cash','available_cash','exposure_base','realized_pnl','costs_base'])a[k]=null;});assert.equal(readSpecialistAccounts(p,now).state,'pending');assert.match(render(p).text,/Allocation pending/);assert.doesNotMatch(render(p).text,/cash AUD|costs AUD/);});
const cases={
 'duplicate agent':p=>p.specialist_accounts.accounts[1].id='solana',
 'unknown agent':p=>p.specialist_accounts.accounts[1].id='fake',
 'missing agent':p=>p.specialist_accounts.accounts.pop(),
 'extra agent':p=>p.specialist_accounts.accounts.push({...p.specialist_accounts.accounts[0]}),
 'unequal nominal allocation':p=>p.specialist_accounts.accounts[0].nominal_initial_cash=3000,
 'duplicated money':p=>p.specialist_accounts.accounts.forEach(a=>{a.cash=10000;a.available_cash=9990;}),
 'root mismatch':p=>p.specialist_accounts.total_cash=10000,
 'invalid reservation':p=>p.specialist_accounts.accounts[0].reserved_cash=5000,
 'global reservation mismatch':p=>p.account.reserved_cash=49,
 'global availability mismatch':p=>p.account.available_cash=9800,
 'cash string':p=>p.specialist_accounts.accounts[0].cash='1990',
 'NaN return':p=>p.specialist_accounts.accounts[0].realized_pnl=NaN,
 'negative exposure':p=>p.specialist_accounts.accounts[0].exposure_base=-1,
 'invented status':p=>p.specialist_accounts.accounts[0].status='live',
 'real money mode':p=>p.specialist_accounts.mode='LIVE',
 'bad currency':p=>p.specialist_accounts.currency='USD',
 'bad revision':p=>p.specialist_accounts.source_revision=-1,
 'bad observation':p=>p.specialist_accounts.observed_at='invalid',
 'bad evidence':p=>p.specialist_accounts.accounts[0].evidence_at='<img>',
 'unproven costs':p=>delete p.specialist_accounts.accounts[0].costs_base,
 'null account row':p=>p.specialist_accounts.accounts[0]=null,
 'pending with cash':p=>p.specialist_accounts.allocation_status='pending',
};
for(const [name,mutate] of Object.entries(cases))test('rejects '+name+' without showing monetary values',()=>{const p=report();mutate(p);const r=render(p);assert.equal(r.view.state,'invalid');assert.doesNotMatch(r.text,/cash AUD|Paper scan observed/);});
test('stale/future projection or heartbeat removes values and active status',()=>{for(const [target,key]of [['specialist_accounts','observed_at'],[null,'heartbeat_at']])for(const delta of [-90001,1]){const p=report();(target?p[target]:p)[key]=new Date(now+delta).toISOString();const r=render(p);assert.equal(r.view.state,'stale');assert.doesNotMatch(r.text,/cash AUD|Paper scan observed/);}});
test('paper_active requires fresh per-agent evidence, running engine and quote',()=>{for(const mode of ['valid','missing','stale','future','stopped','quote_stale']){const p=report(),a=p.specialist_accounts.accounts[0];a.status='paper_active';a.evidence_at=at;a.source_venue='Kraken public spot';a.execution_kind='spot_paper';if(mode==='missing')a.evidence_at=null;if(mode==='stale')a.evidence_at=new Date(now-90001).toISOString();if(mode==='future')a.evidence_at=new Date(now+1).toISOString();if(mode==='stopped')p.status='stopped';if(mode==='quote_stale')p.quote_at=new Date(now-90001).toISOString();const r=render(p);assert.equal(r.text.includes('Paper scan observed'),mode==='valid');}});
test('missing marks are unknown exposure, never zero or inferred equity',()=>{const p=report();p.specialist_accounts.accounts[0].exposure_base=null;assert.match(render(p).text,/Solana[\s\S]*Exposure —/);p.account.valuation_at=null;assert.equal((render(p).text.match(/Exposure —/g)||[]).length,5);assert.match(render(p).text,/settled cash AUD/);});
test('bad optional data leaves existing valid ledger usable',()=>{const p=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-settled-v2.json',import.meta.url)));p.specialist_accounts={untrusted:true};assert.equal(validateV2([{id:'neptune-paper-v2',payload:p}]),p);assert.equal(readSpecialistAccounts(p,now).state,'invalid');});
test('account section is inside existing history dialog, main six panes and artwork unchanged',()=>{const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');assert.equal((html.match(/class="stream-window"/g)||[]).length,6);const dialog=html.slice(html.indexOf('<dialog id="historyDialog"'),html.indexOf('<dialog id="findingsDialog"'));assert.match(dialog,/specialistAccounts/);assert.equal(html.indexOf('specialistAccounts'),html.indexOf('<dialog id="historyDialog"')+dialog.indexOf('specialistAccounts'));assert.match(html,/id="art" src="\.\/neptune-scene.jpg"/);});
test('SQL pending contract permits unknown total cash without funded claims',()=>{const p=report();p.specialist_accounts.allocation_status='pending';p.specialist_accounts.total_cash=null;for(const a of p.specialist_accounts.accounts)for(const k of ['cash','reserved_cash','available_cash','exposure_base','realized_pnl','costs_base'])a[k]=null;const r=render(p);assert.equal(r.view.state,'pending');assert.doesNotMatch(r.text,/cash AUD|Paper scan observed/);p.specialist_accounts.allocation_status='allocated';assert.equal(readSpecialistAccounts(p,now).state,'invalid');});
test('named specialist always distinguishes real source venue from research coverage',()=>{const p=report(),a=p.specialist_accounts.accounts[0];a.source_venue='Kraken public spot';a.execution_kind='spot_paper';a.readiness_reason='Waiting for a qualifying SOL/USD spot entry.';a.status='waiting_for_data';const r=render(p);assert.match(r.text,/Solana · Waiting for data\nSource venue: Kraken public spot · spot paper only; no on-chain execution/);assert.match(r.text,/Readiness: Waiting for a qualifying SOL\/USD spot entry/);assert.match(r.text,/Base · Research only\nSource venue: unverified/);assert.doesNotMatch(r.text,/Paper scan observed/);});
test('activity cannot be asserted without verified source venue and execution type',()=>{for(const fields of [{},{source_venue:'Kraken public spot'},{execution_kind:'spot_paper'},{source_venue:'Kraken public spot',execution_kind:'research_only'}]){const p=report(),a=p.specialist_accounts.accounts[0];Object.assign(a,{status:'paper_active',evidence_at:at},fields);assert.doesNotMatch(render(p).text,/Paper scan observed/);}});
test('malformed source/readiness fails closed and text markup stays inert',()=>{for(const fields of [{source_venue:42},{source_venue:''},{execution_kind:'onchain'},{readiness_reason:null}]){const p=report();Object.assign(p.specialist_accounts.accounts[0],fields);assert.equal(render(p).view.state,'invalid');}const p=report();p.specialist_accounts.accounts[0].readiness_reason='<img src=x onerror=alert(1)>';assert.match(render(p).text,/<img src=x onerror=alert\(1\)>/);});
test('actual SQL allocation projection interoperates with UI without inventing venue activity',()=>{const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/specialist-allocated-sql.json',import.meta.url)));const p=report(),time=Date.parse(fixture.observed_at)+1000;p.specialist_accounts=fixture;p.account.cash=fixture.total_cash;p.account.available_cash=fixture.total_cash;p.account.reserved_cash=0;p.heartbeat_at=fixture.observed_at;p.quote_at=fixture.observed_at;p.account.valuation_at=fixture.observed_at;const view=readSpecialistAccounts(p,time);assert.equal(view.state,'allocated');assert.equal(view.accounts.length,5);assert.equal(view.accounts.reduce((n,a)=>n+a.cash,0),10000);assert.equal(view.accounts[0].source_venue,'Kraken public spot');assert.equal(view.accounts[0].execution_kind,'spot_paper');assert.match(view.accounts[0].readiness_reason,/not on-chain execution/);assert.match(view.accounts[0].costs_basis,/slippage embedded/);assert.equal(view.accounts[1].status,'research_only');});
