import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import {ASSETS,validateV2,paperViewV2,money,quote} from './status-v2.mjs?v=neptune-native-20261009';
const pending=JSON.parse(fs.readFileSync(new URL('./fixtures/pending-v2.json',import.meta.url)));
const now=Date.parse('2026-10-09T05:00:00Z'),at=new Date(now).toISOString();
const row=p=>[{id:'neptune-paper-v2',payload:p}];
function active(){return {...structuredClone(pending),currency:'AUD',risk:{...pending.risk,entry_paused:false},status:'running',heartbeat_at:at,quote_at:at,scan_at:at,scan_complete:true,message:'Nothing to report',account:{initial_cash:10000,cash:10000,equity:10000,realized_pnl:0,unrealized_pnl:0,fees:0,fills:0}};}
test('uncreated is not a seeded account',()=>{assert.equal(validateV2(row(pending)).account.cash,null);assert.equal(paperViewV2(pending,true,now).status,'uncreated');assert.equal(money(null,null),'—');let p=structuredClone(pending);p.account.cash=10000;assert.throws(()=>validateV2(row(p)));});
test('one account exact v2 envelope required',()=>{assert.throws(()=>validateV2([]));assert.throws(()=>validateV2([...row(active()),...row(active())]));for(const [k,v] of [['version',1],['mode','LIVE'],['currency','NZD'],['historically_validated',true]]){let p=active();p[k]=v;assert.throws(()=>validateV2(row(p)));}});
test('AUD and USD labels are explicit and never relabel prices',()=>{assert.match(money(10000,'AUD'),/AUD/);assert.match(money(10000,'USD'),/USD/);assert.match(quote(12),/USD/);assert.equal(money(10000,null),'—');});
test('Nothing to report requires fresh complete scan',()=>{let p=active();assert.equal(paperViewV2(p,true,now).reason,'Nothing to report');for(const k of ['heartbeat_at','quote_at','scan_at']){let q=structuredClone(p);q[k]=new Date(now-121000).toISOString();assert.notEqual(paperViewV2(q,true,now).reason,'Nothing to report');q[k]=new Date(now+1000).toISOString();assert.notEqual(paperViewV2(q,true,now).reason,'Nothing to report');}p.scan_complete=false;assert.equal(paperViewV2(p,true,now).status,'incomplete');});
test('missing feed and paused states remain distinct',()=>{assert.equal(paperViewV2(null,false,now).label,'Data unavailable');assert.equal(paperViewV2(null,true,now).label,'Account not created');for(const state of ['stopped','warming_up','risk_paused','capacity_paused']){let p=active();p.status=state;p.message='Entries paused';assert.equal(paperViewV2(p,true,now).status,state);}});
test('numeric strings, nonfinite balances and bogus fills rejected',()=>{for(const v of ['10000',Infinity,NaN]){let p=active();p.account.cash=v;assert.throws(()=>validateV2(row(p)));}let p=active();p.fills=[{id:'fake'}];assert.throws(()=>validateV2(row(p)));});
test('unknown/duplicate markets cannot qualify as complete universe',()=>{let p=active();p.universe[0]='BTC/USD';assert.throws(()=>validateV2(row(p)));p=active();p.universe[0]=p.universe[1];assert.throws(()=>validateV2(row(p)));assert.equal(ASSETS.length,6);});
test('current published orbit CSS is preserved and responsive windows remain',()=>{const css=fs.readFileSync(new URL('./neptune.css',import.meta.url),'utf8');assert.equal(createHash('sha256').update(css).digest('hex'),'660f3693a812ba3bc51a90b0a5dd97f50575137ccd5597eb4f7d494d154513db');assert.match(css,/@media\(max-width:620px\)/);assert.match(css,/@media\(max-width:850px\)/);assert.match(css,/prefers-reduced-motion/);const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');assert.equal((html.match(/class="stream-window/g)||[]).length,6);assert.match(html,/\.\/neptune-scene.jpg/);assert.match(html,/\.\.\/portfolio\//);});
test('UI has no HTML injection, storage, v1 or order mutation path',()=>{const src=fs.readFileSync(new URL('./neptune.mjs',import.meta.url),'utf8');assert.doesNotMatch(src,/innerHTML|insertAdjacentHTML|localStorage|sessionStorage|paper_public_status|paper_control|method\s*:\s*['"](?:POST|PATCH|DELETE)/);assert.match(src,/li.textContent=format\(item\)/);assert.match(src,/credentials:'omit'/);assert.match(src,/prefers-reduced-motion/);assert.match(src,/audioContext/);});

test('confirmed AUD cannot be relabeled from an active USD account',()=>{let p=active();p.currency='USD';assert.throws(()=>validateV2(row(p)));});
test('seed must match approved 10000, pending cannot scan and contradictory running rejected',()=>{let p=active();p.account.initial_cash=6000;assert.throws(()=>validateV2(row(p)));p=active();p.account.equity=-1;assert.throws(()=>validateV2(row(p)));p=active();p.risk.entry_paused=true;assert.throws(()=>validateV2(row(p)));p=structuredClone(pending);p.scan_complete=true;assert.throws(()=>validateV2(row(p)));});
test('terminal state stays stopped despite stale heartbeat',()=>{for(const status of ['stopped','capacity_paused']){let p=active();p.status=status;p.heartbeat_at=null;p.quote_at=null;assert.equal(paperViewV2(p,true,now).status,status);}});
test('display tolerates server cadence without relaxing execution gate',()=>{let p=active();p.quote_at=new Date(now-30001).toISOString();assert.equal(paperViewV2(p,true,now).status,'running');p.quote_at=new Date(now-80000).toISOString();assert.equal(paperViewV2(p,true,now).status,'running');p.quote_at=new Date(now-90001).toISOString();assert.equal(paperViewV2(p,true,now).status,'stale');});
function pendingFill(){return {id:'exit1',order_id:'order1',decision_id:'decision1',observation_id:'observation2',at,asset:'ETH/USD',side:'sell',qty:1,price:2000,quote_currency:'USD',settlement_status:'pending_conversion',gross_usd:2000,fee_usd:16,net_usd:1984,fx:null,fx_source:null,fx_at:null,fx_rate_date:null,fx_retrieved_at:null,fx_applied_rate:null,gross_base:null,fee_base:null,fx_cost_base:null,cash_delta_base:null,slippage_pct:.25};}
test('verified USD protective exit can await AUD conversion without invented PnL',()=>{let p=active();p.status='data_missing';p.account.equity=null;p.account.unrealized_pnl=null;p.account.unsettled_usd=1984;p.account.fills=1;p.fills=[pendingFill()];p.results=[{id:'result1',asset:'ETH/USD',closed_at:at,entry_fill_id:'entry1',exit_fill_id:'exit1',pnl_base:null,net_r:null,status:'pending_conversion'}];assert.equal(validateV2(row(p)).fills[0].cash_delta_base,null);assert.notEqual(paperViewV2(p,true,now).status,'running');p.fills[0].side='buy';assert.throws(()=>validateV2(row(p)));});
test('pending conversion cannot claim settled AUD money',()=>{let p=active();p.account.fills=1;p.fills=[pendingFill()];p.fills[0].cash_delta_base=3000;assert.throws(()=>validateV2(row(p)));});
test('settled fill validates independent FX provenance and accounting',()=>{let p=active();p.account.fills=1;p.fills=[{...pendingFill(),settlement_status:'settled',fx:1.5,fx_source:'Frankfurter ECB reference',fx_at:at,fx_rate_date:'2026-10-09',fx_retrieved_at:at,fx_applied_rate:1.49625,gross_base:3000,fee_base:24,fx_cost_base:7.44,cash_delta_base:2968.56}];assert.equal(validateV2(row(p)).fills.length,1);p.fills[0].cash_delta_base=3000;assert.throws(()=>validateV2(row(p)));});
test('separate FX settlements do not overwrite pending fills',()=>{let p=active();p.settlements=[{id:'settlement1',exit_fill_id:'exit1',at,usd_amount:1984,fx:1.5,fx_source:'Frankfurter ECB reference',fx_at:at,fx_rate_date:'2026-10-09',fx_retrieved_at:at,fx_applied_rate:1.49625,fx_cost_base:7.44,cash_delta_base:2968.56,pnl_base:100}];assert.equal(validateV2(row(p)).settlements[0].exit_fill_id,'exit1');p.settlements[0].fx_retrieved_at=null;assert.throws(()=>validateV2(row(p)));});
test('shared engine projection fixtures validate without field translation',()=>{for(const file of ['engine-running-v2.json','engine-unsettled-v2.json','engine-settled-v2.json']){const p=JSON.parse(fs.readFileSync(new URL('./fixtures/'+file,import.meta.url)));assert.equal(validateV2(row(p)),p);}});
test('tampered cost model and FX source reject ledger records',()=>{let p=active();p.account.fills=1;p.fills=[pendingFill()];p.fills[0].slippage_pct=0;assert.throws(()=>validateV2(row(p)));p.fills[0].slippage_pct=.25;p.fills[0].fee_usd=0;p.fills[0].net_usd=2000;assert.throws(()=>validateV2(row(p)));p=active();p.account.fx_source={unsafe:'object'};assert.throws(()=>validateV2(row(p)));p=active();p.account.fx=Infinity;assert.throws(()=>validateV2(row(p)));p=active();p.account.fx_retrieved_at='invalid';assert.throws(()=>validateV2(row(p)));});
test('tampered FX settlement totals or linkage reject entire report',()=>{const receipt={id:'settlement1',exit_fill_id:'exit1',at,usd_amount:1984,fx:1.5,fx_source:'Frankfurter ECB reference',fx_at:at,fx_rate_date:'2026-10-09',fx_retrieved_at:at,fx_applied_rate:1.49625,fx_cost_base:7.44,cash_delta_base:2968.56,pnl_base:100};for(const [field,value] of [['cash_delta_base',9999],['fx_applied_rate',1.5],['fx_cost_base',0],['fx_source','unverified']]){let p=active();p.settlements=[{...receipt,[field]:value}];assert.throws(()=>validateV2(row(p)));}let p=active();p.account.fills=1;p.fills=[pendingFill()];p.settlements=[{...receipt,usd_amount:1000,cash_delta_base:1496.25,fx_cost_base:3.75}];assert.throws(()=>validateV2(row(p)));});

test('entry and new runtime dependencies use one deterministic cache version',()=>{const version='neptune-native-20261009',html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');assert.ok(html.includes('./neptune.mjs?v=public-scout-reviewed-20261010'));assert.ok(html.includes('./paper-details.css?v='+version));for(const name of ['neptune.mjs','paper-panels-v2.mjs','paper-history-v2.mjs']){const source=fs.readFileSync(new URL('./'+name,import.meta.url),'utf8');const imports=[...source.matchAll(/from ['"](\.\/[^'"]+\.mjs[^'"]*)['"]/g)];assert.ok(imports.length);for(const match of imports){const expected=/\/public-reviews\.mjs/.test(match[1])?'independent-reviews-20261010':/\/public-scout\.mjs/.test(match[1])?'public-scout-review-20261010':/\/cosmos-controller\.mjs/.test(match[1])?'neural-currents-20261010':/\/discovery-catalogue-validation\.mjs/.test(match[1])?'discovery-20261010':/\/(scene-targets|cosmos-controller)\.mjs/.test(match[1])?'real-targets-20261010':/\/market-activity\.mjs/.test(match[1])?'market-activity-20261010':/\/(paper-panels-v2|paper-history-v2|native-fields|native-history-validation)\.mjs/.test(match[1])?'neptune-native-r2-20261009':version;assert.ok(match[1].endsWith('?v='+expected),match[1]);}}assert.ok(html.includes('Verified owner controls can request Stop or Resume'));assert.ok(!html.includes('This page does not start, stop'));});

test("current orbit honors motion-off and OS reduced motion",()=>{const css=fs.readFileSync(new URL("./paper-details.css",import.meta.url),"utf8");assert.match(css,/body\.still \.agent-node,body\.still \.agent-core:after\{animation:none!important\}/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)\{\.agent-node,\.agent-core:after\{animation:none!important\}\}/);});
test('cosmos uses one branded import graph, original fallback and click-through deck padding',()=>{
 const version='neptune-native-20261009';for(const name of ['cosmos-scene.mjs','cosmos-controller.mjs','paper-eye-cues.mjs']){const source=fs.readFileSync(new URL('./'+name,import.meta.url),'utf8');for(const m of source.matchAll(/from\s*['"](\.\/[^'"]+\.mjs[^'"]*)['"]/g))assert.ok(m[1].endsWith('?v='+(/\/neural-currents\.mjs/.test(m[1])?'neural-currents-20261010':/\/cosmos-scene\.mjs/.test(m[1])?'neural-currents-20261010':/\/(scene-targets|cosmos-controller|character-motion)\.mjs/.test(m[1])?'real-targets-20261010':version)),m[1]);}
 const src=fs.readFileSync(new URL('./neptune.mjs',import.meta.url),'utf8');assert.match(src,/const atmosphere=makeCosmosScene/);assert.doesNotMatch(src,/makeAtmosphere/);assert.match(src,/sceneTargets.observeReport\(report\)/);assert.match(src,/sceneTargets.disconnect\(\)/);assert.match(src,/visualViewport/);const css=fs.readFileSync(new URL('./paper-details.css',import.meta.url),'utf8');assert.match(css,/\.lower-deck\{pointer-events:none\}/);assert.match(css,/\.lower-deck>footer\{pointer-events:auto\}/);
});
test('scene cue caption remains outside six evidence streams and beam targets share real button geometry',()=>{const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8'),src=fs.readFileSync(new URL('./neptune.mjs',import.meta.url),'utf8');assert.ok(html.indexOf('id="sceneCue"')<html.indexOf('class="windows"'));assert.ok(html.indexOf('id="sceneCue"')<html.indexOf('id="openScoutStream"'));assert.match(src,/showMarketLabels:false,getMarketPositions:/);assert.match(src,/x:r.left\+r.width\/2-box.left/);});

test('integrated public Scout identity and neural-current cache chains remain consistent',()=>{
 const source=name=>fs.readFileSync(new URL('./'+name,import.meta.url),'utf8');
 const scoutImport=name=>source(name).match(/from ['"](\.\/public-scout\.mjs[^'"]*)['"]/)[1];
 assert.equal(scoutImport('neptune.mjs'),'./public-scout.mjs?v=public-scout-review-20261010');
 assert.equal(scoutImport('neptune.mjs'),scoutImport('team-worker-view.mjs'));
 const html=source('index.html'),team=source('team-work.mjs');
 for(const name of ['neptune','team-work'])assert.ok(html.includes('./'+name+'.mjs?v=public-scout-reviewed-20261010'));
 assert.ok(html.includes('./team-work.css?v=neural-currents-20261010'));
 assert.ok(team.includes('./agent-web.mjs?v=neural-currents-20261010'));
 assert.ok(team.includes('./team-worker-view.mjs?v=public-scout-review-20261010'));
 assert.ok(source('neptune.mjs').includes('./cosmos-controller.mjs?v=neural-currents-20261010'));
 assert.ok(source('cosmos-controller.mjs').includes('./cosmos-scene.mjs?v=neural-currents-20261010'));
 assert.ok(source('cosmos-scene.mjs').includes('./neural-currents.mjs?v=neural-currents-20261010'));
});
