import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {validateWorkEvent,createWorkStore,redactWorkText,workState,setupTeamWork,validateBuildHistory} from './team-work.mjs';
const at='2026-10-10T00:00:00.000Z',epoch=Date.parse(at);
function event(kind='started',index=0,delta=0){const start=new Date(epoch+index*10000).toISOString(),occurred=new Date(epoch+index*10000+delta).toISOString(),run='interface:'+start+':'+index;return {version:1,id:run+':'+kind,run_id:run,seq:kind==='started'?0:1,actor_id:'browser-interface',actor_kind:'browser_check',kind,occurred_at:occurred,task:'Refresh public paper status',source:{path:'preview/research-desk/neptune.mjs',function_name:'refreshFeed',commit:null,file_sha256:null},evidence:{kind:'local_invocation',id:run,at:start},output:{summary:kind==='started'?'Read-only status request started':kind==='failed'?'Status request failed; data unavailable':'Status response received and validated',exit_code:null},review:null};}
const ingest=(store,ev)=>store.ingest(ev,{now:Date.parse(ev.occurred_at)});
test('local invocation events have bounded immutable allowlisted fields and actual receipt time',()=>{const raw=event();raw.private='private input';const result=validateWorkEvent(raw,{now:epoch});assert.equal(result.private,undefined);assert.equal(result.received_at,at);assert.ok(Object.isFrozen(result));assert.ok(Object.isFrozen(result.source));assert.ok(Object.isFrozen(result.output));raw.output.summary='changed';assert.equal(result.output.summary,'Read-only status request started');});
test('missing proof, wrong actor, coding claims, unknown output and substituted revision fail closed',()=>{for(const mutate of [v=>delete v.evidence,v=>v.evidence.kind='test_run',v=>v.actor_kind='coding_agent',v=>v.actor_id='AGENT 001',v=>v.output.summary='Executed a backend scan',v=>v.source.commit='abcdef1',v=>v.source.file_sha256='a'.repeat(64),v=>v.review={verdict:'passed'},v=>v.seq=1,v=>v.id='bad',v=>v.run_id='arbitrary']){const ev=event();mutate(ev);assert.equal(validateWorkEvent(ev,{now:epoch}),null);}});
test('future and stale events are never active, even when received now',()=>{assert.equal(validateWorkEvent(event(),{now:epoch-1}),null);assert.equal(validateWorkEvent(event(),{now:epoch+60001}),null);const store=createWorkStore();ingest(store,event());assert.match(workState(store.snapshot(),epoch+15001).local,/WAITING/);assert.equal(workState(store.snapshot(),epoch+15001).coding,'NOT CONNECTED');assert.match(workState(store.snapshot(),epoch-1).local,/Timestamp unavailable/);});
test('duplicates do not update event or received time and conflicting terminal events cannot rewrite history',()=>{const store=createWorkStore();const start=event();assert.equal(ingest(store,start),true);assert.equal(store.ingest(start,{now:epoch+50}),false);assert.equal(store.snapshot().events.length,1);assert.equal(store.snapshot().events[0].received_at,at);assert.equal(ingest(store,event('completed',0,5)),true);assert.equal(ingest(store,event('failed',0,6)),false);assert.equal(store.snapshot().events[0].kind,'completed');assert.equal(ingest(store,start),false);assert.match(workState(store.snapshot(),epoch+6).local,/COMPLETED/);});
test('terminal events without corresponding observed start never prove execution',()=>{const store=createWorkStore();assert.equal(ingest(store,event('completed',0,10)),false);assert.equal(store.snapshot().events.length,0);assert.match(workState(store.snapshot()).local,/Waiting/);});
test('out-of-order terminal cannot turn a newer active run into completed',()=>{const store=createWorkStore();ingest(store,event());ingest(store,event('started',1));ingest(store,event('completed',0,11000));assert.match(workState(store.snapshot(),epoch+11000).local,/CHECKING/);assert.equal(workState(store.snapshot(),epoch+11000).event.run_id,event('started',1).run_id);});
test('bounded history rejects evicted start replays while accepting newer genuine runs',()=>{const store=createWorkStore();for(let i=0;i<80;i++){assert.equal(ingest(store,event('started',i)),true);assert.equal(ingest(store,event('completed',i,1)),true);}assert.equal(store.snapshot().events.length,40);assert.equal(ingest(store,event('started',0)),false);assert.equal(ingest(store,event('completed',0,1)),false);assert.equal(ingest(store,event('started',80)),true);});
test('redaction removes credentials, private paths, addresses, contact details, URLs and control characters',()=>{const text="password='hunter22'; Bearer ABCDEFG ghp_abcdefghijklmnopqrstuvwxyz /workspace/private/file /Users/Craig/file C:\\Users\\Craig\\file https://private.example/path?secret=yes someone@example.com 0x"+'a'.repeat(40)+' eyJabcdefghijk.abcdefghijk.abcdefghijk\u001b[31m';const safe=redactWorkText(text);assert.doesNotMatch(safe,/hunter22|ABCDEFG|ghp_|Craig|private.example|someone@|0xaaaa|eyJabc|\u001b/);assert.match(safe,/redacted/);assert.equal(redactWorkText('x'.repeat(20000),12000).length,12000);assert.equal(redactWorkText(null),'');});
class Node{constructor(){this.textContent='';this.children=[];this.events={};this.open=false;}set innerHTML(v){throw Error('unsafe HTML');}addEventListener(k,f){this.events[k]=f;}removeEventListener(k){delete this.events[k];}replaceChildren(...nodes){this.children=nodes;}showModal(){this.open=true;}close(){this.open=false;this.events.close?.();}}
function fixture(){const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8'),nodes=Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Node()])),events={},ticks=[];nodes.codeSource.textContent='async function refreshFeed(){\n const request = "read-only";\n return request;\n}';const document={hidden:false,getElementById:id=>nodes[id],createElement:()=>new Node(),addEventListener:(k,f)=>events[k]=f,removeEventListener:k=>delete events[k]};const app=setupTeamWork({document,now:()=>epoch,setInterval:fn=>{ticks.push(fn);return 1;},clearInterval:()=>{}});return {nodes,document,events,ticks,app};}
test('dialog opens repeatedly and closes without losing static source or generating fake events',()=>{const b=fixture();for(let i=0;i<5;i++)b.nodes.openTeamWork.events.click();assert.equal(b.nodes.teamWorkDialog.open,true);assert.equal(b.ticks.length,1);for(let i=0;i<30;i++)b.ticks[0]();assert.equal(b.app.store.snapshot().events.length,0);assert.match(b.nodes.teamFullSource.textContent,/async function refreshFeed/);assert.equal(b.nodes.teamCodingState.textContent,'NOT CONNECTED');b.nodes.closeTeamWork.events.click();assert.equal(b.nodes.teamWorkDialog.open,false);b.app.dispose();assert.equal(b.events['neptune:interface-work'],undefined);});
test('interface calls never promote coding status or create independent agent identities',()=>{const b=fixture();b.events['neptune:interface-work']({detail:event()});assert.equal(b.nodes.teamCodingState.textContent,'NOT CONNECTED');assert.match(b.nodes.teamLocalState.textContent,/CHECKING/);b.nodes.openTeamWork.events.click();assert.equal(b.nodes.teamWorkEvents.children.length,1);assert.match(b.nodes.teamWorkEvents.children[0].textContent,/Browser interface/);assert.doesNotMatch(b.nodes.teamWorkEvents.children[0].textContent,/AGENT 001/);});
test('one terminal, six original controls, portfolio, native dialog and no event animations remain',()=>{const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8'),css=fs.readFileSync(new URL('./team-work.css',import.meta.url),'utf8'),source=fs.readFileSync(new URL('./team-work.mjs',import.meta.url),'utf8');assert.equal((html.match(/class="team-terminal"/g)||[]).length,1);assert.equal((html.match(/class="stream-window"/g)||[]).length,6);assert.match(html,/id="openPortfolio"/);assert.match(html,/<dialog id="teamWorkDialog"/);assert.match(html,/No live coding workers are connected/);assert.doesNotMatch(css,/@keyframes|animation\s*:|transition\s*:/);assert.match(css,/overflow-wrap:anywhere/);assert.match(css,/grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);assert.doesNotMatch(source,/\.innerHTML\s*=|Math\.random|eval\(/);});

test('historical test receipts require real proof fields and never accept future dates or duplicate suites',()=>{
 const check={kind:'test_run',status:'completed',label:'Frontend tests',command:'node --test *.test.mjs',started_at:at,completed_at:at,exit_code:0,passed:10,failed:0,source_set_sha256:'a'.repeat(64),log_sha256:'b'.repeat(64)};
 assert.equal(validateBuildHistory({version:1,checks:[check]},{now:epoch})[0].passed,10);
 for(const changed of [{completed_at:new Date(epoch+1).toISOString()},{started_at:new Date(epoch+1).toISOString()},{log_sha256:null},{source_set_sha256:null},{exit_code:1},{failed:1},{command:'npm test'},{label:'AGENT 001'}])assert.equal(validateBuildHistory({version:1,checks:[{...check,...changed}]},{now:epoch}),null);
 assert.equal(validateBuildHistory({version:1,checks:[check,check]},{now:epoch}),null);
});

test('unchanged age refresh preserves opened evidence DOM and terminal duplicates stay clean',()=>{const b=fixture();b.events['neptune:interface-work']({detail:event()});b.nodes.openTeamWork.events.click();const row=b.nodes.teamWorkEvents.children[0];for(let i=0;i<4;i++)b.ticks[0]();assert.equal(b.nodes.teamWorkEvents.children[0],row);const store=createWorkStore();ingest(store,event());const end=event('completed',0,1);ingest(store,end);assert.equal(store.ingest(end,{now:epoch+2}),false);assert.equal(store.snapshot().rejected,0);});

test('actual refreshFeed emits one matched start/result and keeps report data out of telemetry',async()=>{
 const src=fs.readFileSync(new URL('./neptune.mjs',import.meta.url),'utf8');const code=src.slice(src.indexOf('function emitInterfaceWork'),src.indexOf('function igniteDecisions'));
 for(const failure of [false,true]){const events=[],nodes={refresh:{}},privateReport={balance:12345,wallet:'private-wallet'};let resolve;const wait=new Promise(r=>resolve=r);const ctx=vm.createContext({busy:false,report:null,connected:false,polls:0,$:id=>nodes[id],document:{dispatchEvent:e=>events.push(e.detail)},CustomEvent:class{constructor(type,{detail}){this.type=type;this.detail=detail;}},Date,recordRuntime(){},readReports:async()=>{await wait;if(failure)throw Error('timeout');return privateReport;},cueBridge:{observe(){},disconnect(){}},igniteDecisions(){},paperViewV2:()=>({label:'local'}),render(){}});vm.runInContext(code,ctx);const first=vm.runInContext('refreshFeed()',ctx);await vm.runInContext('refreshFeed()',ctx);assert.equal(events.length,1);resolve();await first;assert.equal(events.length,2);assert.equal(events[0].run_id,events[1].run_id);assert.equal(events[1].kind,failure?'failed':'completed');assert.equal(events[0].occurred_at,events[0].evidence.at);assert.doesNotMatch(JSON.stringify(events),/12345|private-wallet/);assert.ok(events.every(e=>validateWorkEvent(e,{now:Date.now()})));}
});
test('long source stays bounded and clearly announces safety trimming',()=>{const b=fixture();b.app.dispose();b.nodes.codeSource.textContent='async function refreshFeed(){'+ 'x'.repeat(24000)+'}';setupTeamWork({document:b.document,now:()=>epoch});assert.equal(b.nodes.teamFullSource.textContent.length,12000);assert.match(b.nodes.teamSourceIdentity.textContent,/length limit/);assert.equal(b.nodes.teamCodingState.textContent,'NOT CONNECTED');});
