import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import * as adapter from './status-v2.mjs';import {makeAtmosphere} from './depth-motion.mjs';
const src=fs.readFileSync(new URL('./neptune.mjs',import.meta.url),'utf8').replace(/^import .*\n/,'');
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/pending-v2.json',import.meta.url)));
class Node {
 constructor(){this.textContent='';this.children=[];this.events={};this.attrs={};this.dataset={};this.classList={remove(){},add(){},toggle(){}};}
 set innerHTML(v){throw Error('Unsafe HTML rendering');}
 setAttribute(k,v){this.attrs[k]=v;}
 append(...v){this.children.push(...v);}
 replaceChildren(...v){this.children=v;}
 addEventListener(k,fn){this.events[k]=fn;}
 querySelector(){return this.span??=new Node();}
 getBoundingClientRect(){return {width:390,height:844};}
 getContext(){return {setTransform(){},clearRect(){}};}
 showModal(){this.open=true;}
 close(){this.open=false;}
}
function boot(payload,{fail=false}={}){
 const ids=Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Node()]));
 const markets=[...html.matchAll(/data-market="([^"]+)"/g)].map(m=>{let n=new Node();n.dataset.market=m[1];return n;});
 const tabs=['code','trades','events'].map(p=>{let n=new Node();n.dataset.pane=p;return n;}),panes=tabs.map(t=>{let n=new Node();n.dataset.pane=t.dataset.pane;return n;});
 const docEvents={},mediaEvents={},windowEvents={},states=[];let requests=0;const document={hidden:false,body:new Node(),getElementById:id=>{assert.ok(ids[id],`missing #${id}`);return ids[id];},createElement:()=>new Node(),querySelectorAll:q=>q==='[data-market]'?markets:q==='.mobile-tabs button'?tabs:q==='.instrument'?panes:[],addEventListener(k,fn){docEvents[k]=fn;}};
 const context=vm.createContext({...adapter,setupPaperPanels:()=>({observe(){}}),makeAtmosphere:options=>{const a=makeAtmosphere(options);return {...a,setState(state){states.push(state);a.setState(state);}};},document,window:{addEventListener(k,fn){windowEvents[k]=fn;}},matchMedia:()=>({matches:true,addEventListener(k,fn){mediaEvents[k]=fn;}}),devicePixelRatio:1,requestAnimationFrame:()=>0,cancelAnimationFrame(){},setInterval(){},setTimeout,clearTimeout,AbortController,Intl,Date,fetch:async(url,options)=>{requests++;assert.equal(options.credentials,'omit');assert.equal(options.method,undefined);assert.match(url,/neptune_paper_v2_status/);if(fail)throw Error('offline');return {ok:true,json:async()=>payload};}});
 vm.runInContext(src,context);return {context,ids,markets,tabs,panes,document,docEvents,mediaEvents,windowEvents,states,requests:()=>requests};
}
const settle=()=>new Promise(resolve=>setImmediate(resolve));
function active(){let p=structuredClone(fixture),at=new Date().toISOString();Object.assign(p,{currency:'AUD',status:'running',heartbeat_at:at,quote_at:at,scan_at:at,scan_complete:true,message:'Nothing to report',account:{initial_cash:10000,cash:10000,available_cash:10000,reserved_cash:0,equity:10000,realized_pnl:0,unrealized_pnl:0,fees:0,fills:0},risk:{...p.risk,entry_paused:false}});return p;}
test('unconfigured UI initializes safely without seeded cash or fills',async()=>{const b=boot([{id:'neptune-paper-v2',payload:fixture}]);await settle();assert.equal(b.ids.equity.textContent,'—');assert.equal(b.ids.fills.textContent,'—');assert.match(b.ids.connection.textContent,/Account not created/);assert.match(b.ids.accountDetails.textContent,/AUD chosen/);assert.equal(b.ids.marketSelect.children.length,6);});
test('network failure has data-unavailable status, no fake no-op scan',async()=>{const b=boot(null,{fail:true});await settle();assert.match(b.ids.connection.textContent,/Data unavailable/);assert.doesNotMatch(b.ids.scanState.textContent,/Nothing to report/);});
test('actual text rendering neutralizes remote script markup',async()=>{const p=active(),attack='<img src=x onerror=alert(1)>';p.decisions=[{id:'decision1',at:p.heartbeat_at,asset:'ETH/USD',action:'hold',price:2000,quote_currency:'USD',reason:attack,source:'Kraken public spot',observation_id:'observation1',risk_base:null,stop:null,target:null,invalidation:null,confidence:'unvalidated',result:'no_trade'}];const b=boot([{id:'neptune-paper-v2',payload:p}]);await settle();assert.match(b.ids.events.children[0].textContent,/<img src=x onerror=alert\(1\)>/);assert.equal(b.ids.events.children[0].children.length,0);assert.match(b.ids.equity.textContent,/AUD/);assert.equal(b.ids.fillHistory.children.length,1);assert.match(b.ids.fillHistory.children[0].textContent,/No verified/);});
test('market selection, compact tabs and about close remain wired',async()=>{const b=boot([{id:'neptune-paper-v2',payload:active()}]);await settle();b.ids.marketSelect.value='UNI/USD';b.ids.marketSelect.events.change();assert.match(b.ids.connection.textContent,/UNI/);b.markets[1].events.click();assert.equal(b.ids.marketSelect.value,'SOL/USD');b.tabs[0].events.click();assert.equal(b.tabs[0].attrs['aria-pressed'],'true');b.ids.about.events.click();assert.equal(b.ids.aboutDialog.open,true);b.ids.closeAbout.events.click();assert.equal(b.ids.aboutDialog.open,false);});
test('repeated refresh clicks are coalesced and motion preference honored',async()=>{const b=boot([{id:'neptune-paper-v2',payload:fixture}]);b.ids.refresh.events.click();b.ids.refresh.events.click();await settle();assert.equal(b.requests(),1);assert.equal(b.ids.motion.attrs['aria-pressed'],'false');b.ids.motion.events.click();assert.equal(b.ids.motion.attrs['aria-pressed'],'true');});
test('USD protective exit renders pending conversion and keeps AUD PnL unknown',async()=>{const p=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-unsettled-v2.json',import.meta.url)));const b=boot([{id:'neptune-paper-v2',payload:p}]);await settle();assert.equal(b.ids.equity.textContent,'—');assert.match(b.ids.fillHistory.children[0].textContent,/USD proceeds awaiting AUD conversion/);assert.match(b.ids.resultsHistory.children[0].textContent,/AUD P&L pending conversion/);assert.match(b.ids.accountDetails.textContent,/unsettled proceeds USD/);});

test('system reduced motion and hidden document stop ambient work without financial changes',async()=>{const b=boot([{id:'neptune-paper-v2',payload:fixture}]);await settle();const equity=b.ids.equity.textContent;assert.equal(b.states.at(-1).enabled,false);b.mediaEvents.change({matches:false});assert.equal(b.states.at(-1).enabled,true);b.document.hidden=true;b.docEvents.visibilitychange();assert.equal(b.states.at(-1).visible,false);b.document.hidden=false;b.docEvents.visibilitychange();assert.equal(b.states.at(-1).visible,true);b.mediaEvents.change({matches:true});assert.equal(b.states.at(-1).enabled,false);assert.equal(b.ids.equity.textContent,equity);});
test('page cache exit pauses atmosphere and returning page restores preferences',async()=>{const b=boot([{id:'neptune-paper-v2',payload:fixture}]);await settle();b.ids.motion.events.click();b.windowEvents.pagehide();assert.equal(b.states.at(-1).visible,false);b.windowEvents.pageshow();assert.equal(b.states.at(-1).visible,true);assert.equal(b.states.at(-1).enabled,true);});

test('sixty-second server cadence is presented as an aged sample, never a live quote',async()=>{const p=active();p.quote_at=new Date(Date.now()-80000).toISOString();const b=boot([{id:'neptune-paper-v2',payload:p}]);await settle();assert.match(b.ids.valuation.textContent,/Last sampled/);assert.match(b.ids.valuation.textContent,/(80|81)s ago/);assert.match(b.ids.valuation.textContent,/not a live quote/);assert.match(b.ids.riskDetails.textContent,/server execution still requires quotes no older than 30s/);});
