import {readPortfolioSnapshot} from './portfolio-snapshot.mjs';
import {createLaserAudio} from './laser-audio.mjs?v=neptune-specialists-20261009';
import {readDailyPerformance} from './daily-performance.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import * as adapter from './status-v2.mjs?v=neptune-specialists-20261009';import {makeCosmosScene,createPaperCueBridge} from './cosmos-controller.mjs?v=neptune-specialists-20261009';
import {readResearchV1} from './research-v1.mjs';
const src=fs.readFileSync(new URL('./neptune.mjs',import.meta.url),'utf8').replace(/^import .*\n/,'');
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/pending-v2.json',import.meta.url)));
class Node {
 constructor(){this.textContent='';this.children=[];this.events={};this.attrs={};this.dataset={};this.classList={remove(){},add(){},toggle(){}};}
 set innerHTML(v){throw Error('Unsafe HTML rendering');}
 setAttribute(k,v){this.attrs[k]=v;}
 append(...v){this.children.push(...v);}
 replaceChildren(...v){this.children=v;}
 addEventListener(k,fn){this.events[k]=fn;}
 querySelector(){return this.span??=new Node();}
 getBoundingClientRect(){return {width:390,height:844};}
 getContext(){return {setTransform(){},clearRect(){}};}
 showModal(){this.open=true;}
 close(){this.open=false;}
}
function boot(payload,{fail=false,fetchWait,Audio}={}){
 const ids=Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Node()]));
 const markets=[...html.matchAll(/data-market="([^"]+)"/g)].map(m=>{let n=new Node();n.dataset.market=m[1];return n;});
 const tabs=['code','trades','events'].map(p=>{let n=new Node();n.dataset.pane=p;return n;}),panes=tabs.map(t=>{let n=new Node();n.dataset.pane=t.dataset.pane;return n;});
 const docEvents={},mediaEvents={},windowEvents={},states=[];let requests=0;const document={hidden:false,body:new Node(),getElementById:id=>{assert.ok(ids[id],`missing #${id}`);return ids[id];},createElement:()=>new Node(),querySelectorAll:q=>q==='[data-market]'?markets:q==='.mobile-tabs button'?tabs:q==='.instrument'?panes:[],addEventListener(k,fn){docEvents[k]=fn;},removeEventListener(k){delete docEvents[k];}};
 const context=vm.createContext({...adapter,createLaserAudio,readResearchV1,readDailyPerformance,readPortfolioSnapshot,setupPaperPanels:()=>({observe(){}}),createPaperCueBridge,makeCosmosScene:options=>{const a=makeCosmosScene({...options,createImage:()=>({addEventListener(){},removeEventListener(){}})});return {...a,setState(state){states.push(state);a.setState(state);}};},document,window:{AudioContext:Audio,addEventListener(k,fn){windowEvents[k]=fn;}},matchMedia:()=>({matches:true,addEventListener(k,fn){mediaEvents[k]=e=>{this.matches=e.matches;fn(e);};}}),devicePixelRatio:1,requestAnimationFrame:()=>0,cancelAnimationFrame(){},setInterval(){},setTimeout,clearTimeout,AbortController,Intl,Date,fetch:async(url,options)=>{requests++;assert.equal(options.credentials,'omit');assert.equal(options.method,undefined);assert.match(url,/neptune_paper_v2_status/);if(fetchWait)await fetchWait();if(fail)throw Error('offline');return {ok:true,json:async()=>payload};}});
 vm.runInContext(src,context);return {context,ids,markets,tabs,panes,document,docEvents,mediaEvents,windowEvents,states,requests:()=>requests};
}
const settle=()=>new Promise(resolve=>setImmediate(resolve));
function active(){let p=structuredClone(fixture),at=new Date().toISOString();Object.assign(p,{currency:'AUD',status:'running',heartbeat_at:at,quote_at:at,scan_at:at,scan_complete:true,message:'Nothing to report',account:{initial_cash:10000,cash:10000,available_cash:10000,reserved_cash:0,equity:10000,realized_pnl:0,unrealized_pnl:0,fees:0,fills:0},risk:{...p.risk,entry_paused:false}});return p;}
test('unconfigured UI initializes safely without seeded cash or fills',async()=>{const b=boot([{id:'neptune-paper-v2',payload:fixture}]);await settle();assert.equal(b.ids.equity.textContent,'—');assert.equal(b.ids.fills.textContent,'—');assert.match(b.ids.connection.textContent,/Account not created/);assert.match(b.ids.accountDetails.textContent,/AUD chosen/);assert.equal(b.ids.marketSelect.children.length,6);});
test('network failure has data-unavailable status, no fake no-op scan',async()=>{const b=boot(null,{fail:true});await settle();assert.match(b.ids.connection.textContent,/Data unavailable/);assert.doesNotMatch(b.ids.scanState.textContent,/Nothing to report/);});
test('actual text rendering neutralizes remote script markup',async()=>{const p=active(),attack='<img src=x onerror=alert(1)>';p.decisions=[{id:'decision1',at:p.heartbeat_at,asset:'ETH/USD',action:'hold',price:2000,quote_currency:'USD',reason:attack,source:'Kraken public spot',observation_id:'observation1',risk_base:null,stop:null,target:null,invalidation:null,confidence:'unvalidated',result:'no_trade'}];const b=boot([{id:'neptune-paper-v2',payload:p}]);await settle();assert.match(b.ids.events.children[0].textContent,/<img src=x onerror=alert\(1\)>/);assert.equal(b.ids.events.children[0].children.length,0);assert.match(b.ids.equity.textContent,/AUD/);assert.equal(b.ids.fillHistory.children.length,1);assert.match(b.ids.fillHistory.children[0].textContent,/No verified/);});
test('market selection and About close remain wired',async()=>{const b=boot([{id:'neptune-paper-v2',payload:active()}]);await settle();b.ids.marketSelect.value='UNI/USD';b.ids.marketSelect.events.change();assert.match(b.ids.connection.textContent,/UNI/);b.markets[1].events.click();assert.equal(b.ids.marketSelect.value,'SOL/USD');b.ids.about.events.click();assert.equal(b.ids.aboutDialog.open,true);b.ids.closeAbout.events.click();assert.equal(b.ids.aboutDialog.open,false);});
test('repeated refresh clicks are coalesced and motion preference honored',async()=>{const b=boot([{id:'neptune-paper-v2',payload:fixture}]);b.ids.refresh.events.click();b.ids.refresh.events.click();await settle();assert.equal(b.requests(),1);assert.equal(b.states.at(-1).enabled,false);b.mediaEvents.change({matches:false});assert.equal(b.states.at(-1).enabled,true);assert.equal(b.ids.motion,undefined);});
test('USD protective exit renders pending conversion and keeps AUD PnL unknown',async()=>{const p=JSON.parse(fs.readFileSync(new URL('./fixtures/engine-unsettled-v2.json',import.meta.url)));const b=boot([{id:'neptune-paper-v2',payload:p}]);await settle();assert.equal(b.ids.equity.textContent,'—');assert.match(b.ids.fillHistory.children[0].textContent,/USD proceeds awaiting AUD conversion/);assert.match(b.ids.resultsHistory.children[0].textContent,/AUD P&L pending conversion/);assert.match(b.ids.accountDetails.textContent,/unsettled proceeds USD/);});

test('system reduced motion and hidden document stop ambient work without financial changes',async()=>{const b=boot([{id:'neptune-paper-v2',payload:fixture}]);await settle();const equity=b.ids.equity.textContent;assert.equal(b.states.at(-1).enabled,false);b.mediaEvents.change({matches:false});assert.equal(b.states.at(-1).enabled,true);b.document.hidden=true;b.docEvents.visibilitychange();assert.equal(b.states.at(-1).visible,false);b.document.hidden=false;b.docEvents.visibilitychange();assert.equal(b.states.at(-1).visible,true);b.mediaEvents.change({matches:true});assert.equal(b.states.at(-1).enabled,false);assert.equal(b.ids.equity.textContent,equity);});
test('page cache exit pauses atmosphere and returning page restores preferences',async()=>{const b=boot([{id:'neptune-paper-v2',payload:fixture}]);await settle();b.mediaEvents.change({matches:false});b.windowEvents.pagehide();assert.equal(b.states.at(-1).visible,false);b.windowEvents.pageshow();assert.equal(b.states.at(-1).visible,true);assert.equal(b.states.at(-1).enabled,true);});

test('sixty-second server cadence is presented as an aged sample, never a live quote',async()=>{const p=active();p.quote_at=new Date(Date.now()-80000).toISOString();const b=boot([{id:'neptune-paper-v2',payload:p}]);await settle();assert.match(b.ids.valuation.textContent,/Last sampled/);assert.match(b.ids.valuation.textContent,/(80|81)s ago/);assert.match(b.ids.valuation.textContent,/not a live quote/);assert.match(b.ids.riskDetails.textContent,/server execution still requires quotes no older than 30s/);});

test('agent core follows validated freshness rather than persisted running status',async()=>{for(const [field,value,expected] of [[null,null,'CORE ONLINE'],['heartbeat_at',new Date(Date.now()-120000).toISOString(),'HEARTBEAT STALE'],['quote_at',null,'SAMPLED DATA UNAVAILABLE'],['scan_complete',false,'SCAN INCOMPLETE']]){const p=active();if(field)p[field]=value;const b=boot([{id:'neptune-paper-v2',payload:p}]);await settle();assert.equal(b.ids.agentPulse.textContent,expected);}const offline=boot(null,{fail:true});await settle();assert.equal(offline.ids.agentPulse.textContent,'DATA UNAVAILABLE');assert.match(html,/id="agentPulse"[^>]*>CORE WAITING/);});
test('first request stays pending until a verified empty response or failure, and retry recovers',async()=>{
 let release;const b=boot([],{fetchWait:()=>new Promise(r=>release=r)});assert.match(b.ids.connection.textContent,/Connecting/);assert.doesNotMatch(b.ids.feedSummary.textContent,/unavailable/);assert.equal(b.ids.equity.textContent,'—');release();await settle();assert.match(b.ids.connection.textContent,/Account not created/);
 let attempt=0;const failed=boot([],{fetchWait:async()=>{if(++attempt===1)throw Error('offline');}});await settle();assert.match(failed.ids.connection.textContent,/Data unavailable/);await failed.ids.refresh.events.click();assert.match(failed.ids.connection.textContent,/Account not created/);
});
function audioMock(){let count=0;const calls=[];class Audio{constructor(){count++;this.sampleRate=1;this.state='suspended';}createBuffer(){return {getChannelData:()=>new Float32Array(4)};}createBufferSource(){return {connect:n=>n,start(){}};}createBiquadFilter(){return {frequency:{value:0},connect:n=>n};}createGain(){return {gain:{value:0},connect:n=>n};}async resume(){calls.push('resume');if(Audio.reject)throw Error('audio blocked');this.state='running';}async suspend(){calls.push('suspend');this.state='suspended';}}return {Audio,calls,count:()=>count};}
test('page cache restores only opted-in sound and reports resume rejection truthfully',async()=>{
 const m=audioMock(),b=boot([],{Audio:m.Audio});await settle();b.windowEvents.pagehide();b.windowEvents.pageshow();await settle();assert.equal(m.count(),0);
 await b.docEvents.click();assert.equal(b.ids.audioStatus.textContent,'Ocean and laser sounds on. Ambient lasers are decorative.');assert.equal(b.docEvents.click,undefined);assert.equal(b.docEvents.keydown,undefined);assert.equal(m.count(),1);b.windowEvents.pagehide();await settle();assert.equal(b.ids.audioStatus.textContent,'Ocean and laser sounds paused while the page is hidden.');b.windowEvents.pageshow();await settle();assert.equal(b.ids.audioStatus.textContent,'Ocean and laser sounds on. Ambient lasers are decorative.');assert.equal(m.count(),1);
 b.windowEvents.pagehide();await settle();m.Audio.reject=true;b.windowEvents.pageshow();await settle();assert.equal(b.ids.audioStatus.textContent,'Sound unavailable in this browser session.');const resumes=m.calls.filter(x=>x==='resume').length;b.windowEvents.pageshow();await settle();assert.equal(m.calls.filter(x=>x==='resume').length,resumes);
});
test('scene cue bridge baselines initial history and only renders a new validated paper event',async()=>{
 const p=active(),decision=id=>({id,at:p.heartbeat_at,asset:'ETH/USD',action:'hold',price:2000,quote_currency:'USD',reason:'No setup',source:'Kraken public spot',observation_id:id+'obs',risk_base:null,stop:null,target:null,invalidation:null,confidence:'unvalidated',result:'no_trade'});p.decisions=[decision('initial')];let offline=false;const b=boot([{id:'neptune-paper-v2',payload:p}],{fetchWait:async()=>{if(offline)throw Error('offline');}});b.mediaEvents.change({matches:false});await settle();assert.match(b.ids.sceneCue.textContent,/Ambient/);p.decisions=[decision('new')];await b.ids.refresh.events.click();assert.match(b.ids.sceneCue.textContent,/PAPER REVIEW · UNVALIDATED/);assert.equal(b.ids.fills.textContent,'0');offline=true;await b.ids.refresh.events.click();assert.match(b.ids.sceneCue.textContent,/Ambient/);
});
test('cue queue is suspended and rebaselined across reduced motion, pagehide and hidden document',async()=>{const b=boot([]);await settle();const state=()=>vm.runInContext('cueBridge.snapshot()',b.context);assert.equal(state().active,false);b.mediaEvents.change({matches:false});assert.equal(state().active,true);b.windowEvents.pagehide();assert.equal(state().active,false);b.windowEvents.pageshow();assert.equal(state().active,true);assert.equal(state().seeded,false);b.document.hidden=true;b.docEvents.visibilitychange();assert.equal(state().active,false);b.document.hidden=false;b.docEvents.visibilitychange();assert.equal(state().active,true);b.mediaEvents.change({matches:true});assert.equal(state().active,false);});

test('six windows remain independently keyboard-openable with full evidence and close',async()=>{const b=boot([]);await settle();for(const [stream,name]of [['Scout','Scout'],['Depth','Depth'],['Pulse','Findings'],['Shield','Shield'],['Ledger','History'],['Watch','Runtime']]){b.ids['open'+stream+'Stream'].events.click();assert.equal(b.ids[name.toLowerCase()+'Dialog'].open,true);b.ids['close'+name].events.click();assert.equal(b.ids[name.toLowerCase()+'Dialog'].open,false);}assert.equal((html.match(/class="stream-window"/g)||[]).length,6);assert.doesNotMatch(html,/The ocean never sleeps|OCEAN INTELLIGENCE|PAPER ONLY|EVENT STREAM|id="motion"|id="sound"/);});
test('activity records only real request lifecycle, bounds history and never duplicates ledger rows',async()=>{const b=boot([{id:'neptune-paper-v2',payload:active()}]);await settle();assert.equal(b.ids.runtimeLog.children.length,2);assert.match(b.ids.runtimeLog.children[0].textContent,/Report validated/);assert.match(b.ids.runtimeLog.children[1].textContent,/request started/);assert.match(b.ids.ledgerOutput.textContent,/0 fills/);for(let i=0;i<25;i++)await b.ids.refresh.events.click();assert.equal(b.ids.runtimeLog.children.length,3);assert.equal(b.ids.runtimeHistory.children.length,40);assert.equal(b.ids.fillHistory.children.length,1);});
test('stale and offline data never becomes current stream activity',async()=>{const p=active();p.decisions=[{id:'old-decision',at:new Date(Date.now()-3600000).toISOString(),asset:'ETH/USD',action:'hold',price:2000,quote_currency:'USD',reason:'spread_too_wide',source:'Kraken public spot',observation_id:'old-obs',risk_base:null,stop:null,target:null,invalidation:null,confidence:'unvalidated',result:'blocked'}];const b=boot([{id:'neptune-paper-v2',payload:p}]);await settle();assert.equal(b.ids.depthStatus.textContent,'LAST REPORT');assert.equal(b.ids.pulseStatus.textContent,'LAST REPORT');assert.equal(b.ids.scoutStatus.textContent,'NOT CONNECTED');const off=boot(null,{fail:true});await settle();assert.equal(off.ids.watchStatus.textContent,'UNAVAILABLE');assert.equal(off.ids.ledgerStatus.textContent,'WAITING');});
test('optional catalogue remains a dated snapshot and does not expand execution markets',async()=>{const p=JSON.parse(fs.readFileSync(new URL('./fixtures/research-v1.json',import.meta.url)));const b=boot([{id:'neptune-paper-v2',payload:p}]);await settle();assert.equal(b.ids.scoutStatus.textContent,'SNAPSHOT');assert.match(b.ids.scoutOutput.textContent,/610 markets catalogued · live screen not connected/);assert.match(b.ids.scoutTime.textContent,/19:38:56/);assert.equal(b.ids.marketSelect.children.length,6);p.research_v1.catalogue.research_markets=9000;await b.ids.refresh.events.click();assert.equal(b.ids.scoutStatus.textContent,'NOT CONNECTED');assert.equal(b.ids.marketSelect.children.length,6);});
test('sound waits for the first eligible key gesture and detaches both activation listeners',async()=>{const m=audioMock(),b=boot([],{Audio:m.Audio});await settle();assert.equal(m.count(),0);await b.docEvents.keydown({type:'keydown',key:'Enter'});assert.equal(m.count(),1);assert.equal(b.docEvents.keydown,undefined);assert.equal(b.docEvents.click,undefined);assert.equal(b.ids.audioStatus.textContent,'Ocean and laser sounds on. Ambient lasers are decorative.');});

test('Escape and shortcut keys retain audio activation; About contains working mute and pause controls',async()=>{const m=audioMock(),b=boot([],{Audio:m.Audio});await settle();await b.docEvents.keydown({type:'keydown',key:'Escape'});await b.docEvents.keydown({type:'keydown',key:'r',ctrlKey:true});assert.equal(m.count(),0);assert.equal(typeof b.docEvents.click,'function');await b.docEvents.click({type:'click',button:0});await b.ids.accessSound.events.click();assert.equal(b.ids.audioStatus.textContent,'Ocean and laser sounds muted.');await b.ids.accessSound.events.click();assert.equal(b.ids.audioStatus.textContent,'Ocean and laser sounds on. Ambient lasers are decorative.');b.mediaEvents.change({matches:false});b.ids.accessMotion.events.click();assert.equal(b.states.at(-1).enabled,false);});

test('portfolio strip reads one shared account and opens the existing full-account dialog',async()=>{const p=active();Object.assign(p.account,{valuation_at:p.heartbeat_at,unsettled_usd:0});const b=boot([{id:'neptune-paper-v2',payload:p}]);await settle();assert.equal(b.ids.portfolioBalance.textContent,'10,000.00');assert.equal(b.ids.portfolioCash.textContent,'10,000.00');assert.equal(b.ids.portfolioExposure.textContent,'0.00');assert.equal(b.ids.portfolioPnl.textContent,'—');assert.equal(b.ids.portfolioPct.textContent,'Unavailable');assert.match(b.ids.portfolioState.textContent,/Valued/);b.ids.openPortfolio.events.click();assert.equal(b.ids.historyDialog.open,true);b.ids.closeHistory.events.click();assert.equal(b.ids.historyDialog.open,false);b.ids.openPortfolio.events.click();assert.equal(b.ids.historyDialog.open,true);assert.equal((html.match(/class="stream-window"/g)||[]).length,6);assert.match(html,/Portfolio <small>Simulated · AUD/);});
test('portfolio net PnL and exposure come from global valuation, never specialist allocation sums',async()=>{const p=active();Object.assign(p.account,{valuation_at:p.heartbeat_at,unsettled_usd:0,cash:9500,available_cash:9500,equity:10025});p.positions=[{asset:'ETH/USD',quote_currency:'USD',qty:1,entry_price:500,entry_fx:1.5,cost_base:500,stop:null,target:null,invalidation:null,initial_risk_base:1,trailing_active:false,last_bid:525,quote_at:p.heartbeat_at,opened_at:p.heartbeat_at}];p.specialist_accounts={accounts:[{cash:1e9}]};const b=boot([{id:'neptune-paper-v2',payload:p}]);await settle();assert.equal(b.ids.portfolioBalance.textContent,'10,025.00');assert.equal(b.ids.portfolioCash.textContent,'9,500.00');assert.equal(b.ids.portfolioExposure.textContent,'525.00');assert.equal(b.ids.portfolioPnl.textContent,'—');assert.equal(b.ids.pnl.textContent.includes('25.00'),true);});
test('portfolio unknown/stale/future valuations and stopped/offline feeds never retain a current balance',async()=>{for(const mode of ['missing','old','future','offline']){const p=active();Object.assign(p.account,{valuation_at:p.heartbeat_at,unsettled_usd:0});if(mode==='missing')delete p.account.valuation_at;if(mode==='old')p.account.valuation_at=new Date(Date.now()-91000).toISOString();if(mode==='future')p.account.valuation_at=new Date(Date.now()+60000).toISOString();if(mode==='stopped')p.status='stopped';const b=boot([{id:'neptune-paper-v2',payload:p}],{fail:mode==='offline'});await settle();for(const key of ['portfolioBalance','portfolioExposure','portfolioPnl'])assert.equal(b.ids[key].textContent,'—');assert.equal(b.ids.portfolioCash.textContent,mode==='offline'?'—':'10,000.00');assert.doesNotMatch(b.ids.portfolioState.textContent,/^Valued/);}});
test('portfolio disconnect clears previous sample, pending-FX exposure stays unknown',async()=>{const p=active();Object.assign(p.account,{valuation_at:p.heartbeat_at,unsettled_usd:0});let offline=false;const b=boot([{id:'neptune-paper-v2',payload:p}],{fetchWait:async()=>{if(offline)throw Error('offline');}});await settle();assert.equal(b.ids.portfolioBalance.textContent,'10,000.00');offline=true;await b.ids.refresh.events.click();assert.equal(b.ids.portfolioBalance.textContent,'—');assert.match(b.ids.portfolioState.textContent,/unavailable/);offline=false;p.account.unsettled_usd=10;await b.ids.refresh.events.click();assert.equal(b.ids.portfolioExposure.textContent,'—');});
test('Today portfolio shows signed server-baseline AUD and percent with partial-day coverage',async()=>{const p=active();Object.assign(p.account,{valuation_at:p.heartbeat_at,unsettled_usd:0,equity:10025,cash:10025,available_cash:10025});const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Perth',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(p.heartbeat_at));p.daily_performance={status:'available',timezone:'Australia/Perth',day,coverage:'since_first_observation',baseline_at:p.heartbeat_at,baseline_equity:10000,net_external_flows:0,current_equity:10025,observed_at:p.heartbeat_at,net_pnl:25,pct:.25,source_revision:3};const b=boot([{id:'neptune-paper-v2',payload:p}]);await settle();assert.equal(b.ids.portfolioPnl.textContent,'+25.00');assert.equal(b.ids.portfolioPct.textContent,'+0.25%');assert.match(b.ids.portfolioSince.textContent,/Since .* Perth/);assert.match(b.ids.dailyDetails.textContent,/since first observed today/);assert.match(b.ids.dailyDetails.textContent,/not a full midnight-to-now return/);});

test('OS reduced motion remains authoritative when About motion is toggled',async()=>{const b=boot([]);await settle();b.ids.accessMotion.events.click();assert.equal(b.states.at(-1).enabled,false);assert.equal(vm.runInContext('cueBridge.snapshot().active',b.context),false);});
test('incomplete market screening does not erase fresh flat portfolio cash/equity',async()=>{const p=active();Object.assign(p,{status:'data_stale',quote_at:null,scan_complete:false});Object.assign(p.account,{valuation_at:p.heartbeat_at,unsettled_usd:0});const b=boot([{id:'neptune-paper-v2',payload:p}]);await settle();assert.match(b.ids.connection.textContent,/Sampled data unavailable/);assert.equal(b.ids.portfolioCash.textContent,'10,000.00');assert.equal(b.ids.portfolioBalance.textContent,'10,000.00');assert.equal(b.ids.portfolioExposure.textContent,'0.00');assert.match(b.ids.portfolioState.textContent,/screen incomplete/);p.account.valuation_at=new Date(Date.now()-91000).toISOString();await b.ids.refresh.events.click();assert.equal(b.ids.portfolioCash.textContent,'10,000.00');assert.equal(b.ids.portfolioBalance.textContent,'—');assert.match(b.ids.portfolioState.textContent,/Cash verified/);p.heartbeat_at=new Date(Date.now()-91000).toISOString();await b.ids.refresh.events.click();assert.equal(b.ids.portfolioCash.textContent,'—');});
