import test from 'node:test';import assert from 'node:assert/strict';
import {signedMove,signedMovePercent,dailyMoveFx,dailyMoveMarkup,createHoldingDailyController} from '../portfolio/holding-daily-view.mjs';
import {parseHoldingDayChange,holdingDayChangeTarget} from '../portfolio/holding-day-change.mjs';
import {groupHoldings} from '../portfolio/model.mjs';
const now=Date.parse('2026-10-07T13:10:00Z'),asset='0x'+'1'.repeat(40),pool='0x'+'2'.repeat(40),opposite='0x'+'3'.repeat(40),holding={key:'1:'+asset,chainId:1,assetId:asset,pricePairAddress:pool,quantity:'3'};
function comparison(price='110',base='100'){const target=holdingDayChangeTarget({chainId:1,assetId:asset,poolAddress:pool}),at=Date.parse('2026-10-07T12:00:00Z')/1000;return parseHoldingDayChange({target,nowMs:now,metadataText:JSON.stringify({data:[{type:'pool',id:'eth_'+pool,attributes:{address:pool},relationships:{base_token:{data:{type:'token',id:'eth_'+asset}},quote_token:{data:{type:'token',id:'eth_'+opposite}}}}]}),ohlcvText:JSON.stringify({data:{type:'ohlcv_request_response',attributes:{ohlcv_list:[[at,price,price,price,price,'1'],[at-86400,base,base,base,base,'1']]}},meta:{base:{address:asset},quote:{address:opposite}}})});}
const fx={usd_to_aud:'1.5',fx_observed_at:'2026-10-07T13:00:00Z',fx_source:'https://www.ecb.europa.eu/',provenance:{valuation:{fx:{provider_observation_date:'2026-10-02'}}}};
const tick=()=>new Promise(setImmediate);
test('signed formatting preserves tiny values, negatives, zero and large exact quantities',()=>{assert.equal(signedMove('+0.00000000001','USD'),'+<US$0.01');assert.equal(signedMove('-12.345','AUD'),'−A$12.35');assert.equal(signedMove('0','USD'),'US$0.00');assert.equal(signedMovePercent({numerator:'-1',denominator:'1000000000000000000000000000000'}),'−<0.01%');assert.equal(signedMovePercent({numerator:'10',denominator:'1'}),'+10.00%');});
test('saved AUD FX requires real current provenance and cannot reuse an old or future rate',()=>{assert.equal(dailyMoveFx(fx,now).date,'2026-10-02');for(const snapshot of [null,{...fx,usd_to_aud:null},{...fx,fx_observed_at:'2026-10-08T00:00:00Z'},{...fx,provenance:{valuation:{fx:{provider_observation_date:'2026-09-01'}}}}])assert.equal(dailyMoveFx(snapshot,now),null);});
test('daily movement shows exact dollars and percentage for selected quantity without changing saved value',()=>{const before=JSON.stringify(holding);assert.match(dailyMoveMarkup(holding,comparison(),'USD',fx,now),/\+US\$30\.00 \(\+10\.00%\)/);assert.match(dailyMoveMarkup(holding,comparison(),'AUD',fx,now,true),/\+A\$45\.00/);assert.match(dailyMoveMarkup(holding,comparison(),'AUD',fx,now,true),/2026-10-02 reference rate/);assert.match(dailyMoveMarkup(holding,comparison('90'),'USD',fx,now),/is-down.*−US\$30\.00 \(−10\.00%\)/);assert.equal(JSON.stringify(holding),before);});
test('missing FX, stale candles and missing history never look like zero or fresh gains',()=>{assert.match(dailyMoveMarkup(holding,comparison(),'AUD',null,now),/FX needs refresh/);assert.match(dailyMoveMarkup(holding,comparison(),'USD',fx,now+2*3600000),/old candles/);assert.doesNotMatch(dailyMoveMarkup(holding,{status:'unavailable'},'USD',fx,now),/0\.00|is-up|is-down/);});
test('the selected quote carries its pool identity and liquid plus locked quantities are counted once',()=>{const row={chain_id:1,asset_id:asset,symbol:'SYN',decimals:0,balance_raw:'3',price_status:'observed',price_usd:'110',price_observed_at:'2026-10-07T13:00:00Z',price_source:'Synthetic',price_pair_address:pool},m={snapshot:fx,balances:[row],stakes:[{...row,principal_raw:'2',status:'active'}]};const [h]=groupHoldings(m);assert.equal(h.quantity,'5');assert.equal(h.pricePairAddress,pool);assert.match(dailyMoveMarkup(h,comparison(),'USD',fx,now),/US\$50\.00/);});
test('scope changes abort reads and late old-account results cannot reappear',async()=>{const pending=[],calls=[],source={get:async(input,{signal})=>{calls.push({input,signal});return await new Promise(resolve=>pending.push(resolve));}};let changes=0;const view=createHoldingDailyController({source,now:()=>now,onChange:()=>changes++});view.setScope({account:'private-A'},[{...holding,wallet:'private-wallet',quantity:'999'}]);view.setScope({account:'private-B'},[holding]);assert.equal(calls[0].signal.aborted,true);assert.deepEqual(Object.keys(calls[0].input).sort(),['assetId','chainId','poolAddress']);assert.doesNotMatch(JSON.stringify(calls[0].input),/private|999/);const before=changes;pending[0](comparison());await tick();assert.equal(changes,before);pending[1](comparison());await tick();assert.equal(changes,before+1);assert.equal(view.comparison(holding).status,'ready');view.clear();assert.equal(view.comparison(holding).status,'unavailable');});
test('one scope deduplicates calls, caps source lookups at 12 per minute and retains limits across switches',async()=>{const calls=[],source={get:async input=>{calls.push(input);return {status:'unavailable',reason:'missing_24h_baseline'};}};const view=createHoldingDailyController({source,now:()=>now}),ctx={};const holdings=Array.from({length:20},(_,i)=>({...holding,assetId:'0x'+(i+10).toString(16).padStart(40,'0')}));view.setScope(ctx,[...holdings,...holdings]);for(let i=0;i<50;i++)await tick();assert.equal(calls.length,12);view.setScope(ctx,holdings);await tick();assert.equal(calls.length,12);view.setScope({},[holding]);await tick();assert.equal(calls.length,12);assert.equal(view.comparison(holding).reason,'rate_budget');view.clear();});
test('hidden-tab work pauses, refreshes only public targets on return and sign-out invalidates completion',async()=>{let clock=now,pending;const signals=[],source={get:async(input,{signal})=>{signals.push(signal);return await new Promise(resolve=>pending=resolve);}};const view=createHoldingDailyController({source,now:()=>clock});view.setScope({},[holding]);view.pause();assert.equal(signals[0].aborted,true);pending(comparison());await tick();clock+=61000;view.refresh();assert.equal(signals.length,2);view.clear();pending(comparison());await tick();assert.equal(view.comparison(holding).status,'unavailable');});

test('FX retrieval timestamps cannot replace a malformed or absent reference date',()=>{
 const missing={...fx,provenance:{valuation:{fx:{observed_at_basis:'retrieved_at'}}}};
 assert.equal(dailyMoveFx(missing,now),null);
 const malformed={...fx,provenance:{valuation:{fx:{provider_observation_date:'2026-02-30',provider_as_of:'2026-10-07T00:00:00Z'}}}};
 assert.equal(dailyMoveFx(malformed,now),null);
 const precise={...fx,provenance:{valuation:{fx:{provider_as_of:'2026-10-07T00:00:00Z'}}}};
 assert.equal(dailyMoveFx(precise,now).date,'2026-10-07');
});
test('request reservations remain for a full minute after completion, including scope cancellation',async()=>{
 let clock=now,resolve,calls=0;const source={get:async()=>{calls++;if(calls===1)await new Promise(r=>resolve=r);return {status:'unavailable'};}},view=createHoldingDailyController({source,now:()=>clock});
 const holdings=Array.from({length:12},(_,i)=>({...holding,assetId:'0x'+(i+10).toString(16).padStart(40,'0')}));view.setScope({},holdings);clock+=7000;resolve();for(let i=0;i<30;i++)await tick();assert.equal(calls,12);
 clock=now+60000;view.setScope({},[holding]);await tick();assert.equal(calls,12);
 clock=now+67000;view.setScope({},[holding]);await tick();assert.equal(calls,13);view.clear();
});
