import test from 'node:test';import assert from 'node:assert/strict';import {createWalletHistoryController} from '../portfolio/wallet-history-controller.mjs';
const query={accountId:'test-account',walletIds:['test-wallet'],range:'1d',currency:'USD'};
const build=()=>({status:'ready',data:{schema_version:1,status:'building',scope:{account_id:'test-account',wallet_ids:['test-wallet']},query:{range:'1d',currency:'USD'},progress:{completed_steps:1,total_steps:13,phase:'balances',can_continue:true}}});
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)}};
test('scope switch cancels old request and stale completion cannot replace the new state',async()=>{const a=deferred(),b=deferred(),signals=[];let calls=0;const c=createWalletHistoryController({read:args=>{signals.push(args.signal);return calls++?b.promise:a.promise;}});const first=c.load(query),second=c.load({...query,walletIds:['other']});assert.equal(signals[0].aborted,true);b.resolve({status:'unavailable',code:'LATEST'});await second;a.resolve(build());await first;assert.equal(c.getState().error,'LATEST');assert.deepEqual(c.getState().query.walletIds,['other']);});
test('cancel, clear and destroy invalidate in-flight private responses',async()=>{for(const method of ['cancel','clear','destroy']){const gate=deferred();const c=createWalletHistoryController({read:()=>gate.promise});const run=c.load(query);c[method]();gate.resolve(build());await run;assert.notEqual(c.getState().status,'building');if(method!=='cancel')assert.equal(c.getState().query,null);}});
test('building progress is scoped and an explicit continuation sends the same query',async()=>{const seen=[];const c=createWalletHistoryController({read:async args=>{seen.push(args);return build();}});await c.load(query);assert.equal(c.getState().status,'building');await c.load();assert.equal(seen.length,2);assert.equal(seen[1].accountId,query.accountId);assert.deepEqual(seen[1].walletIds,query.walletIds);assert.equal(c.getState().progress.completed_steps,1);});
test('malformed or cross-wallet progress does not invite an unsafe continuation',async()=>{for(const change of [r=>r.data.scope.wallet_ids=['foreign'],r=>r.data.progress.total_steps=0,r=>r.data.query.currency='AUD']){const response=build();change(response);const c=createWalletHistoryController({read:async()=>response});await c.load(query);assert.equal(c.getState().error,'HISTORY_RESPONSE_INVALID');}});
test('signed-out response clears selected scope and no polling timer is created',async()=>{const states=[];let calls=0;const c=createWalletHistoryController({read:async()=>{calls++;return {status:'signed-out'};},onChange:state=>states.push(state)});await c.load(query);assert.equal(c.getState().query,null);assert.equal(c.getState().status,'signed-out');await Promise.resolve();assert.equal(calls,1);assert.equal(states.length,2);});
