import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeWalletHistory} from '../portfolio/wallet-history.mjs';
import {holdingsChartData} from '../portfolio/holdings-chart.mjs';
const NOW=Date.parse('2026-10-04T12:00:00Z'),stamp=t=>new Date(t).toISOString();
const options={accountId:'synthetic-account',walletIds:['synthetic-wallet'],range:'1d',currency:'USD',now:NOW};
function fixture(){return {schema_version:1,status:'partial',scope:{account_id:options.accountId,wallet_ids:[...options.walletIds],scope_key:'synthetic-liquid-coverage',chain_ids:['ethereum'],positions:'liquid'},query:{range:'1d',currency:'USD'},source:{provider:'Synthetic historical test',method:'historical_block_balances_x_historical_prices',retrieved_at:stamp(NOW),attribution:'Synthetic fixture, no real data'},window:{actual_from:stamp(NOW-1800000),actual_to:stamp(NOW-600000),sample_interval_seconds:600},coverage:{requested_wallet_count:1,included_wallet_count:1,excluded_wallet_ids:[],complete:false,exclusions:[{code:'PROTOCOL_HISTORY_UNSUPPORTED'}],warnings:[]},points:[{at:stamp(NOW-1800000),value:'100',coverage_key:'same',complete:false},{at:stamp(NOW-1200000),value:'102.000000000000000001',coverage_key:'same',complete:false},{at:stamp(NOW-600000),value:'101.125',coverage_key:'same',complete:false}],change:{amount:'9999999'},error_code:null};}
test('uses actual exact values, recomputes honest change and draws real ebb/flow',()=>{const s=normalizeWalletHistory(fixture(),options);assert.equal(s.change,'1.125');assert.equal(s.changeFormatted,'+US$1.13');assert.equal(s.percentFormatted,'+1.13%');assert.equal(s.points[1].value,'102.000000000000000001');assert.equal(holdingsChartData(s).connectionCount,2);assert.equal(s.partialCoverage,true);});
test('wallet/account/currency/range substitution and malformed identities fail closed',()=>{for(const mutate of [r=>r.scope.account_id='other',r=>r.scope.wallet_ids=['other'],r=>r.query.currency='AUD',r=>r.query.range='max',r=>r.scope.positions='all',r=>r.scope.wallet_ids.push('synthetic-wallet')]){const r=fixture();mutate(r);assert.throws(()=>normalizeWalletHistory(r,options));}});
test('stale/future source and duplicated/reversed points cannot masquerade as current history',()=>{for(const mutate of [r=>r.source.retrieved_at=stamp(NOW-3600000),r=>r.source.retrieved_at=stamp(NOW+120000),r=>r.points[1].at=r.points[0].at,r=>r.points.reverse(),r=>r.points[1].value=-1,r=>r.points[1].value='NaN']){const r=fixture();mutate(r);assert.throws(()=>normalizeWalletHistory(r,options));}});
test('null values remain gaps and suppress comparison',()=>{const r=fixture();r.points[1].value=null;const s=normalizeWalletHistory(r,options);assert.equal(s.change,null);assert.equal(s.reason,'history_data_gap');assert.equal(holdingsChartData(s).runs.length,0);});
test('coverage changes break connections and do not become profit',()=>{const r=fixture();r.points[1].coverage_key='different';const s=normalizeWalletHistory(r,options);assert.equal(s.changeAvailable,false);assert.equal(s.reason,'scope_changed');assert.equal(holdingsChartData(s).runs.length,0);});
test('missing intervals split the actual line without inserting a value',()=>{const r=fixture();r.points.splice(1,1);const s=normalizeWalletHistory(r,options);assert.equal(s.points.length,2);assert.equal(s.reason,'history_data_gap');assert.equal(holdingsChartData(s).runs.length,0);});
test('AUD remains independent and zero baseline does not invent a percentage',()=>{const r=fixture();r.query.currency='AUD';r.points[0].value='0';const s=normalizeWalletHistory(r,{...options,currency:'AUD'});assert.equal(s.changeFormatted,'+A$101.13');assert.equal(s.percentFormatted,null);});
test('unavailable range is empty rather than a zero history',()=>{const r=fixture();r.status='unavailable';r.points=[];r.window.actual_from=null;r.window.actual_to=null;const s=normalizeWalletHistory(r,options);assert.equal(s.points.length,0);assert.equal(s.change,null);assert.equal(s.reason,'history_unavailable');});

import fs from 'node:fs';
test('production-generated synthetic pilot contract renders 13 real supplied points and the exact asset subset',()=>{const r=JSON.parse(fs.readFileSync(new URL('./fixtures/history-pilot.synthetic.json',import.meta.url),'utf8'));const s=normalizeWalletHistory(r,{accountId:r.scope.account_id,walletIds:r.scope.wallet_ids,range:'1d',currency:'USD',now:Date.parse(r.source.retrieved_at)});assert.equal(s.points.length,13);assert.equal(s.change,'-4000');assert.equal(holdingsChartData(s).connectionCount,12);assert.match(s.assetLabel,/ETH/);assert.match(s.assetLabel,/DRAGONX/);r.coverage.included_asset_ids=['native'];const only=normalizeWalletHistory(r,{accountId:r.scope.account_id,walletIds:r.scope.wallet_ids,range:'1d',currency:'USD',now:Date.parse(r.source.retrieved_at)});assert.equal(only.assetLabel,'ETH');});
