const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {validItem,validDocument,render}=require('../bacon-shortlist.js');
// Synthetic test data only. Never committed to the published data directory.
const item={id:'fixture',symbol:'TEST',pair:'TEST/USDT',currency:'USDT',side:'buy',entry:[100,101],stop:90,targets:[120,130],publishedAt:'2026-09-30T10:00:00Z',expiresAt:'2026-10-01T10:00:00Z',sourceUrl:'https://example.com/source',sourceName:'Fixture source',rationale:'Test only',levelBasis:'source-explicit'};
const doc={schema:1,paperOnly:true,date:'2026-09-30',checkedAt:'2026-09-30T12:00:00Z',deadlineAt:'2026-09-30T22:00:00Z',status:'ready',summary:'Paper shortlist updated.',sourceChecks:[],items:[item],watchlist:[]};
const now=Date.parse('2026-09-30T12:01:00Z');
test('complete paper cards show all levels currency source and date',()=>{assert.ok(validDocument(doc));const html=render(doc,now);for(const text of ['Entry · USDT','Stop · USDT','Targets · USDT','100–101','120 / 130','https://example.com/source','30 Sept 2026','Paper buy'])assert.ok(html.includes(text),text);assert.ok(!html.includes('<button'));assert.ok(!html.includes('data-buy'));});
test('incomplete, inverted and nonnumeric levels are rejected',()=>{for(const update of [{stop:null},{stop:102},{entry:[101,100]},{entry:'100'},{targets:[]},{targets:[99]},{currency:''},{sourceUrl:'javascript:alert(1)'},{expiresAt:'bad'},{levelBasis:'guessed'}])assert.equal(validItem({...item,...update}),false,JSON.stringify(update));});
test('short geometry is checked',()=>{assert.ok(validItem({...item,side:'sell',stop:110,targets:[90]}));assert.ok(!validItem({...item,side:'sell'}));});
test('empty report is honest and partial access stays visible',()=>{const html=render({...doc,items:[],status:'partial',summary:'Nothing to report.',sourceChecks:[{name:'Instagram',url:'https://instagram.com/VirtualBacon0x/',status:'unavailable',checkedAt:doc.checkedAt,detail:'Login required'}]},now);for(const text of ['Nothing to report.','No complete, current paper setup','Some sources','Login required'])assert.ok(html.includes(text));});
test('stale, expired and duplicate reports cannot look newly actionable',()=>{const html=render({...doc,items:[item,item]},now);assert.equal((html.match(/<h3>TEST<\/h3>/g)||[]).length,1);const old=render(doc,now+28*3600000);assert.ok(old.includes('Research is stale'));assert.ok(old.includes('setup(s) withheld'));assert.ok(!old.includes('Paper buy'));});
test('remote text cannot inject markup or unsafe links',()=>{const html=render({...doc,summary:'<img src=x onerror=alert(1)>',watchlist:[{symbol:'X',note:'<script>alert(1)</script>',sourceUrl:'javascript:alert(1)',missing:['stop']}]},now);assert.ok(!html.includes('<script>'));assert.ok(!html.includes('href="javascript:'));assert.ok(html.includes('&lt;img'));});
test('published shortlist obeys contract and has no synthetic items',()=>{const d=JSON.parse(fs.readFileSync('data/bacon-shortlist.json'));assert.ok(validDocument(d));assert.ok(d.items.every(x=>x.symbol!=='TEST'));});
test('HBAR seed and existing saved-trade storage keys remain unchanged',()=>{const html=fs.readFileSync('index.html','utf8');assert.ok(html.includes('const stake=1000, entry=0.10283, quantity=stake/entry;'));assert.ok(html.includes("seaChefBaconTradesV1"));assert.ok(html.includes("seaChefPaperHBAR20260930v1"));});
