import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {PGlite} from '@electric-sql/pglite';
const base=new URL('./fixtures/build5/',import.meta.url);
async function setup(){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create function auth.uid() returns uuid language sql as $$select null::uuid$$;create table public.paper_control(id int,owner_id uuid);create schema net;create schema cron;create table net.calls(id bigserial primary key,url text,body jsonb);create table net._http_response(id bigint,status_code int,content_type text,headers jsonb,content text,timed_out bool,error_msg text,created timestamptz);create function net.http_get(url text,params jsonb,headers jsonb,timeout_milliseconds int) returns bigint language sql as $$insert into net.calls(url) values(url) returning id$$;create function net.http_post(url text,body jsonb,params jsonb,headers jsonb,timeout_milliseconds int) returns bigint language sql as $$insert into net.calls(url,body) values(url,body) returning id$$;create table cron.job_run_details(jobid bigint,return_message text);create table cron.job(jobid bigint,jobname text,username text,database text,command text,active bool);create function cron.alter_job(job_id bigint,active boolean) returns void language sql as $$update cron.job set active=$2 where jobid=$1$$;create function cron.unschedule(job_id bigint) returns boolean language sql as $$update cron.job set active=false where jobid=$1 returning true$$;`);
for(const f of ['schema.sql','core.sql','owner-access.sql','collector.sql'])await db.exec(await fs.readFile(new URL(f,base),'utf8'));
await db.exec(`insert into neptune_v2_private.build_metadata values(5,'1e1907c0fca5ffcd54a2f25e957b081be4815e097dbbbaf9073e97951c7fb5af','00f878a855d0b8f65b57473bc0d2c89efde617b72ca5643b14ed05aa55afa8f8',now());select neptune_v2_private.initialize('AUD');insert into public.neptune_paper_v2_control(id,owner_id) values('neptune-paper-v2','00000000-0000-0000-0000-000000000001');select neptune_v2_private.allocate_specialists();select neptune_v2_private.sync_control();insert into neptune_v2_private.feed_control(id,started_at,contract_verified,job_id,job_owner,job_database) values(true,clock_timestamp(),true,1,current_user,current_database());insert into cron.job values(1,'neptune-v2-feed-guard',current_user,current_database(),'set statement_timeout=''8s''; select neptune_v2_private.feed_tick();',true);`);return db;}
const patch=()=>fs.readFile(new URL('../ATOMIC-NATIVE-UPGRADE.sql',import.meta.url),'utf8');
test('atomic native upgrade preserves allocated root and historical rows, leaves owner stopped',async()=>{const db=await setup();const before=(await db.query('select to_jsonb(a) p from neptune_v2_private.account a')).rows[0].p;await db.exec(await patch());const after=(await db.query('select to_jsonb(a) p from neptune_v2_private.account a')).rows[0].p;assert.deepEqual(after,before);assert.equal((await db.query('select count(*) n from net.calls')).rows[0].n,0);assert.equal((await db.query('select enabled from public.neptune_paper_v2_control')).rows[0].enabled,false);await assert.rejects(db.exec(await patch()),/Exact reviewed build5/);await db.close();});
test('running root rejects entire upgrade before DDL',async()=>{const db=await setup();await db.exec('update public.neptune_paper_v2_control set enabled=true;select neptune_v2_private.sync_control()');await assert.rejects(db.exec(await patch()),/Stop/);await db.exec('rollback');assert.equal((await db.query("select to_regnamespace('neptune_mv_private') n")).rows[0].n,null);await db.close();});
test('altered predecessor body rejects entire upgrade',async()=>{const db=await setup();await db.exec("create or replace function neptune_v2_private.universe() returns text[] language sql immutable security invoker set search_path='' as $$select array['ETH/USD']::text[]$$");await assert.rejects(db.exec(await patch()),/Unexpected predecessor/);await db.exec('rollback');assert.equal((await db.query("select to_regnamespace('neptune_mv_private') n")).rows[0].n,null);await db.close();});
test('existing private access drift is rejected without silently revoking it',async()=>{const db=await setup();await db.exec('grant execute on function neptune_v2_private.num(text) to anon');await assert.rejects(db.exec(await patch()),/Existing private ACL drift/);await db.exec('rollback');assert.equal((await db.query("select has_function_privilege('anon','neptune_v2_private.num(text)','execute') p")).rows[0].p,true);await db.close();});
test('new private objects deny malicious default client grants after atomic install',async()=>{const db=await setup();await db.exec('alter default privileges grant all on tables to anon,authenticated,service_role;alter default privileges grant execute on functions to anon,authenticated,service_role');await db.exec(await patch());for(const role of ['anon','authenticated','service_role']){assert.equal((await db.query("select has_schema_privilege($1,'neptune_mv_private','usage') p",[role])).rows[0].p,false);assert.equal((await db.query("select has_function_privilege($1,'neptune_v2_private.native_public_projection(jsonb,jsonb,jsonb,jsonb,timestamptz)','execute') p",[role])).rows[0].p,false);assert.equal((await db.query("select has_table_privilege($1,'neptune_v2_private.native_inventory','select') p",[role])).rows[0].p,false);}await db.close();});
