// Actual candidate SQL and engine; pg_net transport only is stubbed. No live calls.
import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const db=new PGlite();const q=async(s,a=[])=>(await db.query(s,a)).rows;
await db.exec(`create role anon;create role authenticated;create role service_role;
create schema auth;create function auth.uid() returns uuid language sql as $$select null::uuid$$;create table public.paper_control(id int,owner_id uuid);
create schema net;create schema cron;
create table net.calls(id bigserial primary key,url text,body jsonb,method text);
create table net._http_response(id bigint primary key,status_code int,content_type text,headers jsonb,content text,timed_out bool,error_msg text,created timestamptz);
create function net.http_get(url text,params jsonb,headers jsonb,timeout_milliseconds int) returns bigint language sql as $$insert into net.calls(url,method) values(url,'GET') returning id$$;
create function net.http_post(url text,body jsonb,params jsonb,headers jsonb,timeout_milliseconds int) returns bigint language sql as $$insert into net.calls(url,body,method) values(url,body,'POST') returning id$$;
create table cron.job_run_details(jobid bigint,return_message text);create table cron.job(jobid bigint,jobname text,username text,database text,command text,active bool);
create function cron.alter_job(job_id bigint,active boolean) returns void language sql as $$update cron.job set active=$2 where jobid=$1$$;
create function cron.unschedule(job_id bigint) returns boolean language sql as $$update cron.job set active=false where jobid=$1 returning true$$;
create table public.observed_scans(payload jsonb);`);
for(const f of ['schema.sql','core.sql','owner-access.sql','native-economics.sql','native-ledger.sql','native-order-rules.sql','native-scanner-helpers.sql','native-audit.sql','native-public-projection.sql','collector.sql','native-collector.sql','collector-integration.sql'])await db.exec(await fs.readFile(new URL('../'+f,import.meta.url),'utf8'));
// Test-only call counter still invokes the actual engine, never a fake process_scan.
await db.exec(`alter function neptune_v2_private.process_scan(jsonb) rename to tested_process_scan;
create function neptune_v2_private.process_scan(o jsonb) returns jsonb language plpgsql as $$begin insert into public.observed_scans values(o);return neptune_v2_private.tested_process_scan(o);end$$;
insert into neptune_v2_private.build_metadata values(6,repeat('b',64),'00f878a855d0b8f65b57473bc0d2c89efde617b72ca5643b14ed05aa55afa8f8',now());
select neptune_v2_private.initialize('AUD');insert into public.neptune_paper_v2_control(id,owner_id) values('neptune-paper-v2','00000000-0000-0000-0000-000000000001');select neptune_v2_private.allocate_specialists();update public.neptune_paper_v2_control set enabled=true;select neptune_v2_private.sync_control();
insert into cron.job values(9,'neptune-v2-feed-guard',current_user,current_database(),'set statement_timeout=''8s''; select neptune_v2_private.feed_tick();',true);
insert into neptune_v2_private.feed_control(id,started_at,contract_verified,job_id,job_owner,job_database) values(true,clock_timestamp(),true,9,current_user,current_database());`);
const native=JSON.parse(await fs.readFile(new URL('./fixtures/normalized-native.json',import.meta.url),'utf8'));
const metadata={};for(const m of native.markets)metadata[m.venue]={...m.metadata,at:new Date(Date.now()-1000).toISOString()};for(const f of Object.values(native.quote_fx))metadata[f.base]={...f.metadata,at:new Date(Date.now()-1000).toISOString()};
await q("insert into neptune_mv_private.control(id,started_at,enabled,contract_verified,metadata) values(true,clock_timestamp(),true,true,$1)",[JSON.stringify(metadata)]);
const assets=['ETH/USD','SOL/USD','AVAX/USD','LINK/USD','AAVE/USD','UNI/USD'];
const fxDate=new Date(Date.now()-86400000).toISOString().slice(0,10);
function legacy(kind,asset){const ms=Date.now(),at=ms/1000,start=Math.floor(ms/900000)*900000;if(kind==='fx')return[{base:'USD',quote:'AUD',rate:1.5,date:fxDate}];let result;
 if(kind==='metadata')result=Object.fromEntries(assets.map(a=>[a,{wsname:a,altname:a.replace('/',''),base:a.split('/')[0],quote:'USD',aclass_base:'currency',aclass_quote:'currency',status:'online',lot:'unit',lot_multiplier:1,ordermin:'0.001',costmin:'1',tick_size:'0.01',lot_decimals:6}]));
 if(kind==='depth')result={[asset]:{bids:[['100','100000',at-1]],asks:[['100.01','100000',at-1]]}};
 if(kind==='trade')result={[asset]:[['100','10',at-1,'b','m','',1]]};
 if(kind==='bars')result={[asset]:Array.from({length:97},(_,i)=>[(start-(96-i)*900000)/1000,'100','101','99','100','100','1000',100])};
 return{error:[],result};}
function multivenue(v,k,price=100){const ms=Date.now(),start=Math.floor(ms/900000)*900000;if(k==='depth')return v==='binance'?{lastUpdateId:123,bids:[[String(price),'100000']],asks:[[String(price+.01),'100000']]}:{coin:'@107',time:ms-10,levels:[[{px:String(price),sz:'100000',n:1}],[{px:String(price+.01),sz:'100000',n:1}]]};
 if(k==='fx')return{error:[],result:{[v+'/USD']:{bids:[['0.999','100000',ms/1000-1]],asks:[['1.001','100000',ms/1000-1]]}}};
 if(k==='metadata')return{error:'temporary metadata outage'};
 if(k==='avg_price')return{mins:5,price:String(price),closeTime:ms-10};
 if(k==='trades')return v==='binance'?[{id:1,price:'100',qty:'10',time:ms-10}]:[{coin:'@107',px:'100',sz:'10',time:ms-10,tid:1}];
 if(k==='bars')return Array.from({length:97},(_,i)=>{let t=start-(96-i)*900000;return v==='binance'?[t,'100','101','99','100','1000',t+899999,'100000',100,'500','50000','0']:{s:'@107',i:'15m',t,T:t+899999,o:'100',h:'101',l:'99',c:'100',v:'1000',n:100};});
 throw Error('Unexpected request '+v+' '+k);}
async function respond({legacyStatus=200,nativeDeny=null,omitLegacy=false,onlyLegacy=false,onlyNative=false,nativePrice=100}={}){
 if(!onlyNative)for(const r of await q('select * from neptune_v2_private.feed_requests')){
  if(omitLegacy&&r.kind!=='fx')continue;const status=r.kind==='fx'?200:legacyStatus;
  await q("insert into net._http_response values($1,$2,'application/json','{}',$3,false,null,clock_timestamp())",[r.request_id,status,JSON.stringify(legacy(r.kind,r.asset))]);
 }
 if(!onlyLegacy)for(const r of await q('select * from neptune_mv_private.requests')){const status=r.venue===nativeDeny?403:r.kind==='metadata'?503:200;await q("insert into net._http_response values($1,$2,'application/json','{}',$3,false,null,clock_timestamp())",[r.request_id,status,JSON.stringify(multivenue(r.venue,r.kind,nativePrice))]);}
}
const tick=()=>db.exec('select neptune_v2_private.feed_tick()');const scans=()=>q('select payload from public.observed_scans');let passed=0;const ok=s=>{passed++;console.log('PASS',s);};
await db.exec('begin');await tick();assert.equal((await q('select count(*) n from net.calls'))[0].n,29);assert.equal((await q('select count(*) n from neptune_v2_private.feed_requests'))[0].n,20);assert.equal((await q("select neptune_v2_private.feed_url('depth','binance:SOLUSDT') x"))[0].x,null);assert((await q("select request_url from neptune_v2_private.feed_requests")).every(r=>!r.request_url.includes('binance:')&&!r.request_url.includes('@107')));let timing=(await q('select l.pending_at>=n.pending_at ordered from neptune_v2_private.feed_control l cross join neptune_mv_private.control n'))[0];assert.equal(timing.ordered,true);await respond();await tick();let out=await scans();assert.equal(out.length,1);assert.equal(out[0].payload.markets.length,8);assert.equal(Object.keys(out[0].payload.quote_fx).length,2);assert.equal(out[0].payload.fx.rate_date,fxDate);assert.equal(out[0].payload.fx.at,fxDate+'T00:00:00+00:00');assert.equal((await q('select count(*) n from neptune_v2_private.observations'))[0].n,1);assert.equal((await q('select count(*) n from cron.job'))[0].n,1);assert.equal((await q('select outcome from neptune_v2_private.feed_events'))[0].outcome,'processed');await tick();assert.equal((await scans()).length,1);await fs.writeFile(path.join(os.tmpdir(),'neptune-test-collector-merged-synthetic.json'),JSON.stringify(out[0].payload,null,2));await db.exec('rollback');ok('one actual engine scan merges six legacy + two native + stablecoin crosses; same sole cron, no native Kraken symbols or FX restamping');
await db.exec('begin');await tick();await respond({onlyLegacy:true});await tick();assert.equal((await scans()).length,0);assert((await q('select pending_epoch from neptune_mv_private.control'))[0].pending_epoch);await respond({onlyNative:true});await tick();assert.equal((await scans()).length,1);assert.equal((await scans())[0].payload.markets.length,8);await db.exec('rollback');ok('native response waits within existing batch deadline and is not consumed or discarded early');
await db.exec('begin');await tick();await respond({legacyStatus:403});await tick();out=await scans();assert.equal(out.length,1);assert.equal(out[0].payload.markets.filter(m=>m.book).length,2);assert.deepEqual(out[0].payload.quote_fx,{});assert(out[0].payload.native_feed.provider_blocked.kraken);assert.equal((await q('select terminal from neptune_v2_private.feed_control'))[0].terminal,false);assert.equal((await q('select terminal from neptune_mv_private.control'))[0].terminal,false);assert.equal((await q('select count(*) n from neptune_v2_private.observations'))[0].n,1);await db.exec('rollback');ok('legacy Kraken403 still delivers native books in one actual scan; crosses blocked, no global stop');
await db.exec('begin');await tick();await respond({omitLegacy:true});await db.exec("update neptune_v2_private.feed_control set pending_at=clock_timestamp()-interval '16 seconds';update neptune_mv_private.control set pending_at=clock_timestamp()-interval '17 seconds';alter table neptune_v2_private.feed_requests disable trigger immutable_rows;update neptune_v2_private.feed_requests set sent_at=clock_timestamp()-interval '16 seconds' where kind<>'fx';alter table neptune_v2_private.feed_requests enable trigger immutable_rows");await tick();out=await scans();assert.equal(out.length,1);assert.equal(out[0].payload.markets.filter(m=>m.book).length,2);assert(out[0].payload.native_feed.provider_blocked.kraken);assert.equal((await q('select count(*) n from neptune_v2_private.observations'))[0].n,1);await db.exec('rollback');ok('unresolved legacy Kraken at bounded deadline cannot strand valid native batch; actual engine sees native protective data');
await db.exec('begin');await tick();await respond({nativeDeny:'binance'});await tick();out=await scans();assert.equal(out.length,1);assert.equal(out[0].payload.markets.length,7);assert(out[0].payload.markets.some(m=>m.asset==='hyperliquid:@107'));assert(out[0].payload.native_feed.provider_blocked.binance);assert.equal((await q('select count(*) n from neptune_v2_private.observations'))[0].n,1);await db.exec('rollback');ok('native Binance403 leaves legacy and Hyper books available in same scan');
await db.exec('begin');await db.exec("update public.neptune_paper_v2_control set enabled=false");await tick();assert.equal((await q('select count(*) n from net.calls'))[0].n,0);assert.equal((await scans()).length,0);await db.exec('rollback');ok('owner-disabled prevents native tick and all dispatch');
await db.exec('begin');await q('update neptune_mv_private.control set provider_blocked=$1',[JSON.stringify({kraken:{permanent:true,reason:'access_denied'}})]);await tick();assert((await q('select url from net.calls')).every(r=>!r.url.startsWith('https://api.kraken.com/')));assert.equal((await q('select count(*) n from neptune_v2_private.feed_requests'))[0].n,1);await db.exec('rollback');ok('existing Kraken provider denial suppresses both legacy API retries and conversion reads');
// Establish actual reconciled native inventory through the real engine, then use
// one scheduled mixed observation for a protective sale during metadata+Kraken outage.
await db.exec('begin');
const initial=JSON.parse(await fs.readFile(path.join(os.tmpdir(),'neptune-test-collector-merged-synthetic.json'),'utf8'));
function seed(price=104,signal=true,fx=true){const o=structuredClone(initial),at=new Date().toISOString();o.at=at;if(!fx)o.fx=null;for(const m of o.markets){m.received_at=at;m.book.at=at;m.metadata.at=at;m.trade_at=at;if(m.asset==='binance:SOLUSDT'){m.bars=m.bars.map(b=>({...b,o:'100',h:'103',l:'97',c:'100',v:'1000'}));m.book.bids=[[String(price),'100000']];m.book.asks=[[String(price+.01),'100000']];m.avg_price={price:String(price),mins:5,at,received_at:at,source:'https://data-api.binance.vision/api/v3/avgPrice?symbol=SOLUSDT'};if(signal)Object.assign(m.bars.at(-1),{c:'104',h:'105',l:'100',v:'1600'});}}for(const f of Object.values(o.quote_fx)){f.received_at=at;f.book.at=at;f.metadata.at=at;}return o;}
const previous=initial.markets[0].bars.at(-1).t-900000;await q("update neptune_v2_private.account set state=jsonb_set(state,'{last_bar}',$1)",[JSON.stringify(Object.fromEntries([...assets,'binance:SOLUSDT','hyperliquid:@107'].map(a=>[a,previous])))]);
await q('select neptune_v2_private.tested_process_scan($1)',[JSON.stringify(seed())]);await q('select neptune_v2_private.tested_process_scan($1)',[JSON.stringify(seed())]);assert.equal((await q("select count(*) n from neptune_v2_private.fills where payload->>'asset'='binance:SOLUSDT' and payload->>'side'='buy'"))[0].n,1);
await q('select neptune_v2_private.tested_process_scan($1)',[JSON.stringify(seed(80,false,false))]);assert.equal((await q('select state from neptune_v2_private.account'))[0].state.pending['binance:SOLUSDT'].side,'sell');
await q("update neptune_mv_private.control set metadata=jsonb_set(metadata,'{binance,at}',to_jsonb((clock_timestamp()-interval '2 hours')::text))");await tick();assert((await q("select * from neptune_mv_private.requests where venue='binance' and kind='avg_price'"))[0].protective_only);await respond({legacyStatus:403,nativePrice:79});await tick();out=await scans();assert.equal(out.length,1);assert(out[0].payload.markets.find(m=>m.asset==='binance:SOLUSDT').protective_only);assert(out[0].payload.markets.find(m=>m.asset==='binance:SOLUSDT').avg_price);const sale=(await q("select payload from neptune_v2_private.fills where payload->>'asset'='binance:SOLUSDT' and payload->>'side'='sell'"))[0].payload;assert.equal(sale.quote_currency,'USDT');assert.equal(sale.net_usd,null);assert.equal(sale.cash_delta_base,null);assert(sale.net_quote_delta>0);assert.equal((await q('select count(*) n from neptune_v2_private.native_receivables'))[0].n,1);await q('select neptune_v2_private.native_scan_reconcile()');await db.exec('rollback');ok('one scheduled mixed scan executes real protective Binance sale with held rules+fresh avgPrice during metadata503/legacyKraken403; exact USDT proceeds await conversion');
await db.exec('begin');await tick();await respond({nativeDeny:'USDT'});await tick();out=await scans();assert.equal(out.length,1);assert.equal(out[0].payload.markets.filter(m=>m.book).length,2);assert.deepEqual(out[0].payload.quote_fx,{});assert(out[0].payload.native_feed.provider_blocked.kraken);await db.exec('rollback');ok('native conversion-provider denial is preflighted before legacy parsing; no Kraken entry quotes leak through same scan');
const t=Date.now(),receipt=new Date(t-5000).toISOString(),cutoff=new Date(t).toISOString();
for(const [kind,body]of [['depth',{error:[],result:{'ETH/USD':{bids:[['100','10',(t-1000)/1000]],asks:[['101','10',(t-1000)/1000]]}}}],['trade',{error:[],result:{'ETH/USD':[['100','10',(t-1000)/1000,'b','m','',1]]}}]])assert.equal((await q("select neptune_v2_private.feed_parse($1,'ETH/USD',$2,$3,$4) p",[kind,JSON.stringify(body),receipt,cutoff]))[0].p,null);
const edge=Math.floor(t/900000)*900000;const bars=Array.from({length:23},(_,i)=>[(edge-(23-i)*900000)/1000,'100','101','99','100','100','1000',100]);const parsed=(await q("select neptune_v2_private.feed_parse('bars','ETH/USD',$1,$2,$3) p",[JSON.stringify({error:[],result:{'ETH/USD':bars}}),new Date(edge-1000).toISOString(),new Date(edge+1000).toISOString()]))[0].p;if(parsed)assert(parsed.bars.every(b=>b.t+900000<=edge-1000));ok('legacy parser now enforces receipt-time source events and completed candles across delayed collection');
await db.exec('begin');await tick();await respond();await db.exec("create or replace function neptune_mv_private.collect(owner_epoch bigint) returns jsonb language plpgsql as $$begin raise exception 'synthetic native parser failure';end$$");await tick();out=await scans();assert.equal(out.length,1);assert.equal(out[0].payload.markets.length,6);assert.equal(out[0].payload.native_feed.feed_terminal,true);assert.equal((await q('select terminal from neptune_v2_private.feed_control'))[0].terminal,false);await db.exec('rollback');ok('isolated native collector exception does not roll back or suppress actual legacy scan');
await db.exec('begin');await tick();await respond();await db.exec("alter function neptune_mv_private.tick(bigint) rename to tested_native_tick;create function neptune_mv_private.tick(owner_epoch bigint) returns jsonb language plpgsql as $$declare r jsonb;begin r:=neptune_mv_private.tested_native_tick(owner_epoch);if r->'snapshot'<>'null'::jsonb then r:=jsonb_set(r,'{snapshot,markets,0,synthetic_padding}',to_jsonb(repeat('x',150000)));end if;return r;end$$");await tick();out=await scans();assert.equal(out.length,1);assert.equal(out[0].payload.markets.length,6);assert.equal(out[0].payload.native_feed.snapshot_rejected,true);assert.equal((await q('select count(*) n from neptune_v2_private.observations'))[0].n,1);await db.exec('rollback');ok('synthetic oversized native envelope explicitly freezes native side while preserving single bounded legacy scan');
await db.exec('begin');await tick();await respond();await db.exec('update public.neptune_paper_v2_control set enabled=false');await tick();await db.exec('update public.neptune_paper_v2_control set enabled=true');await tick();assert.equal((await scans()).length,0);assert.equal((await q('select count(*) n from net.calls'))[0].n,29);await db.exec('rollback');ok('owner Stop/Resume epoch fence never admits the already-issued previous-owner batch');
await fs.writeFile(path.join(os.tmpdir(),'neptune-test-collector-integration-test-report.json'),JSON.stringify({groups_passed:passed,actual_engine:true,transport:'synthetic pg_net',cron_count:1,live_mutations:false},null,2));await db.close();
