import {historicalAllVenuePolicy} from './fixtures/historical-policy.mjs';
import {validateHistoryRow,historyCsv} from './reader/paper-history-v2.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();const q=async(s,a=[])=>(await db.query(s,a)).rows;
await db.exec('create role anon;create role authenticated;create role service_role;create schema auth;create function auth.uid() returns uuid language sql as $$select null::uuid$$;create table public.paper_control(id int,owner_id uuid);');
for(const f of ['schema.sql','core.sql','owner-access.sql','native-economics.sql','native-ledger.sql','native-order-rules.sql','native-scanner-helpers.sql','native-audit.sql','native-public-projection.sql'])await db.exec(await fs.readFile(new URL('../'+f,import.meta.url),'utf8'));
await db.exec(historicalAllVenuePolicy);
await db.exec("insert into neptune_v2_private.build_metadata values(6,repeat('b',64),'00f878a855d0b8f65b57473bc0d2c89efde617b72ca5643b14ed05aa55afa8f8',now());select neptune_v2_private.initialize('AUD');insert into public.neptune_paper_v2_control(id,owner_id) values('neptune-paper-v2','00000000-0000-0000-0000-000000000001');select neptune_v2_private.allocate_specialists();update public.neptune_paper_v2_control set enabled=true;select neptune_v2_private.sync_control();");
const native=JSON.parse(await fs.readFile(new URL('./fixtures/normalized-native.json',import.meta.url),'utf8'));
const assets=['ETH/USD','SOL/USD','AVAX/USD','LINK/USD','AAVE/USD','UNI/USD'];
function fixture(price=104,signal=true,fxok=true){const ms=Date.now(),at=new Date(ms).toISOString(),t=Math.floor(ms/900000)*900000;const out={at,fx:fxok?{base:'USD',quote:'AUD',rate:1.5,source:'Frankfurter ECB reference',at:new Date(ms-86400000).toISOString(),rate_date:new Date(ms-86400000).toISOString().slice(0,10),fetched_at:at}:null,markets:assets.map(asset=>({asset,received_at:at,book:{at,bids:[[104,10000]],asks:[[104.01,10000]]},metadata:{asset,venue:'Kraken',kind:'spot',quote:'USD',status:'online',source:'https://api.kraken.com/0/public/AssetPairs',at,tick_size:.01,min_qty:.001,min_cost:1,qty_decimals:6},trade_at:at,volume_24h_usd:10000000,bars:Array.from({length:22},(_,i)=>({t:t-(22-i)*900000,o:100,h:103,l:97,c:100,v:100}))})),quote_fx:structuredClone(native.quote_fx)};
for(const m0 of native.markets){const m=structuredClone(m0);m.received_at=at;m.metadata.at=at;m.trade_at=at;m.book.at=at;m.book.bids=[[String(price),'100000']];m.book.asks=[[String(price+.01),'100000']];m.avg_price={price:String(price),mins:5,at,received_at:at,source:'https://data-api.binance.vision/api/v3/avgPrice?symbol=SOLUSDT'};m.bars=Array.from({length:96},(_,i)=>({t:t-(96-i)*900000,o:100,h:103,l:97,c:100,v:1000}));if(signal&&m.asset===(typeof signal==='string'?signal:'binance:SOLUSDT'))Object.assign(m.bars.at(-1),{c:104,h:105,l:100,v:1600});out.markets.push(m);}
for(const [k,v]of Object.entries(out.quote_fx)){v.asset=k;v.received_at=at;v.metadata.at=at;v.book.at=at;v.book.bids=[['0.999','100000000']];v.book.asks=[['1.001','100000000']];}
return out;}
const scan=async o=>(await q('select neptune_v2_private.process_scan($1::jsonb) p',[JSON.stringify(o)]))[0].p;
test('native completed-bar intent then later real-source paper buy',async()=>{const previous=fixture().markets[0].bars.at(-1).t-900000;await q("update neptune_v2_private.account set state=jsonb_set(state,'{last_bar}',$1)",[Object.fromEntries([...assets,'binance:SOLUSDT','hyperliquid:@107'].map(a=>[a,previous]))]);let p=await scan(fixture());let rows=await q("select payload from neptune_v2_private.orders where payload->>'asset'='binance:SOLUSDT'");assert.equal(rows.length,1,'native signal must create intent');assert.equal(p.account.fills,0);p=await scan(fixture());rows=await q("select payload from neptune_v2_private.fills where payload->>'asset'='binance:SOLUSDT'");assert.equal(rows.length,1,'native later observation must fill');assert.equal(rows[0].payload.quote_currency,'USDT');assert.equal(rows[0].payload.fee_currency,'SOL');await q('select neptune_v2_private.native_scan_reconcile()');});
test('protective native sell keeps typed proceeds and verified dust, then later settles once',async()=>{let report=await scan(fixture(80,false,false));let pos=(await q("select payload from neptune_v2_private.positions where asset='binance:SOLUSDT'"))[0].payload;assert(pos.qty>0);const pending=(await q('select state from neptune_v2_private.account'))[0].state.pending['binance:SOLUSDT'];assert.equal(pending.side,'sell');report=await scan(fixture(79,false,false));const fills=await q("select payload from neptune_v2_private.fills where payload->>'asset'='binance:SOLUSDT' order by at");assert.equal(fills.length,2);const sale=fills[1].payload;assert.equal(sale.cash_delta_base,null);assert.equal(sale.net_usd,null);assert.equal(sale.quote_currency,'USDT');assert(sale.net_quote_delta>0);assert.equal((await q('select coalesce(sum(delta),0) n from neptune_v2_private.usd_ledger'))[0].n,'0');const inv=(await q("select * from neptune_v2_private.native_inventory where asset='binance:SOLUSDT'"))[0];assert(Number(inv.qty)>0&&Number(inv.qty)<Number(inv.qty_step));assert.equal(report.account.equity,null);await q('select neptune_v2_private.native_scan_reconcile()');report=await scan(fixture(79,false,true));assert.equal((await q('select count(*) n from neptune_v2_private.native_settlement_attribution'))[0].n,1);await scan(fixture(79,false,true));assert.equal((await q('select count(*) n from neptune_v2_private.native_settlement_attribution'))[0].n,1);assert.equal((await q('select count(*) n from neptune_v2_private.native_receivables r where not exists(select 1 from neptune_v2_private.native_settlement_attribution a where a.exit_fill_id=r.exit_fill_id)'))[0].n,0);});
test('Hyperliquid spot received-HYPE fee and depeg-safe target lifecycle',async()=>{const prev=fixture().markets[0].bars.at(-1).t-900000;await q("update neptune_v2_private.account set state=jsonb_set(state,'{last_bar,hyperliquid:@107}',to_jsonb($1::bigint))",[prev]);
 const hfixture=(price=20.8,signal=true,fxok=true)=>{const o=fixture(104,signal?'hyperliquid:@107':false,fxok);const m=o.markets.find(x=>x.asset==='hyperliquid:@107');m.book.bids=[[String(price),'100000']];m.book.asks=[[String(price+.001),'100000']];m.bars=m.bars.map(b=>({...b,o:b.o*.2,h:b.h*.2,l:b.l*.2,c:b.c*.2}));return o;};
 let report=await scan(hfixture());assert.equal((await q("select count(*) n from neptune_v2_private.orders where payload->>'asset'='hyperliquid:@107' and payload->>'side'='buy'"))[0].n,1);report=await scan(hfixture());const f=(await q("select payload from neptune_v2_private.fills where payload->>'asset'='hyperliquid:@107' and payload->>'side'='buy'"))[0].payload;assert.equal(f.quote_currency,'USDC');assert.equal(f.fee_currency,'HYPE');assert.equal(f.fee_rate,.0007);assert(f.net_inventory_delta<f.gross_qty);let p=(await q("select payload from neptune_v2_private.positions where asset='hyperliquid:@107'"))[0].payload;assert(p.initial_risk_base<=5);
 const depeg=hfixture(p.target+1,false);depeg.quote_fx['USDC/USD'].book.bids=[['0.70','100000000']];depeg.quote_fx['USDC/USD'].book.asks=[['0.701','100000000']];await scan(depeg);let state=(await q('select state from neptune_v2_private.account'))[0].state;assert.equal(state.pending['hyperliquid:@107'],undefined,'quote target cannot fabricate AUD2R during depeg');
 report=await scan(hfixture(p.stop-1,false,false));report=await scan(hfixture(p.stop-2,false,false));const sale=(await q("select payload from neptune_v2_private.fills where payload->>'asset'='hyperliquid:@107' and payload->>'side'='sell'"))[0].payload;assert.equal(sale.net_usd,null);assert.equal(sale.quote_currency,'USDC');assert.equal(report.account.equity,null);await scan(hfixture(p.stop-2,false,true));await q('select neptune_v2_private.native_scan_reconcile()');assert.equal((await q("select count(*) n from neptune_v2_private.native_settlement_attribution"))[0].n,2);
});
test.after(()=>db.close());

test('both native lifecycles and mixed legacy audit validate through exact public reader and CSV',async()=>{
 const rows=(await q('select to_jsonb(h) r from public.neptune_paper_v2_history h order by seq')).map(x=>x.r);
 assert(rows.some(r=>!r.kind.startsWith('native_')));
 for(const row of rows)assert.doesNotThrow(()=>validateHistoryRow(row),JSON.stringify(row));
 for(const asset of ['binance:SOLUSDT','hyperliquid:@107']){
  const events=rows.filter(r=>r.payload.asset===asset);
  for(const kind of ['native_orders','native_fills','native_receivables','native_settlements','native_fill_attribution','native_quote_ledger','native_settlement_attribution'])assert(events.some(r=>r.kind===kind),asset+' missing '+kind);
  assert(events.some(r=>r.payload.verified_fee_dust===true));
  for(const row of events.filter(r=>['native_orders','native_fills','native_settlements'].includes(r.kind))){assert.match(row.payload.native_model_hash,/^[a-f0-9]{64}$/);assert(historyCsv([row]).includes(row.payload.native_model_hash));}
 }
 assert(historyCsv(rows).includes('PAPER_SIMULATED'));
 if(process.env.NEPTUNE_TEST_HISTORY_OUT)await fs.writeFile(process.env.NEPTUNE_TEST_HISTORY_OUT,JSON.stringify(rows,null,2));
});
