import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const files=['schema.sql','core.sql','owner-access.sql','collector.sql','native-economics.sql','native-ledger.sql','native-order-rules.sql','native-scanner-helpers.sql','native-audit.sql','native-public-projection.sql'];const hash=createHash('sha256');for(const f of files)hash.update(await fs.readFile(new URL('../'+f,import.meta.url)));const source=hash.digest('hex');assert.match(source,/^[a-f0-9]{64}$/);
const config=createHash('sha256').update(await fs.readFile(new URL('../config.json',import.meta.url))).digest('hex');const results=[];const assets=['ETH/USD','SOL/USD','AVAX/USD','LINK/USD','AAVE/USD','UNI/USD'];
function fixture(price=104,signal=false,outage=false){const ms=Date.now(),at=new Date(ms).toISOString(),t=Math.floor(ms/900000)*900000;return {at,fx:outage?null:{base:'USD',quote:'AUD',rate:1.5,source:'Frankfurter ECB reference',at:new Date(ms-86400000).toISOString(),rate_date:new Date(ms-86400000).toISOString().slice(0,10),fetched_at:at},markets:assets.map(asset=>{const bars=Array.from({length:22},(_,i)=>({t:t-(22-i)*900000,o:100,h:103,l:97,c:100,v:100}));if(signal&&asset==='ETH/USD')Object.assign(bars.at(-1),{c:104,h:105,l:100,v:160});return {asset,received_at:at,book:{at,bids:[[price,10000]],asks:[[price*1.0001,10000]]},metadata:{asset,venue:'Kraken',kind:'spot',quote:'USD',status:'online',source:'https://api.kraken.com/0/public/AssetPairs',at,tick_size:.01,min_qty:.001,min_cost:1,qty_decimals:6},trade_at:at,volume_24h_usd:10000000,bars:outage?null:bars};})};}
const close=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`);
for(const scenario of ['initial_stop','target','trailing_stop']){
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'neptune-lifecycle-'));let db=new PGlite(dir);const q=async(s,a=[])=>(await db.query(s,a)).rows;const scan=async(o)=>{await new Promise(r=>setTimeout(r,3));return (await q('select neptune_v2_private.process_scan($1::jsonb) r',[JSON.stringify(o)]) )[0].r;};
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create function auth.uid() returns uuid language sql as $$select null::uuid$$;create table public.paper_control(id int,owner_id uuid);`);
 for(const f of files)await db.exec(await fs.readFile(new URL('../'+f,import.meta.url),'utf8'));
 await q('insert into neptune_v2_private.build_metadata(id,source_hash,config_hash) values(3,$1,$2)',[source,config]);await db.exec("select neptune_v2_private.initialize('AUD');insert into public.neptune_paper_v2_control(id,owner_id) values('neptune-paper-v2','00000000-0000-0000-0000-000000000001');select neptune_v2_private.allocate_specialists();update public.neptune_paper_v2_control set enabled=true;select neptune_v2_private.sync_control()");
 // Isolated fixture setup represents a prior consumed bar, never a production scan/state edit.
 const previous=fixture().markets[0].bars.at(-1).t-900000;await q("update neptune_v2_private.account set state=jsonb_set(state,'{last_bar}',$1::jsonb)",[JSON.stringify(Object.fromEntries(assets.map(a=>[a,previous])))]);
 let r=await scan(fixture(104,true));assert.equal(r.account.fills,0);assert.equal((await q('select count(*) n from neptune_v2_private.orders'))[0].n,1);
 r=await scan(fixture(104,true));assert.equal(r.account.fills,1);assert.equal(r.positions.length,1);let p=r.positions[0];assert.equal(p.asset,'ETH/USD');assert(p.initial_risk_base<=5);assert(-r.fills[0].cash_delta_base<=200);assert.equal(r.fills[0].venue,'Kraken');assert.equal(r.fills[0].specialist_id,'ethereum');assert.equal(r.specialist_accounts.accounts.filter(a=>a.execution_kind==='spot_paper').length,2);const buy=r.fills[0],initialStop=p.stop;await q('select neptune_v2_private.specialist_reconcile()');
 assert(Date.parse(buy.at)>Date.parse((await q('select payload from neptune_v2_private.orders'))[0].payload.at));close(buy.price,104.28);close(buy.gross_usd,buy.qty*buy.price);close(buy.fee_usd,buy.gross_usd*.008);close(buy.cash_delta_base,-(buy.gross_usd+buy.fee_usd)*1.50375);assert.equal(buy.source_hash,source);
 const persisted=(await q('select cash,state from neptune_v2_private.account'))[0];await db.close();db=new PGlite(dir);assert.deepEqual((await q('select cash,state from neptune_v2_private.account'))[0],persisted);
 let trigger,execution;
 if(scenario==='initial_stop'){trigger=initialStop-1;execution=initialStop-8;assert.equal(p.trailing_active,false);}
 if(scenario==='target'){trigger=p.target+2;execution=p.target+1;}
 if(scenario==='trailing_stop'){r=await scan(fixture(125));p=r.positions[0];assert.equal(p.trailing_active,true);assert(p.stop>initialStop);assert.equal(r.account.fills,1);const peakStop=p.stop;r=await scan(fixture(124));p=r.positions[0];assert(p.stop>=peakStop);trigger=p.stop-.2;execution=p.stop-1;assert(execution>initialStop);assert(trigger<p.target);}
 const outage=scenario==='initial_stop';r=await scan(fixture(trigger,false,outage));assert.equal(r.account.fills,1);const pending=(await q('select state from neptune_v2_private.account'))[0].state.pending['ETH/USD'];assert.equal(pending.side,'sell');assert.equal(pending.reason,scenario==='target'?'net_r_target':'protective_stop');
 await db.close();db=new PGlite(dir);assert.deepEqual((await q('select state from neptune_v2_private.account'))[0].state.pending['ETH/USD'],pending);
 const staleBook=fixture(execution,false,outage);staleBook.markets[0].book.at=new Date(Date.now()-120000).toISOString();r=await scan(staleBook);assert.equal(r.account.fills,1);assert.equal((await q('select state from neptune_v2_private.account'))[0].state.pending['ETH/USD'].id,pending.id);
 const receipt=fixture(execution,false,outage);r=await scan(receipt);assert.equal(r.account.fills,2);assert.equal(r.positions.length,0);const sell=r.fills.find(f=>f.side==='sell');assert(Date.parse(sell.at)>Date.parse(pending.at));close(sell.price,Math.floor(execution*.9975/.01)*.01);close(sell.qty,buy.qty);close(sell.gross_usd,sell.qty*sell.price);close(sell.fee_usd,sell.gross_usd*.008);assert.equal((await scan(receipt)).duplicate,true);assert.equal((await q('select count(*) n from neptune_v2_private.fills'))[0].n,2);
 if(outage){assert.equal(sell.cash_delta_base,null);assert.equal(sell.fx,null);assert.equal(r.account.equity,null);close(r.account.unsettled_usd,sell.gross_usd-sell.fee_usd);const unsettledState=(await q('select cash,state from neptune_v2_private.account'))[0];await db.close();db=new PGlite(dir);assert.deepEqual((await q('select cash,state from neptune_v2_private.account'))[0],unsettledState);close(Number((await q('select sum(delta) n from neptune_v2_private.usd_ledger'))[0].n),sell.gross_usd-sell.fee_usd);r=await scan(fixture());assert.equal(r.settlements.length,1);assert.equal(r.account.unsettled_usd,0);await scan(fixture());assert.equal((await q('select count(*) n from neptune_v2_private.settlements'))[0].n,1);}
 else close(sell.cash_delta_base,(sell.gross_usd-sell.fee_usd)*1.49625);
 const cash=Number((await q('select cash from neptune_v2_private.account'))[0].cash),ledger=Number((await q('select sum(delta) n from neptune_v2_private.cash_ledger'))[0].n);close(cash,ledger);const pnl=buy.cash_delta_base+(sell.gross_usd-sell.fee_usd)*1.49625;close(cash,10000+pnl);close(r.account.realized_pnl,pnl);assert.equal(Number((await q('select sum(delta) n from neptune_v2_private.usd_ledger'))[0].n||0),0);assert(scenario==='initial_stop'?pnl<0:pnl>0);
 results.push({scenario,source_hash:source,isolated_fixture:true,buy_price:buy.price,sell_price:sell.price,qty:buy.qty,initial_stop:initialStop,trigger_bid:trigger,execution_bid:execution,realized_aud:pnl,ending_aud_cash:cash,fees_usd:buy.fee_usd+sell.fee_usd,round_trip_fills:2,restarted_with_open_position:true,restarted_with_pending_exit:true,deduplicated_receipt:true,stale_book_fresh_receipt_blocked:true,deferred_fx_settlement:outage,restarted_with_unsettled_fx:outage});console.log('PASS',scenario,'later-observation execution, two restarts, dedup, costs and AUD reconciliation');await db.close();
}
await fs.writeFile(path.join(os.tmpdir(),'neptune-test-lifecycle-results.json'),JSON.stringify(results,null,2));
