import test from 'node:test';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();const q=async(s,a=[])=>(await db.query(s,a)).rows;
await db.exec('create role anon;create role authenticated;create role service_role;');for(const f of ['schema.sql','core.sql'])await db.exec(await fs.readFile(new URL('../'+f,import.meta.url),'utf8'));await db.exec(await fs.readFile(new URL('../native-economics.sql',import.meta.url),'utf8'));
const batch=JSON.parse(await fs.readFile(new URL('./fixtures/normalized-native.json',import.meta.url),'utf8'));
const now=new Date().toISOString();const fx={base:'USD',quote:'AUD',rate:1.5,source:'Frankfurter ECB reference',at:now,fetched_at:now};
const meta=asset=>({...batch.markets.find(m=>m.asset===asset).metadata,at:now});
function quote(currency,bid=.98,ask=1.02,size=100000){return {asset:currency+'/USD',received_at:now,metadata:{asset:currency+'/USD',base:currency,quote:'USD',venue:'kraken',kind:'spot',status:'online',source:'https://api.kraken.com/0/public/AssetPairs',at:now},book:{at:now,timestamp_basis:'http_response_observed',bids:[[String(bid),String(size)]],asks:[[String(ask),String(size)]]}};}
const economics=async({asset='binance:SOLUSDT',side='buy',qty=1,price=100,m=meta(asset),f=fx,conversion=quote(asset.includes('binance')?'USDT':'USDC'),held=false}={})=>(await q('select neptune_v2_private.native_economics($1,$2,$3,$4,$5,$6,$7,$8,$9) p',[asset,side,qty,price,m,f,conversion,now,held]))[0].p;
test('collector SQL metadata round-trips without renamed denominations',async()=>{for(const a of ['binance:SOLUSDT','hyperliquid:@107'])assert.equal((await q('select neptune_v2_private.native_identity($1,$2,$3) p',[a,meta(a),now]))[0].p,true);});
test('Binance buy charges received SOL, retains explicit dust and USDT identity',async()=>{const p=await economics({qty:.123});assert.equal(p.quote_currency,'USDT');assert.equal(p.gross_qty,.123);assert.equal(p.fee_currency,'SOL');assert.equal(p.fee_qty,.000123);assert.equal(p.net_inventory_delta,.122877);assert.equal(p.sellable_inventory,.122);assert.equal(p.dust_inventory,.000877);assert.equal(p.net_quote_delta,-12.3);assert(p.cash_delta_base<-(12.3*1.02*1.5));});
test('Hyper spot fee uses HYPE inventory and proper5sig/int price rules',async()=>{const p=await economics({asset:'hyperliquid:@107',qty:1,price:40});assert.equal(p.fee_qty,.0007);assert.equal(p.net_inventory_delta,.9993);assert.equal(p.dust_inventory,.0093);assert.equal(p.fee_rate,.0007);assert.equal((await q("select neptune_v2_private.native_price('hyperliquid:@107',123456,'buy',$1) p",[meta('hyperliquid:@107')]))[0].p,'123456');});
test('protective native sale survives missing both conversion legs with correct currency',async()=>{const p=await economics({side:'sell',f:null,conversion:null});assert.equal(p.settlement_status,'pending_native_conversion');assert.equal(p.cash_delta_base,null);assert.equal(p.net_usd,null);assert.equal(p.net_quote_delta,99.9);assert.equal(p.quote_currency,'USDT');assert.equal(p.fee_currency,'USDT');});
test('persisted verified rules allow protective exit through metadata outage',async()=>{const m=meta('binance:SOLUSDT');m.at=new Date(Date.now()-172800000).toISOString();assert.equal(await economics({m}),null);const p=await economics({side:'sell',m,held:true,conversion:null});assert.equal(p.net_quote_delta,99.9);assert.equal(p.cash_delta_base,null);});
test('no peg, wrong stable currency, insufficient conversion depth all block buys',async()=>{assert.equal(await economics({conversion:null}),null);assert.equal(await economics({conversion:quote('USDC')}),null);assert.equal(await economics({conversion:quote('USDT',.98,1.02,.5)}),null);});
test('side-sensitive observed depeg affects AUD value',async()=>{const a=await economics({side:'sell',conversion:quote('USDT',.80,.81)});const b=await economics({side:'sell',conversion:quote('USDT',.98,.99)});assert(a.cash_delta_base<b.cash_delta_base);assert.equal(a.quote_conversion.raw_usd_per_quote,.8);});
test('fee dust cannot be sold as non-lot quantity; below minimum rejects',async()=>{assert.equal(await economics({side:'sell',qty:.122877}),null);assert.equal(await economics({side:'sell',qty:.001}),null);});
test('entry without exact identity or fee rules fails closed',async()=>{const m=meta('hyperliquid:@107');m.instrument_identity.base_token_index=149;assert.equal(await economics({asset:'hyperliquid:@107',m}),null);const b=meta('binance:SOLUSDT');delete b.fee_qty_decimals;assert.equal(await economics({m:b}),null);});
test('missing side or currency never becomes a sale',async()=>{assert.equal(await economics({side:null}),null);assert.equal((await q('select neptune_v2_private.native_quote_conversion(null,1,$1,$2,$3) p',['sell',quote('USDT'),now]))[0].p,null);assert.equal((await q('select neptune_v2_private.native_price($1,100,null,$2) p',['binance:SOLUSDT',meta('binance:SOLUSDT')]))[0].p,null);});
test.after(()=>db.close());

test('oversized quote conversion blocks buys and retains typed protective sell proceeds',async()=>{const conversion=quote('USDT',9999999,10000000);assert.equal(await economics({conversion}),null);const p=await economics({side:'sell',conversion});assert.equal(p.settlement_status,'pending_native_conversion');assert.equal(p.cash_delta_base,null);assert.equal(p.net_usd,null);assert.equal(p.net_quote_delta,99.9);});
